### PR TITLE
add layer: PDOK Luchtfoto Beeldmateriaal 25cm

### LINKED ISSUE #326: Add "Actueel_ortho25" WMTS layer as "best" imagery for the Netherlands
Redirected from
https://forum.openstreetmap.org/viewtopic.php?id=58096

In the Netherlands, we have now the newest Goverment Aerial Ortho Images, 2016 and 2017 is coming in a most recent actual version.
In [JOSM](https://josm.openstreetmap.de/wiki/Maps/Netherlands), it is in default entries.

In all editors:
In a country, when zooming in there must be a warning, that there is a newer/better aerial available and maybe set as default for that country.

Now, retags to older situations, this must be avoided. To get a better map quality.

What do you think?

I think there must be rules for editors to use the best possible layer in a area.
The setup of a editors, largely determine the quality of the mapping.

BING and Digtial Globe is not everywhere the best solution.
In the Netherlands for years BING was the best, thanks, but now all Openstreetmap mappers must be guided to the new ones.

### PR DESCRIPTION
**Pull request by tyrasd**
as requested in #326

### CODE REVIEW

**Comment by Klumbumbus** [comment]
I think
`http://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/search?facet.q=license%2FCC-BY&isChild=%27false%27&resultType=details&any_OR_title_OR_keyword=luchtfoto&fast=index&_content_type=json&from=1&to=20&sortBy=relevance`
should be placed into
`attribution: url:`

and

`https://forum.openstreetmap.org/viewtopic.php?pid=630995#p630995`
into
`license_url`

**Comment by tyrasd** [comment]
right

**Comment by AllroadsNL** [comment]
I noticed on
WMTS metadata
http://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/c82a783a-9a58-4761-a809-b4c5d90dcd35
This is a little hidden under right upper corner, button "weergave" choice "Volledige weergave 

> Juridische restricties
Overige beperkingen
Naamsvermelding verplicht: Beeldmateriaal.nl
Overige beperkingen
http://creativecommons.org/licenses/by/4.0/deed.nl

Attributtion Beeldmateriaal.nl

+        "attribution": {
 +            "text": "Nationaal Georegister, CC BY 4.0",
 This should be
+        "attribution": {
 +            "text": "Kadaster / Beeldmateriaal.nl, CC BY 4.0",

Because of the [explicit permission] (https://wiki.openstreetmap.org/wiki/Contributors#Kadaster.2FBeeldmateriaal) agreement, we set Kadaster in front of the text attribution.

Could you change that.

Also on [JOSM](https://josm.openstreetmap.de/wiki/Maps/Netherlands) this should be changed.
I saw in history Klumbumbus changed the JOSM file.
Could the atrribution also be shown on JOSM.
In ID, I see it.
Editors could also be used for other purposes. Non OSM activity.

On the forum they ask, why they can not zoom in, in potlach as far as in JOSM.
I believe this is the projection they use and the possiblity of other projections JOSM
http://geodata.nationaalgeoregister.nl/luchtfoto/wmts?&request=GetCapabilities&service=WMTS
or is this the bottleneck.
+        "max_zoom": 18,
 +        "best": true,

**Comment by tyrasd** [comment]
I've updated the attribution string now (see the linked commit above)

> `"max_zoom": 18`

Well, that's the maximum zoom level the WMTS service returns any data for at the moment. If the imagery is in principle available in better resolution (e.g. via WMS): could you contact the people from beeldmateriaal.nl / nationaalgeoregister.nl and ask them if they can update the WMTS service to offer a few more zoom levels. :smile:

**Comment by AllroadsNL** [comment]
Today we got a explicit permissions to use the Beeldmateriaal.nl logo for the aerial.
wsh-logo-beeldmateriaal-nederlanddefwebsite
and I cut of the Beeldmateriaal Nederdland.
102 105 px wsh-logo-beeldmateriaal-nederlanddefwebsite
I used the icon as a png and uploaded it to [this site](https://www.base64-image.de/) as others did, like for the BING aerial.
Could this also be used in the attribution?

For use in  elements:
`
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGYAAABpCAYAAADIiVa3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAADGZJREFUeF7tXQtwFVcZzoMmQJNAaUrKAK30Ncij1AJ5QFusqO04rdrpaHVaRzvVGR3rozM66miNndFaCElI0gsESIUktLk3kdS2xhlHoXlBEvK+N8+ScG9oa0GJI1PBSmH9/jsbJ73Zs3vu7p6zm2E788+l2T3/4/vOa/8952xiwlX237Fjx+YpinIYYWc7EXpiYmJbXl7eQ/hVnLDvWputra2lIEdxSmC/0LXgiHIMQS8OBALJLP24/lWnCCG7sH8Fv58WFb/r9La3t9+BoGuOHz/+c3RTSVoONjY2LgEoZxwm5q1QKJTiOgDtdgggLwIhxZD38e93W1pa0lk2cP1VJ0lRW0y13Ri4Th/IeBIyPg3sh1lOgrBHnSaF7KNFP+Y6IO1yCMFlgZCDMUAHWPqbmppuwL3vOE0MjS+QX8OPb6KifCtWOjs7M+3CSLoeBLUZEooBeRJk3a7The1wmhQO+5NHjx5dKB1QOwyihj2BAC/GBola+LxOF7YB91/iAMax6bM69vjtwEi6DoD/A3Wq+REA8be/t7W1LdOZHh92OykqMd+VDqpVg3D8ZyxwQcxPdUh5ANcvu50YqnDoDe6yipPU8tRSdICdpAdKHWKa3U6K6t8JjC9zpAJrxZjRUzquP+f26TFPxdCLwwp+Qso2NzfnwuELOoGdx7WlOq2lhQcUN9yDOEfgRxN+m1VpceXzDqVO4OCoAWhVLFIQ1Ce1JgpuIIHXB4w59wup8VaUwvmAQQCXAP6dOq3lz7wAuPQ+3dSSFWxNlwVQ3+YAq1GHlJVoLf/l0OHoc4uBf6+bBlBEQTV1Ypj9RWv5jg4x22c5KQqlakTga0onpeoBaD0HqGdZqQs1rf8fDh2ubS00NnZ0dCw3BaKIQuqA/xpAfUNH/ohrP2bZx7VsBPYnAx16+p2+RvG9iEqaKAJjT6eHgIeAh4CHgIeAh4CHgIfArEJg2cHRLellwVfTXwzW60laafAPH8O9rOAy9w7n8+gxssN9vSxYn7V3qD43EKmzS3IC4frs2si9riAwwzdYkfDbTiXhhS592dalLK0cydFy+pbA2ILkwp5JQx1GNnivwxfyefn+EeWeugkFxNgk4csb6iK3OE7MqkAoJbW4bzSBAt3ezZZt3cqcwt7TS8rfma/l9JIDI48Y6tDTb/La2kPjyqZaG4nxR/7qOCnkQLRr2tZ1RZcUAg3EzfcN1LGcXrh7cLtUYuBPSnGfko2Wkmdba4koOf4I86WfVMIyy4d/Ge1+jGosgMiqGH6K5dzc0v4jUomBz4v3DCmbbe3GQHJteKtUAljG5pWGXucCFK2KNb7cVjWaMaeo528J6O4MCTaqALzXYWtV1Zhy3+9PK5vRlZHY0KW9tx5jpePE3NYwmjqnqPekITEAIXlHz7k7Dg1rrlBcWjm+LrGg67I0UkBe0o4e5faDJ5XV1WNRgqYk28+eBOT4w5cwSejEb/sMCYQ7cgPhfMdJIQeyKodXJBb0XDQEFN1Y6s7+rgRGtnXRvsGnDcnlbQlm74OPqGTKRhCTV6tNDsaPblYMriBkyonFL41+xpAUdeBPLQvWMrvDsoFqx4nBmHOdb0B3zEErKXYVASxn0vYM5nMBitqYvnvoV5p60IpSSvrbuPSYbQ085UDMzRWj7Gcaf/jKJv+pvNlBjA81nWdGBmAWlI9o7r66fv9QOp5v3pU68GsQlVTQo6x7+ZTOBCA8sf417Wcw15GVUtJ3jKemJxZ0f5D50knNVfxL8Xe6ztUl8tR8M/egciFdhLGF/aCJ8YU24br/vxsCobRknpoenZH1nr3pUOQ6ragy94/cZzsplIXgTc3Qfc93KjeWD+mnZvynHnE/K/Bw+YG3Vidu7/nQEFSAlFzcF0pgrOlFV/Y4T6sztDPVUmAvrSyo3ITxYhnyYLxy58s6qRmML2gx1bn+sE+VXUhUfsGVRGXuG36MC1BKfZT0H2UFkbFn8Cdceni7KNij55Mth09HWwCvsKbIzOSmP/J1VxKT5hs4wAUo5cjKQjXMqbIvVMmlh5MYGsTv0h3E7cgih9/f8Mrb7lmaNAUuZYgpU8wFKIiZ6xsoYxGTsrO/hUsPDzFUCUqCSN9P2JqYnNFq/JE3XNlaVhwYy+bKKEcfLruVlF2hZzUDCSjJSYW9IduIwUBOY4rdiUkNYp5xJTFZe4cLoi/GaPZjJJTFrRh+QisQeoZJKuw5E51BGenhvL6mejyakLTvxdfMri+vZmKj64ihxGVGWejNuUU943OL+rgkY9+I5iE8C353aiFyaN28evTv6xm/tiQ4vrEmPIaZkzDJCURa3Pmgma8k4a1lGjnHKwkow0rH5Pon5vHqMbqPdImW9eWd17iutXgOeQh4CHgIeAh4CHgIXCUI0NlhdHIF5BfxCm1QYp09hkPjbqQD4+LV6cb7EecPceqS3BkbgCi0su0O5W/WqsPQebcVvS4r28o6kVBI+6WzUQDsB2ZBoMMXcAiD5pJR/H019Lr+RCWe2NHyvyGEAC2l6kbX4zyOse6hLeGQlVr66WwylJvVm2DVuOm8go9LIwZGn7FCCpWl3buQT2g5Tbt6cY3OwHTt7mMe3xDDoLTDfdCF0cFtttRmOL5Jixg6ohA2JnmCd/k9FVJaC+2/BxC9doEBkjVfw6qzvbftsiNLj3p2Go2NUUEcn5VCDAzHHiBqqauBvh8xWsw11A3IAtQOO/D3PepNaOKCf6+hXyndGJxnnsJnNjAEwFzBiGvtZvU6VK5SSuuYboTONBZxDBV0HmIFA3DrHALYbC8gdxkTwNsKgGac7GoTaEd0iMm3yYZZoLnL0QxS6vkw6CfXAZx/CgQoyPqAAmw+JdAuN+icPpyQdj4MHFqLmiB6ZnQG5GuuxITtBzhBsRtkM/p2SBlf1JYyJhoYevqnr1ww8mVrYf9D0T7E6odPE/hbRTzCymDYSha1FIhwUqYAoZbBesjEtXOyiaGstq2A2qEMQGwEEBGZYMCm5m5eGnvgR1CmL7B1iZ5B7MDSNh1wajOc+odkIKg/Z+4ogz908JyZPt9UGdgbkf7uRI9BBP+gg0nDbtaMBj79RjIxB22r6VYVIfDHIbYkJU2COEmHmGrFAWI+ZVKn2RbzpFU8LZenWorAvy8zcJYtVpaZXjGjjKiH21jyztO5nZaBtaqAXnYh1XKvWiu3AABHhE4dZ32JiCoPrufQPSL9I/34FMp6q5h65T0EPAQ8BDwEPAQ8BDwE9BGgj69h9vWQm4UechsaGlK1IqG1Bpg5fd4p/yl/KKSOIaBZ8QUJmr5rAaB+RcPJVTPM7w1YIgzE0IcKTD0NyywHP5nfu4QfPpm+TMt+X2C9mrBEChVGwH1OBGXCZpC1soS6OhP67KiMrZYJYCkAMZ0OBUXARGC/BvIsJSUhDfjbSYjmSzAaSxjvZ+ajrNF3zewgIlbHCyKJceLrqkH6ch0mHhmxgYGUeTSgQp6GHImpNMyPXeM+6Qs0MO59TiQxz0luMVXol6/nDUjN172i+kgvqzS3Z9Arb1y7IisW2PoXK/PNG5vufWoCUEQz19K506zTRBDkTdYkQN1l0CSKGNg9B/ka9H8J8mXCzWwsXOVCoVAKDMpY2WialKlA1IzyPaxlTYjjiwKJYR46xAW0mZvUWiCs1QAw5qpKM/6yyuAVwXyaUIgghzXxsNP/GboEt5pGGtCFBjBNuYhJACrWoGPv+2F8DcT09jxGLR2jlI8sUsgO/FgEOWtnq6GpvMwYZthCMDxfbuXt8s4jIM1dYaKDhN0iO4lxxRtMBFRgQ1AXhc7xDZilRdxmWw1IpW2EHZATJPj//dLWHhvVWDhD+/PNfrOYdks9amRD9HXqfsxUMJRjniwo2mcu/Qjq4XjTHPTQBfkKlwHBN9EiDvhCa415u17alEuVUfOcNMHuxqeeVtvD2V2QCxwB9tKqlfgsiL0bfse7BIv55XOxnprUjgBX0tiD33H8Tk8wUopkkCYNvb2915pUL6wYTdPhXzxJ2u8Jc0akYgIfwdLemK0kmK2somcgkTat6qbdwRytnbqxC4hnhVV7Xvk4EAAxVUbkgJjdcaj0brUDAXU5rdFD519ATinNykCiDy3tVjtsezoMEADglBnmmqHh3n8LTel7bH0UAQBew0nOXg87iQioK2qMtirSrPNuiW55pggBgE6745jPZTS9dk0K5mqjDOTQegLN8caVG2CvJoLUDDR1a/8X/K0PormmQDY2/wPTPhXkodiOXwAAAABJRU5ErkJggg==

`
Also for in JOSM.


>ask them if they can update the WMTS service to offer a few more zoom levels? 😄

next step.

**Comment by Klumbumbus** [comment]
Please before converting to base64 minimize the png filesize by e.g. this service: http://compresspng.com/

This makes the resulting base64 code in the end shorter

**Comment by AllroadsNL** [comment]
No, i did not.

Now, I did it once again and enable it. 

Filename:	
102 105 px wsh-logo-beeldmateriaal-nederlanddefwebsite.png
Filesize:	2.76 KB (- 16.46%)
Encoded:	3.68 KB
Width:	102 px
Height:	105 px


For use in  elements:
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGYAAABpCAYAAADIiVa3AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAACkZJREFUeNrtXQtwlMUdzwMTgkl4GIgMIOJrlIdQgYSHShUVx/FRh1HrKNMy1Bk7pVVndLRjbcpMoUDIg5wBAomSl+YuKVHUONNpxSQHJOGSu+SOvCQhF3xhC512KMgrX///m69OGr7d20u+b79dsv+Z39wld7ff7v72v//d//53NypqlMmhQ4cSDh48+CnglB2A53+iaVp0lJL/F6icPKgczS7A87NGY6VPcblcsZTPn7WZlAF4fWDUENLY2HgbFLri8OHDb0I3EWP0ndra2qlQKSdtJuaLQCAQNxrsxSQobA7gDLz/2u12J1G++4GdpOjElI2GbmstoHdQwR8jfRcIW203KQjQ6GeuWkKgcKlASPGQQrtI36+rq5sMn38lgLYMAP4I738BDeWFofB4PCkyd13LAYEhhT4NZN1K+c02EbQlDE4fOHBggpSkQKt6HgpwzqAlbqL8ZhF856LoxEAZnLLak5f0oebQAv29oaFhOuV3+yTQFizHr2Tsvn5LKdAbFFJWAS5LQMoAaPYC6TSF1i/jhJLy23oZtAVwBOzLGJlIeTZMS9sg+vCYUWM2SENKfX39EsjwWUqB/g2YRiHVLRExXfBahxquwy3kfAddJ5C57jAFKqXMc35sNFCQCaDx94lo7F1hMn4RKv9Oirb8RWZSwrmW7CLlRYaM11JIuR1wQXJiPhKKFN11cpLB3/RLCjFbJScFu7EXhCEFXfWQqWqGjH9Hcl3obv3vZSYFbWNTU9MM0Qz+fsjcxxR8AniN0g2m4ZJxmDREBpbvbbXsrESJEiVKlChRogRkenH3iiSH/4Okt/3VNCTm+T+8Eb5LSidld2cGSzqmweGvTt3dUb3EFawyC+muvuq0yuA9QhCTnN9eFPUnjxa1uZmOLc3atJKudKM0bnL1jI/N8p4Om4ZZgLxgnmcUdml3V/VrUKkmoe/yoqrgTbaTMtsViIvPae0OFXRrCxlbWrQxWb4TUwu+GmeUztS9XU+GTcMCzCvv1ZZVmkiMM/g3IbQl1DVtaR4IWwlQ6ePyj1aR0pmws30rV2LgWXE5rVoaVOZS07QlqKU7g2IslqUUdP4+1DUwVERqUec6Ujpj89o+40oM5HnKrg5tuandGJBc2bdSCGIS8gIfMVUoaBXJvtxS2p08Jtv7DXZ3/DSmRZtd2qPd++cT2nLoyhAmdGnfLgRbaTspt9R0x4/J9h1jsS+x27ynbivvNIxQnFbSOz86s/kyT9sSs82r3Vp8TJtT1hMi6H9Ic9K6qb6L8OqB18Yr4OprAsOfIYS2pJZ0zorO9J5j6cbic9uaowje1kl72tfbYfiH5hEambbYid0R0X60RMngMZ7yTveDrIWOd/grid2h42iZ7cSAzZmYf5Rqc0AzcqSYWCbuas9gtC9a0s6OPxgmAi0wbntbgwjEzCzqJs9pnH0Dy5zHl8pBTD609M1sFTq+oMtw99V1hR1JML/5mqvhN7I5mV5t/nvHKQOAvv6F+43nYMJJ3PbWQywtPTqz5XzKO8cMo/inwf/xc7u1JTHPD7aF1o0F90lBymRXIDGWpaWHRmS+724oD040nAcVdt1rhSGPyD2zyaNdX9BBd804jz8pBTEz9n4xJ3qr9xJLJcXmtAaiCDG90JU9Z6p9gbQSHX7tBrAX0wu7mHHnexTXDNgX0JgyeM3XsSOtMviEkMSk7Ol8htXwg3E/QHSA7mp/3WxicH6yYt+JkAawgjREpvjEfiaq4d/LSsw4R6CCOFTOD5SYSQwa8QVUI26KB/nMove/nCEcKeghRk8xKzFj8486iAOI3Da3acRgI9juh4rrN9UxaaAtHwupLbP29qQxeZR14x+3I/CWYUIuLTYmyxcwjRgw5GgvzHZMGhDzipDEpO7uzAwtjG1pDg/04hZ1Pk+aw8RkeU/+sHBlAuaW9YYcklYSs7Sif7FwpKDjMtkR+Hxstrd3bHYrE5L3dKUZpTX+3eMT4nPbWljTocPbe+12f+/iir4eGDVZhnRX0C3mRDNDi5kNcxjMHCvwNyR3zBJnf0IkadGAaVmNhQWea1SUhxIlSpQoUaLEHsENnnhyBeB3kQI3KJE2iDY2Nl6PB8YNJ13RAOV82ePhPGLDsx9HuO1tplG68Nldsu+zHISDpBMJrdKWBVCx50dAytn6+nrDkFH4/xwZTlRiPFju59xI0Te6Hh6htlzAreFG6ePZZLJvgh10XsEd3IiBB75i0ml4PzJKH3f16mdgapLvUG7ndriPfnDb9yZlfJnRM/CIQjx56SrQmCIupOD+e3iYz8SDCJ6gjPa+lFBDLuu2MQQox0O8RmHFJhfkVYLGXIPdgGSkfIu9CQ5c4P1cfOXSjdFO4RtBYXIojaBRMo0psWMiudqKY6ggzXJKQ6iSjBi+YUxQeSuNTnY1CZ9RiMmQqBs7w/V8GOgn58OD/2lhofykCxTgs3USacsRbufDwMPmcRgZnQTyJxI0dZVExGzjqSk9HLqAC3jLBalhAC7Z0C314/wjEpA8GKZrCg9SBlXEKtIkU7+9iLdv603h3PhQEYshc0ERjr5F24M2iLdvC+cgQpGClx1Apv5hQ/9cSWko+3kfw8t97SQMKQ/b6DRsIY1oIE8bORNTLBIpz9nsYj+Nh5gSiLmfMzFrbScEWylk5DeCTNCWkZaYLZzcXnEyOp7bKQIxMW63+x69Va6wC3jqOOkmImw88Hk6fsfqPDQ0NCxUURxKlChRokSJEmsFL1+D0dejIgMnuTU1NfGkWAMYOT1uY97mWeUDk+IGCRy+G+Vfv0XDzqiZ16wi5lNJVgI3UTwU+Tbl6SxpacIMYlolWXDykyJLsKuzK/bYSne+x8bKDuJ174C30CkJqIH/HSMtgqEtIazPjGO418wKbLaSGDtuV/XjzXUw8Eg2aP0J+oLcegzIYL3s2o4ADbB7j1hJzAbOBSqFfvm6CPKH/rr3By1WzSQtefO8zQ+e9S+S59ss1/4KjqTkjqAB3Q/4nDQI0HcZ1FlIxCnAGnj/FOBprDdL5zGBQCCOU2Rj7kjzqnuU7yaFNUE5fmIhMRV2LIg9ZbHal/MoBw4CrIpLIA08ZNaaWjToHBtZhgUNq9229X6MABnJ9jwCetDlw1n7J+G1jCYTs9FWvxnjza3My7GkXWEcGlm2mcQIsYIJGck0oTDnLB3jhxEM4h6u1ugRQU0Yc4yAvwuFuZtS358/3DuLcbfUagHKsHGYxDiEXg6ATD4WqZsDJ12An4qQfz2Mtj/SeGm8gVb4tRqMtofM7kAvKkPBfBi1IlL+hxGCVSvVYhpGrKPtgdfeIQ7Gi/p+yBd9Pt+1Amp9QoRO2l9LudqJla/vjVmJgNHKbJwDiZxn3B3MurYC5Zml1rT5ak4pAzE7VU1xFj2cNtzw+a9ATh6OynBFFDTtZlVzfOzkmghGZ/+x1KWv5ApyKhjJ2a1qi6PoETXhtiriqPMuVVv8BwLLafMyHF5rMlz2dpWSs16qDbCjzN5k693aD8BQLlJMAW/5L9sNeVGc9shRAAAAAElFTkSuQmCC`

**Comment by tyrasd** [comment]
ok, thanks. I've replaced the icon in 90d8cae.

**Comment by AllroadsNL** [comment]
NOW with first compress it. -48% And then on enable upload base64.

Filename:	
102 105 px wsh-logo-beeldmateriaal-compress.png
Filesize:	1.70 KB
Encoded:	2.27 KB
Width:	102 px
Height:	105 px
For use in  elements:
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGYAAABpCAMAAAD/V6aFAAABQVBMVEVHcEzFxcUIjtE3quLGxsYMlNMxseXFxcXFxcXGxsY3qeC82+c4qeA4quEcod3FxcXGxsbGxsbKysrHx8cGkdLGxsYPl9fExMTGxsbGxsbGxsYGjtDGxsYLlNXFxcXKysrGxsY3qeDFxcXGxsbFxcXGxsY3qeHGxsbIyMjGxsbGxsbFxcXFxcXFxcXGxsYBi883quHExMTGxsbGxsYgpdkYntoeqtXGxsYko93FxcXFxcUio97GxsYDjdAcn9rGxsbGxsbGxsYQmdjGxsYCjdAAis0IktM1qODGxsbHx8fGxsY3quHFxcUco93GxsbGxsbFxcUmotw3q+E4quE3quE3quACjtEKl9XGxsbFxcUZoNkBi883qeHGxsYAis44quEAic0AiM08rOIcnNk6q+IspN4Mk9QFj9EXmdclodzGxsbX17u1AAAAXnRSTlMA7d4ItK8KTHw//QHerC31nSgFHsszjQ5Bw23d6qMYFFmUZtVH78rkCTn4uIZUdvqAFKxPDUAEozao2iLQ5V39lLF/y+z+wd1he76y+hGNgC1uQO7BUNR6mYRR96TdoavfmwAABLhJREFUeF7s08Fqg0AQBuApCC0IBBtCYpBVbMQmNoF4CfGykV5aKKbXAn2B//0foOLspQF0xhQokO80/2l2WH66xnNx18vz6S+c0K+ha8TukQn62RWNFxzfeY2J0K96pLH2zSSf81hjwIHGevsG7nncYkhC45gDgNKdlWOA/Uo7MemsnwBkAYcGQtmcVJINWi8cZhZCR1JZWrSiKacSUkvSeEBnx2llIWQ/Vbegk8UcQ0i9asqTgJ05biF2Jrn1BJ2J0R6DKmzJGmSq371eWOgsSKK8+M4COrmoOimckHPwAR2PBPbRRQUaKKU0zK/hRHy72UDHTmmYqT1nx2tnhadz8ulfuLn5YazseRMEwjhuJDCIOhkXw8DiagchJkQGInZoHKxWk7Y5nkO09ft/gTb3Sjg4nt/4T7jf5XnhIlcR8SRzbUxaeO/XBFQCGxasd7QToLeyMBglvZZ4AUSw9VjyCcTCvTI1Z0TNciIAlydziwZ+ihZe+jUZVUekPNlbNPS3LEwQrXHVoblozdZas7KqmmU7rXstjm7N7sCSaW7TPO//yM4vOYiaJV9EADOfJUcgVoDK/ix9/NaQ5gQEQOzQh+hPOECTgdJkLPBnfRoQqzPa4DUBJZLImAD76ow9vEZP7yrhzVr11kxM2gTr0HfXgxa1t12jVucDr5mqu8MlZkkKLZbHrYao2eg7DEOkSh8Ke55c2zTPskZRI0VOgNYEMulqukl1SlAWb6s1884/GjyKDt4GKDY5UVxZEl9MjXhjTKojTjOnIKGpfNPAQNTMBLegzn4xVPBPDrNhk8XwddzOGbeg/trT+DxyPAOni/ivXfNbbRSIwvgpLCQiYIyIRmAT1hS1RCEJICmCgjdtKKmXe+ML+P4PsCmzG6Y96zczFO/yu3WGzxnPmTl/JCV37gTFXKb4m6e9zk2JQPWBp5cirfMHY1YoJOi+5MqOkHFrY5kXoLL8WsV4c4XMk6lK7QKZiI326QPPMZWJwafx+UtnojL8aCqzAFZWDYyjeJIYbdgVUIkuB04hvllsoJL4bueO79kclOFbA5mSEHkN5hwMZI4ECP9vs2fx9F1fxfGQX47YUiyc+UVfprWBSjIw5OLTVl/mAlT6QYYfA12NDDhZSLhIZRThAOuHAfBKOviJss5rx98ubGfwTQ+gZ2PSFdriY7EShrMDiyn12hmQx71wK3i1qLCjQUWmKqc6P9UyVmhhwrUYmI0NDH0C3LnjzTTZCicPjnhYh+NLNZbofyiim4IYZi2fnU733hm5ACrT0A5fbSti6AQryWm++9HXUhCRPquXzDnABWwCupJ20VlcBsq4Y0YM5aRyTzfC07+uUlcrD3KOpR01hGexI/ZI1/Nhk+cWjbBsoYqMbYm77TjWSkcpU24cnKYJCDMNl7NKaZR3YO8oA+T0Hu6EcnbqLi3D8YmDTyg2Qz3raUYQ7/NynLZtFzYpKT7vW50TgAdSDWkye5Z9bEMq1rKxvfmkS9DcwsEqIzUROC4BNrmXjxOyjn8FpEHagn9PMEEXht2S9NiyvGwaSmYAEyD9N3Zumma6BdkbyXH2NB2nm8xvmpB9L1WOJiRzWHI+CRHLbafh0l+p1Hb2B2WwRgDiX0fTAAAAAElFTkSuQmCC`

**Comment by Klumbumbus** [comment]
OK, thanks. Icon replaced. Good to know that the optimization is not so good at base64-image.de

**Comment by Klumbumbus** [comment]
> Also for in JOSM.
Updated in JOSM too.

**Comment by AllroadsNL** [comment]
Thanks!

**Comment by AllroadsNL** [comment]
[Request capabilities](https://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wmts?request=GetCapabilities&service=WMTS)

Take

<Layer>
<ows:Title>Luchtfoto Actueel Ortho 25cm RGB</ows:Title>
<ows:Abstract/>
<ows:WGS84BoundingBox>

Then we do not have to change every year the layer link name, the year.

Pdok changes Actueel (actual) tiles, make the 2016 to a 2017 and now to 2018 tilelayer set !!


I see on other sites that the layers is also not working, this is because these sites have also a different layername with not RGB in it, this is wrong in our code.

Conclusion: PDOK also changed names of 2016 and 2017 layers. With the introduction of 2018.

**Pull request merged**
