### PR TITLE
Goiania base map

### PR DESCRIPTION
**Pull request by tsmock**
* https://wiki.openstreetmap.org/wiki/Dados_Abertos_-_Prefeituras_do_Brasil
	  indicates that is is under a ODBL compatible license, but I
	  cannot find the information required (I'm not a native spanish
	  speaker)

Signed-off-by: Taylor Smock <taylor.smock@kaartgroup.com>

### CODE REVIEW

**Comment by naoliv** [comment]
https://wiki.openstreetmap.org/wiki/Dados_Abertos_-_Prefeituras_do_Brasil had an incorrect/incomplete statement (saying that everything listed there have data compatible with ODbL)

I have included a warning on the page, asked the Brazilian community to pay more attention about this and also asked to check the license/permission of the listed sites.

**Comment by naoliv** [comment]
This is not permissive per http://portalmapa.goiania.go.gov.br/helpsiggo/HelpSIGGO/_termo_de_compromisso.htm

We will have to ask for permission it seems.

**Comment by grischard** [comment]
Closing for now then. Sorry @taylorsmock and thank you.

**Comment by tsmock** [comment]
I'm being told that http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm "guarantees access to information relating to public data", but I'll see if I can get clarification on (at least some of) the PR's I've done.

**Comment by naoliv** [comment]
This law regulates access to information, but does not say that all data is free and of unrestricted use.

Through this law we can request access to the data, which may or may not be accepted by the government agency.

**Pull request closed without merging**
