### PR TITLE
remove best marker from broken layer see #845 #872

### PR DESCRIPTION
**Pull request by matkoniecz**
I am not sure what exactly went wrong but for long time this layer is showing blank white instead of aerial tiles

I am not making PR removing it as maybe it is fixable, but it is no longer the best imagery

### CODE REVIEW

**Comment by matkoniecz** [comment]
Failure is 

> ERROR:root:Error in sources/europe/pl/Geoportal2Orthophotomap(aerialimage).geojson : sources/europe/pl/Geoportal2Orthophotomap(aerialimage).geojson has no privacy_policy_url. Adding privacy policies to sources is important to comply with legal requirements in certain countries.

and therefore can be ignored as it is minor and not introduced in this PR anyway

**Comment by grischard** [comment]
What about just nuking it if it's broken?

**Comment by matkoniecz** [comment]
It sometimes works, but extremely rarely. Maybe it will change?

In JOSM I simply removed it as there is working wmts - that is sadly unsupported by iD and Vespucci

I intended this is band aid to unbreak iD that is now showing white as an aerial

**Review by andrewharvey — APPROVED** [review]

**Comment by matkoniecz** [comment]
I posted at https://forum.openstreetmap.org/viewtopic.php?pid=797364#p797364 and https://t.me/OpenStreetMapPolska/1916 to make Polish OSM Community informed about the situation

**Comment by maro-21** [comment]
It's not broken, it works. I map almost every day and haven't seen any blank tiles. Maybe it's only in the region where you edit.
Could you undo this change?

**Comment by andrewharvey** [comment]
@matkoniecz @maro-21 if you two could come to some agreement if this should be best or not, I think that would help resolve the outstanding issue, then it well need to be another PR to revert the change if that's decided upon.

**Pull request merged**
