### PR TITLE
Update licence url

### PR DESCRIPTION
**Pull request by simonpoole**
The old url stopped working, via @don-vip

### CODE REVIEW

**Comment by don-vip** [comment]
Change applied on JOSM for [all three entries](https://josm.openstreetmap.de/wiki/Maps/Switzerland?action=diff&version=104) sharing this link.

**Comment by Klumbumbus** [comment]
fixed two links: https://josm.openstreetmap.de/wiki/Maps/Switzerland?action=diff&version=105

**Comment by Klumbumbus** [comment]
one more change/addition: https://josm.openstreetmap.de/wiki/Maps/Switzerland?action=diff&version=106

**Comment by don-vip** [comment]
> 
> 
> one more change/addition: https://josm.openstreetmap.de/wiki/Maps/Switzerland?action=diff&version=106

Don't forget this one :) https://josm.openstreetmap.de/wiki/Maps/Switzerland?action=diff&version=107

**Comment by Klumbumbus** [comment]
Hah, nice trap by the zürich IT guys using `-` for 2011 and `_` for 2013 ;)

**Pull request merged**
