### PR TITLE
Update NC Latest Orthoimagery

### PR DESCRIPTION
**Pull request by rivermont**
* Tagged as 'best' imagery for NC. It's nearly the highest quality in most areas and is ortho-rectified and thus has almost negligible offset throughout.
* More imagery was taken in 2015 and 2017, so added that to the layer description.

### CODE REVIEW

**Comment by grischard** [comment]
Thanks!

https://nconemap.maps.arcgis.com/apps/MapSeries/index.html?appid=c503fa08ae9744b3b3c307457a231db2 says that some of the pictures are from 2018 too.

Would you have a license that allows us to use these while we're at it?

**Comment by grischard** [comment]
https://nconemap.gov/NCOneMapBlog/tabid/679/EntryId/1061/2017-Piedmont-Imagery-Now-Available.aspx also suggests that the `Orthoimagery_Latest_cached` service would be faster for our usage.

**Comment by rivermont** [comment]
The imagery has already been in the project for a while now so I assumed we already had one, but I'll find it.

**Comment by grischard** [comment]
Unfortunately not uncommon, see #439 🙈

**Comment by rivermont** [comment]
I am unable to find a license on their web portal or ArcGIS site.  
I emailed NC OneMap through the form on their site explaining the need for a license and will hopefully hear back soon.

**Comment by grischard** [comment]
Thank you!

**Comment by rivermont** [comment]
I haven't received any response after the mentioned email, but I found the license listed on NCOnemap's ArcGIS portal that serves this imagery:

[Latest Orthoimagery (Cached)](https://www.nconemap.gov/datasets/latest-orthoimagery-cached)
> Geospatial data provided from NC OneMap are free to download and use by anyone without restriction. By sharing their geospatial content, all provider organizations understand, and agree with, the free and unrestricted use policy of NC OneMap. Written release agreements to authorize use of data are not required and will not be issued. While every effort has been made by data providers to ensure these data are accurate and reliable, there is no assumption of liability for any damages caused by inaccuracies in the data or services. There is no warranty, express or implied, nor does the fact of distribution constitute such a warranty.

"free to download and use by anyone without restriction" seems pretty compatible to me.

**Comment by grischard** [comment]
Aha! Yes, that's excellent.

Let's also add https://www.nconemap.gov/pages/terms as a privacy_policy_url and then we're good to sail I think.

**Comment by rivermont** [comment]
Looks like I forgot about this for a while 😬 .
NC Ortho have also changed their website so I'm now finding the new license location.

**Comment by rivermont** [comment]
Closing since a different pull was created and merged since this was opened.

**Pull request closed without merging**
