### PR TITLE
KYAPED 2020

### LINKED ISSUE #1209: Kentucky Aerial Photography and Elevation Data Program 2020
## URL of the imagery
https://kyraster.ky.gov/arcgis/rest/services/ImageServices/Ky_KYAPED_2020_6IN/ImageServer/
https://kygeoportal.ky.gov/geoportal/catalog/search/resource/details.page?uuid=%7BBCAF6E4F-D34F-4636-8B6B-8DD9B3134DD8%7D

## Two letter country code
US

## Desired layer name
KyFromAbove 2020 6in

## License
All KYAPED imagery is [in the public domain](https://kygeonet.ky.gov/kyfromabove/pdfs/KyFromAboveDistributionPolicy.pdf).

## Is the license compatible with OSM?
Yes

## Attribution (text, URL, required?)
[KyFromAbove](https://kyfromabove.ky.gov/), Commonwealth of Kentucky
(not required)

## Privacy policy (URL)
https://kentucky.gov/policies/

## Icon
None

## Bounding polygon
Here’s an [Overpass query](http://overpass-turbo.eu/s/19IQ) based on the provided list of counties. The server is down at the moment, so I can’t verify the exact bounds. Most likely the geometry can be simplified quite a bit.

/ref #612

### PR DESCRIPTION
**Pull request by 1ec5**
Added the Kentucky Aerial Photography and Elevation Data Program’s layer of 6-inch orthoimagery from 2020 with a partially hand-drawn geometry based on where the imagery seems to be available.

Fixes #1209.

### CODE REVIEW

**Comment by 1ec5** [comment]
Also [added to the JOSM wiki](https://josm.openstreetmap.de/wiki/Maps/USA%20States?action=diff&version=273).

**Comment by rbuffat** [comment]
@1ec5 Could state some more details about the license terms of this imagery? I tried to access https://kygeonet.ky.gov/kyfromabove/pdfs/KyFromAboveDistributionPolicy.pdf, but it did timeout several times.

**Comment by 1ec5** [comment]
Perhaps there was a bit of downtime when you checked. (Hopefully they aren’t blocking non-U.S. connections like a lot of U.S. state government sites tend to do.) Here’s a copy of the PDF, which also applies to the existing KYAPED layers added in #821:

[KyFromAboveDistributionPolicy.pdf](https://github.com/osmlab/editor-layer-index/files/6988381/KyFromAboveDistributionPolicy.pdf)

Here’s the relevant passage:

> Data acquired during the KYAPED effort will be made available in the public domain.

**Comment by rbuffat** [comment]
I guess it's probably geo blocked then.

**Pull request merged**
