### PR TITLE
Latvia, orthophoto 2008: add new map

### PR DESCRIPTION
**Pull request by soshial**

### CODE REVIEW

**Comment by rbuffat** [comment]
Thanks @soshial !

**Comment by soshial** [comment]
Recently, Latvian cadastre map has been published under open data lisense. This WMS service has a lot of layers, hence it's not really possible/convenient to add only one layer. @[rbuffat](https://github.com/rbuffat), may I create a layer with [GetCapabilities URL](https://lvmgeoserver.lvm.lv/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities&layer=publicwfs%3AKadastra_karte)?

**Comment by rbuffat** [comment]
Theoretically yes, but then only a few osm editors will be able to use the data. The WMS GetMap request allows to include multiple layers using `LAYERS=1,2,3,4,5,6&STYLES=,,,,,`.  Maybe this is an option?

**Comment by soshial** [comment]
Thanks, I managed to do it in this PR: https://github.com/osmlab/editor-layer-index/pull/1449

**Pull request merged**
