### PR TITLE
Reinstate NZ LINZ layers via a caching proxy server

### PR DESCRIPTION
**Pull request by andrewharvey**
This reverts https://github.com/osmlab/editor-layer-index/commit/748c386277d9188005b758d9f123f744c4820693 by using a caching proxy server, which has been setup by a community member, details at https://maptimeoceania.slack.com/archives/C42BW30LB/p1561800703035300?thread_ts=1556178915.002600&cid=C42BW30LB

We never heard back from LINZ if a caching proxy server would be okay, or we need to host the imagery ourselfs, so I think let's try this and then be reactive if it becomes a problem in the future.

I think in the future we could try to run this on OSMF or a local chapter's infrastructure, but let's roll this out first regardless.

see background in #602

### CODE REVIEW

**Comment by andrewharvey** [comment]
@grischard there were a few other changes in https://github.com/osmlab/editor-layer-index/commit/748c386277d9188005b758d9f123f744c4820693 seemingly unrelated to dropping the NZ imagery, since I used git revert, those changes are reverted here, could you let me know if I should drop these parts out of this PR?

**Comment by andrewharvey** [comment]
Let's hold off merging this for now, I'm getting 502 Bad Gateway responses.

**Comment by Cameron-D** [comment]
Hey, I've made a few changes to my server configuration which should mean no more 502's.
Thanks for the PR too, I was unsure whether it'd be best to revert or open a new commit (And a long time since I've touched GH/git in general).

**Comment by grischard** [comment]
Oh dear, it looks like I typed `git commit -a` and accidentally caught a few local changes.

Fantastic otherwise! Happy to merge when you're happy to merge.

**Comment by andrewharvey** [comment]
> Oh dear, it looks like I typed git commit -a and accidentally caught a few local changes.
>
> Fantastic otherwise! Happy to merge when you're happy to merge.

Ok let's merge this @grischard

**Pull request merged**
