### PR TITLE
Added Cyclosm tiles

### LINKED ISSUE #1181: Add CyclOSM layer
Hi everyone,
The requested feature is in the title.

Excuse me if this issue report is not good enough, this is my first time.

Thanks for your work.
Lysios

## URL of the imagery
I think that's the one > `https://{s}.tile-cyclosm.openstreetmap.fr/[cyclosm|cyclosm-lite]/{z}/{x}/{y}.png`

## Two letter country code
world

## Desired layer name
CyclOSM

## Licenses
[https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/LICENSE.md](https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/LICENSE.md)

## Is the license compatible with OSM?
(required)

## Attribution (text, URL, required?)
I do not know

## Privacy policy (URL)
I do not know

## Icon
[https://raw.githubusercontent.com/cyclosm/cyclosm-website/master/images/logo.png](https://raw.githubusercontent.com/cyclosm/cyclosm-website/master/images/logo.png)

## Bounding polygon
(if possible, provide a bounding polygon where the imagery is valid, e.g. as a GeoJSON or OSM file.)<br/>
See FAQ at https://github.com/osmlab/editor-layer-index/blob/gh-pages/FAQ.md#how-can-i-draw-a-bounding-polygon) for information about how to draw a bounding polygon.

### PR DESCRIPTION
**Pull request by PanierAvide**
~~See https://github.com/osmlab/editor-layer-index/pull/1226~~

closes #1181

### CODE REVIEW

**Comment by Asteliks** [comment]
@PanierAvide This branch has conflicts that must be resolved

**Comment by PanierAvide** [comment]
Conflict is now solved

**Comment by Asteliks** [comment]
@andrewharvey @rbuffat could you take a look at this?

**Review by andrewharvey — APPROVED** [review]
Looks good to me, thanks.

Though I think en.yaml yet's updated automatically from Transifex, so probably doesn't need to be manually set, though probably doesn't hurt.

**Pull request merged**
