### PR TITLE
Updated URLs to newer (?) ELI version

### PR DESCRIPTION
**Pull request by grischard**
See https://github.com/osmlab/editor-layer-index/pull/403#issuecomment-366525927

### CODE REVIEW

**Comment by Klumbumbus** [comment]
There is a typo in both new URLs (missing `/` after ows) and the URL encoding is not necessary too.

**Comment by tyrasd** [comment]
> typo […] missing `/` after ows

Not sure about that. I believe it doesn't matter, but https://geoservices-urbis.irisnet.be/geoserver/web/ itself advertises the WMS without a slash after `ows`:

```
https://geoservices-urbis.irisnet.be/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities
```

**Comment by grischard** [comment]
I've removed the / in JOSM in https://josm.openstreetmap.de/wiki/Maps/Belgium?action=diff&version=108

**Comment by Klumbumbus** [comment]
Ok. I tested the version without / and it didn't work. Obviously I made a mistake at my test. Works now for me too.

**Pull request merged**
