### PR TITLE
Sweden: Fix licence_url's and add i18n for some sources

### PR DESCRIPTION
**Pull request by magol**

### CODE REVIEW

**Comment by NKAmapper** [comment]
Thank you for updating the URLs.
You may want to add CC0 also for the Economic maps, including in the attribution text.

**Comment by magol** [comment]
@NKAmapper 
Thank you to notified me about that. I have fixed it now.

**Comment by magol** [comment]
I also notice that the file https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/fi/Nordicsnowmobileoverlay.geojson is used in Sweden to, even if it is marked for use in only Finland. So I added `i18n `to it too.

It is little problematic when a source is used across several countries, it was a bit difficult to find this file. It should be a text file (or something) in the folder for each country that lists all sources that concern the country, at least those sources that are not in the country's own folder.

**Comment by grischard** [comment]
If a file is used in more than one country, I'd just put it in `europe` and remove the `"country_code": "FI",` in the json.

**Comment by magol** [comment]
@grischard 
The folder `Europe` may not be the best place as it does not cover the whole of Europe, but it is significantly better than the `fi` folder. So I've moved it now.

**Comment by grischard** [comment]
Looks perfect! The folders aren't a strict hierarchy, just to help the maintainers and contributors find things.

**Pull request merged**
