### PR TITLE
Scripts require Python 2

### PR DESCRIPTION
**Pull request by simon04**
This allows running `make` on Arch Linux.

### CODE REVIEW

**Comment by iandees** [comment]
I'd rather see us fix the code so that it runs on both python2 and python3.

Can you detail what problems you had running it on python3?

**Comment by simon04** [comment]
```
$ python3 scripts/check.py 
  File "scripts/check.py", line 11
    print file
             ^
SyntaxError: Missing parentheses in call to 'print'
```

```
$ python3 scripts/check.py
Traceback (most recent call last):
  File "scripts/check.py", line 4, in <module>
    schema = json.load(open('schema.json', 'rb'))
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

…

See my PR #202.

**Comment by bhousel** [comment]
These issues are exactly why we should move the project to node.js.  see #168 
I don't have time to deal with python dependency hell and version mismatches.

**Comment by iandees** [comment]
@bhousel good thing you don't have to! Each language has its own dependency hell and version mismatches.

**Comment by bhousel** [comment]
Sorry for my frustration before, we should just merge these improvements..

**Pull request merged**
