### PR TITLE
Add "Geoportal 2: Shaded relief (WMS)"

### PR DESCRIPTION
**Pull request by Zaczero**
image

Layer information (in Polish): https://www.geoportal.gov.pl/dane/numeryczny-model-terenu

**I did:**
* test both EPSG:3857, EPSG:4326 in available_projections

**I did not:**
* run additional checks for validity except for manually importing the configuration to iD

### CODE REVIEW

**Comment by rbuffat** [comment]
@Asteliks or @matkoniecz if possible, could you have a look at this?

**Comment by matkoniecz** [comment]
@rbuffat It is a very useful layer and like other geoportal.gov.pl products is effectively PD-licensed

**Comment by rbuffat** [comment]
Thanks @Zaczero and @matkoniecz !

**Comment by matkoniecz** [comment]
@Zaczero 

Maybe

> Geoportal 2: Ukształtowanie terenu (WMS)

or

> Geoportal 2: Ukształtowanie terenu

would be better than

> Geoportal 2: Cieniowanie (WMS)


("terrain elevation" vs "shading")

**Comment by Zaczero** [comment]
@matkoniecz Sure, the "Ukształtowanie terenu" name is more meaningful ➡️ https://github.com/osmlab/editor-layer-index/pull/1724

**Pull request merged**
