### PR TITLE
updating imagico.de OSM images for mapping

### PR DESCRIPTION
**Pull request by imagico**
This is a simple update of the images in one single layer.  I also created another branch with the individual images as separate layers:

https://github.com/imagico/editor-imagery-index/tree/osmim-individual

Not sure which is the better option.

### CODE REVIEW

**Comment by tyrasd** [comment]
I'd actually prefer to merge it as multiple layers, given that there are now even more overlapping layers (see also https://github.com/osmlab/editor-layer-index/pull/131#issuecomment-170330460). Having it as single layers would even open up the option to set the `best` flag for some of them (if and where applicable).

@bhousel @pnorman What do you think?

**Comment by bhousel** [comment]
I think multiple layers probably makes more sense too..  I don't know much about this source though.. Is `max_zoom: 15` right?  That doesn't seem like very useful imagery for tracing.

**Comment by imagico** [comment]
Yes, max_zoom 15 is correct.

Regarding usefulness - most of the imagery is the most recent available in this repository and significant parts are also the highest resolution for the respective areas.  My primary motivation for having this here is because i keep seeing mappers mapping from other older and less accurate images in these areas which seems a fairly wasted effort.

Note the individual images would add quite a lot of layers (about 40).

**Comment by imagico** [comment]
Closing in favor of #164.

**Pull request closed without merging**
