### PR TITLE
adding OSMIM as individual layers

### PR DESCRIPTION
**Pull request by imagico**
replaces #163.

As individual layers.

Also added best flags to where it obviously fits (Northern Greenland, Alaska, Antarctic and some Subantarctic islands)

### CODE REVIEW

**Comment by bhousel** [comment]
I did a quick test of Bing vs imagico on the Alaskan source, and I don't think imagico should be marked `best` here.   Can you please double check all of the areas where you're making the `best` claim?   

bing_v_imagico

**Comment by imagico** [comment]
I am sorry but no, since there is no comprehensive and up-to-date info on the variable quality sources like Bing which quality level is available at what location it is impossible to check this reliably within a reasonable time frame.  Also it can easily change any day.  I added 'best' for images where i know from looking at a representative selection of points in the image they are newest and highest quality (resolution, seasonality, cloud freeness etc.) compared to other sources i know of.  This applies to the Alaska area for a huge percentage.  You can of course be very picky and allow 'best' only for sources that provide best quality by all measures for 100 percent of the coverage area but for a significant portion of the sources marked as best right now there will likely be smaller parts (especially due to clouds) where this does not apply.

Ideally having several objective quality measures (like age and ground resolution) would be better than a binary measure like 'best' - see #130.

**Comment by bhousel** [comment]
Please remove the `best` flag from any sources that you don't have time to check.  

Our hope for this `best` flag is that local contributors can use it to mark imagery that they know to be better than Bing/Mapbox.  For example, "[Kanton Zürich 2015 10cm](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/ch/KantonZuerich10cm-2015-TMS.json#L10)" is marked "best" because people from Switzerland say so, not because of the imagery's age and resolution.  Tomorrow Bing may update their imagery and then "Kanton Zürich 2015 10cm" will no longer be the best source there, and ideally somebody from the Swiss community will notice this and open an issue to remove the flag.

**Comment by imagico** [comment]
OK - removed.

I only added it in the first place since @tyrasd suggested it.  As previously indicated i consider the 'best' flag unsuited for what it is used for.

**Comment by bhousel** [comment]
Thanks, @imagico

**Pull request merged**
