### PR TITLE
Add orthophotos for Kalmar municipality

### PR DESCRIPTION
**Pull request by NKAmapper**
Three versions needed to cover the area.
Permission included as a pdf.

### CODE REVIEW

**Comment by grischard** [comment]
Thank you!

**Comment by rbuffat** [comment]
@NKAmapper just FYI, the following sources seem not to be offered anymore by the [ArcGIS server](https://kartportal.kalmar.se/arcgisserver/services/Ortofoto) for 19 days:
* europe / se / Kalmar North Orthophoto 2014
* europe / se / Kalmar South Orthophoto 2016
* europe / se / Kalmar Urban Orthophoto 2018

**Comment by NKAmapper** [comment]
The URL was changed, it seems. The new URL is: https://karta.kalmar.se/ims/services/Ortofoto/Kalmar_2018/ImageServer/WMSServer?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox} (and similar for 2014, 2016).

I have updated JOSM, however there are reprojection problems.

**Comment by rbuffat** [comment]
@NKAmapper I created a PR to update the sources and add the 2020 imagery: https://github.com/osmlab/editor-layer-index/pull/1005

The accuracy seems fine, at least with EPSG:3857 (not advertised by the server, but seems to work)
kalmar_test

**Pull request merged**
