### PR TITLE
added the current layer for Poznan (PL)

### PR DESCRIPTION
**Pull request by Asteliks**
This pull request solves the [Poznan new map](https://github.com/osmlab/editor-layer-index/issues/876) issue

### CODE REVIEW

**Comment by Asteliks** [comment]
On my side ready for merge, sorry for the commits during the request

**Comment by Asteliks** [comment]
thanks

**Comment by maro-21** [comment]
Write please either in English or in Polish... "Poznań: Orthophotomap Bieżąca (aerial image)" isn't a good name. The name should be in English and you should add `"i18n": true"` so it can be translatable. Thank you.

"Bieżąca" does't say much - why not just add a year when the photos were taken?

**Comment by Asteliks** [comment]
> Write please either in English or in Polish... "Poznań: Orthophotomap Bieżąca (aerial image)" isn't a good name. The name should be in English and you should add `"i18n": true"` so it can be translatable. Thank you.

Naming was coordinated with the local authorities responsible for the creation of the source, what is more there is no explicit text in the documentation saying that the name must be in English [source](https://github.com/osmlab/editor-layer-index/blob/gh-pages/schema.json). That is why we have several sources not named in English [source](https://osmlab.github.io/editor-layer-index/).

> "Bieżąca" does't say much - why not just add a year when the photos were taken?

There is no year as this source will always present the latest available orthophoto map

**Pull request merged**
