### PR TITLE
Update SouthAfricaCDNGIAerial.geojson URL

### PR DESCRIPTION
**Pull request by Firefishy**
Update URL to match current preferred version.

### CODE REVIEW

**Comment by Manu1400** [comment]
## i.e.
* a title: https://aerial.openstreetmap.org.za/layer/ngi-aerial/7/69/74.jpg
* map: https://aerial.openstreetmap.org.za/

**Comment by Manu1400** [comment]
@Firefishy please keep `{switch:a,b,c}` in the URL

**Comment by grischard** [comment]
@Manu1400 http 2 makes this an anti-pattern. We recommend against it on tile.openstreetmap.org too.

**Comment by Manu1400** [comment]
> @Manu1400 http 2 makes this an anti-pattern. We recommend against it on tile.openstreetmap.org too.

## on tile.openstreetmap.org
"Now that tile.openstreetmap.org supports HTTP/2 + HTTP/3 the old (a|b|c).tile.openstreetmap.org is no longer"
https://github.com/Leaflet/Leaflet/pull/8418

**Comment by Firefishy** [comment]
> @Firefishy please keep `{switch:a,b,c}` in the URL

Since this targets primarily clients which use HTTP/2, my preference as the person who runs the service `aerial.openstreetmap.org.za` service is to no longer support the old `{switch:a,b,c}.` HTTP/1.1 hack which was used increase max browser connections. HTTP/2 multiplexing makes the hack redundant.

**Pull request merged**
