### PR TITLE
[Arenda,PH] Update TMS and extent based on newly processed imagery

### PR DESCRIPTION
**Pull request by maning**
We processed another batsh of drone images.  This covers the whole AOI with updated OAM TMS.

### CODE REVIEW

**Comment by grischard** [comment]
Can you please make sure your source json files are formatted in a human-readable way?

**Comment by grischard** [comment]
Sorry @maning, I've reverted this:

- There's no license linked
- There's no privacy policy
- The json files aren't formatted properly

I understand and appreciate your eagerness to improve the index, but please let the maintainers review and help first :)

**Comment by maning** [comment]
@grischard Thanks for reviewing, but this was just an update of a previous data which passed all automated checks.  

I agree that I should have reformatted it in human-readable form but all other data remain the same as before except for polygon and new URL.  If this PR does not comply with the agreed standards it should have at least failed the automated tests.

**Comment by grischard** [comment]
That's why we have maintainers :). I see that you also merged your previous PR yourself.

We'd love improvements to our automated checks. Some legacy sources don't have licenses or privacy policies either, so good tests would require a bit of travis-fu to only test new files.

**Comment by maning** [comment]
Understood, looking forward to the [updated guides](https://github.com/osmlab/editor-layer-index/blob/gh-pages/CONTRIBUTING.md) before I do another PR.

**Pull request merged**
