### PR TITLE
Add Orthophoto 2019 (5cm) for CH/Geneva

### PR DESCRIPTION
**Pull request by alkino**
I only replace 2016 by 2019, I don't know how this file is generated.
Check this file twice before merging.

### CODE REVIEW

**Comment by rbuffat** [comment]
I would not replace a source that is still working, but rather create a new one. Old imagery might still be useful, e.g. to see why a feature was created in the past.

To create parameters for a WMS layer you can use the following tool: https://mybinder.org/v2/gh/rbuffat/eli-helper/master?urlpath=apps%2F/create_wms_template_appmode.ipynb In this case, you would need to use `https://ge.ch/sitgags2/services/RASTER/ORTHOPHOTOS_2019/MapServer/WMSServer?` as URL. 

To check if the geometry corresponds to the wms layer, you can use e.g. [QGIS](qgis.org). You can drag and drop the geojson you created to QGIS and add the WMS layer with: Layer -> Add Layer -> Add WMS/WMTS Layer. You first have to add the WMS server using New (You can use the url from above). Then you can connect the server and select the WMS layer and Add it to the map. 

Orthophotos are typically processed to match the ground (You can find some documentation of this process in French [here in Chapter 3](https://www.swisstopo.admin.ch/content/swisstopo-internet/fr/home/products/images/ortho/swissimage10/_jcr_content/contentPar/tabs_copy/items/60_1569482292365/tabPar/downloadlist/downloadItems/67_1588752711524.download/Produktinfo_SWISSIMAGE10cm_FR_bf.pdf) ). Typically, a dataset for a specific region (e.g. a Canton), is only required/tested to be accurate for this region. However, the dataset can span a greater area. For this area, the quality might not be the same. Thus, to be safe, it might be better to just include the boundaries of the region.

**Comment by alkino** [comment]
I have make a fix.
I've try the two steps:
* parameters for WMS
* QGIS

For QGIS I have not an idea if it's good or no, there is yellow square and layer...

**Comment by rbuffat** [comment]
If you right-click on the geojson layer -> properties you can adjust the transparency of the layer. The geometry is a rough approximation of Geneva, but it should be fine for this source.

If you feel that this new source is the best for the region, you can change the "best" property to true and set the property to false for the source that previously had best = true.

**Comment by rbuffat** [comment]
The source is marked with "Accessible for consultation and extraction for free use (Open Data)" here: https://ge.ch/sitg/sitg_catalog/data_details/f498b260-5381-4912-b2e7-906a91902e3b/xhtml_raw

**Comment by alkino** [comment]
So is it good or no? I've search for a better geojson area for geneva canton (after using transparency in QGIS) but cannot find it in open data of SITG, maybe something is available openly somewhere else?

**Comment by rbuffat** [comment]
Looks good from my side. Merci!

**Comment by alkino** [comment]
What is the next step to have this merged?

**Comment by andrewharvey** [comment]
> What is the next step to have this merged?

@grischard do you have permissions to allow @rbuffat to merge PRs? Doesn't looks like I can make that change.

**Pull request merged**
