### PR TITLE
Fixed Brazil-Londrina

### PR DESCRIPTION
**Pull request by matheusgomesms**
Updated URLs (as discussed in PR #1233) and added privacy policy.

### CODE REVIEW

**Comment by rbuffat** [comment]
I did not find any license information on https://geo.londrina.pr.gov.br
I found this metadata page, but there also seems to be no license information: https://geo.londrina.pr.gov.br/portal/home/item.html?id=050f1b9b21304744b270241f502be8a6

**Comment by matheusgomesms** [comment]
Hi René,

I'm not sure if they have anywhere explicit information about license (CC, ODbL etc.), but on the [1073/2013 Decree Law](http://www2.londrina.pr.gov.br/jornaloficial/images/stories/jornalOficial/jornal_2278_assinado.pdf) that created SIGLON (Londrina GIS), it is stated on Article 3, item II:

"to ensure the transparency of government actions, in order to allow **public access** to all information that is not of restricted use, in accordance with the relevant legislation." (_garantir a transparência das ações de governo, de forma a permitir o acesso público a todas as informações que não sejam de uso restrito, em conformidade com a legislação pertinente._)

Is this enough or should we ask for explicit permission?

**Comment by willemarcel** [comment]
@matheusgomesms It would be good to have a confirmation of the permission to use in OpenStreetMap. I've emailed them asking it.

There is a more recent imagery: https://geo.londrina.pr.gov.br/portal/home/item.html?id=553747b7f8bc48a99871a48ea7f1d928

**Comment by matheusgomesms** [comment]
@willemarcel Nice! This is a very good imagery!

I still couldn't make it work neither on JOSM or iD. Would you have the correctly URL to be inserted on these editors? I'm trying to use this one:

https://geo.londrina.pr.gov.br/server/rest/services/Imagens/OrtofotoInfraero2020/MapServer/WMTS/tile/1.0.0/Imagens_OrtofotoInfraero2020/default/GoogleMapsCompatible/{zoom}/{y}/{x}

**Comment by willemarcel** [comment]
@matheusgomesms i updated the URL

**Comment by matheusgomesms** [comment]
Finally I got an answer from them. The last orthophotos comes from Infraero, so they cannot share it outside their GIS, unfortunately. Other data was made available, at least.

The other most recent imagery is from 2011, and comes from another company as well (Copel), so I am not pushing this anymore. Therefore, I am closing this PR.

**Comment by rbuffat** [comment]
@matheusgomesms Thanks for this update!

**Comment by cicku** [comment]
Should we contact DWG for revert of all affected changesets?

**Pull request closed without merging**
