### PR TITLE
Add reference URLs for layers in Austria.

### PR DESCRIPTION
**Pull request by hikemaniac**
This PR adds reference URLs for several layers in Austria. It also fixes one typo where the text says "goverment" instead "government". As this is my first contribution to this repository, can you please verify its correctness?

### CODE REVIEW

**Comment by grischard** [comment]
Much appreciated, thank you!

Since you're interested in Austrian layers: the VoGIS and Vienna layers are missing a license property. Would you have any idea of what should go there?

**Comment by hikemaniac** [comment]
@grischard I did some research on the other layers licenses and found out that all the Vienna layers are licensed under [Creative Commons Attribution 3.0 Austria](https://creativecommons.org/licenses/by/3.0/at/deed.de) according to [data.gv.at](https://data.gv.at). For the VoGIS layers the situation is not as easy. They are not published under a proper license but under certain [usage terms](http://vogis.cnv.at/nutzungsbestimmungen/nutzung.pdf) which say, that the data may be used when the government of Vorarlberg is informed about it (which is probably true for this project and OSM).

Should I submit another pull request for adding the `license_url` attribute?

**Comment by tyrasd** [comment]
//cc @simon04

**Comment by grischard** [comment]
The CC-BY license is not fully compatible with the ODbL, so we'll [need a tiny bit of extra paperwork](https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/).

I'm not sure they understand the CC-BY fully, as their usage terms contradict CC-BY. In any case, we can't guarantee that OSM won't be used, for example, for pornography.

I'm not sure the VoGIS email is enough either. Any thoughts, @simonpoole ?

**Comment by simonpoole** [comment]
Yes, their additional usage terms contradict the terms in CC BY (any version, or actually any "open" license). They need to make up their mind.

**Pull request merged**
