### PR TITLE
Formatted the imagery.xml file for better readability

### PR DESCRIPTION
**Pull request by Asteliks**
The content is the same but now you can actually read it as it no longer is a one liner

### CODE REVIEW

**Comment by rbuffat** [comment]
This file is automatically generated from all *geojson files: https://github.com/osmlab/editor-layer-index/blob/11b1b68120edf1e0550376442459e998a55f58ba/Makefile#L15
Thus, your commit would be overwritten the next time it is generated. As far as I'm aware of the file is not intended to be read by humans. 

I guess the only argument against more human-readable formatting would be an increase in file size?

**Comment by grischard** [comment]
Yes, the produced file isn't meant to be readable.

**Comment by Asteliks** [comment]
thanks didn't know that. Could you tell me how can I add my previous PR to JOSM?

**Comment by grischard** [comment]
What do you mean by "add to JOSM"? You want to use the ELI imagery in JOSM?

**Comment by Asteliks** [comment]
If I understand it correctly the changes summited in the source folder go to everything but JOSM? Is that why you list JOSM as Optional?
That would be:
-https://github.com/osmlab/editor-layer-index/pull/935
-https://github.com/osmlab/editor-layer-index/pull/936

**Comment by grischard** [comment]
Ah! Ideally, you'd add them with the other layers in https://josm.openstreetmap.de/wiki/Maps/Poland so that all the JOSM users can benefit from it.

**Comment by Asteliks** [comment]
Perfect I'll do so. Do I only need to click the edit this site or is there a different place to submit the changes?

**Comment by grischard** [comment]
Yup, you can just click "Edit" there.

**Comment by Asteliks** [comment]
Thanks I'll do so in a moment.
I feel like asking about a different PR here isn't a welcome thing to do but is there something wrong with this PR: https://github.com/osmlab/editor-layer-index/pull/935
TBH we need it quite bad in Poznan the latest maps we where using are from 2016 and much has changed. (I suggest moving the conversation there)

**Comment by grischard** [comment]
I've merged #935. Now you have to do it on the JOSM side too, otherwise the universe will be out of balance :)

**Comment by Asteliks** [comment]
I see we need it perfectly balanced, well as all things should be :D

**Comment by Asteliks** [comment]
Unfortunately the story ain't over. Im trying to commit this to the said wiki, but I'm getting an error "Ostrzeżenie: Niepoprawna strona Wiki: XML validation for map failed: line 1481: EntityRef: expecting ';' (line 1481)"

The funny thing is 1481 corresponds to the url and I don't see how a ';' is expected there

```XML
    <entry>
        <name>Poznań: Orthophotomap Bieżąca (aerial image)</name>
        <id>poznan-ortofotomapaBiezaca</id>
        <category>photo</category>
        <type>wms</type>
        <url><![CDATA[http://wms2.geopoz.poznan.pl/geoserver/gwc/service/wms?LAYERS=ortogpkg:ortofotomapa_biezaca&STYLES=&FORMAT=image/jpeg&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap]]></url>
        <attribution-text>Zarząd Geodezji i Katastru Miejskiego GEOPOZ</attribution-text>
	<attribution-url>https://www.geopoz.pl/</attribution-url>
        <permission-ref>https://www.geopoz.pl/bip/index.php?t=200&id=2449</permission-ref>
        <privacy-policy-url>https://www.geopoz.pl/portal/index.php?t=200&id=5142</privacy-policy-url>
        <projections>
            <code>CRS:84</code>
            <code>EPSG:2177</code>
	    <code>EPSG:2180</code>
            <code>EPSG:3857</code>
	    <code>EPSG:4326</code>
        </projections>
        <bounds min-lat='52.28401' min-lon='16.72794' max-lat='52.51784' max-lon='17.0831'>
            <shape>
                <point lat='52.48838' lon='16.72794' /><point lat='52.48982' lon='16.86925' /><point lat='52.50779' lon='16.86879' />
                <point lat='52.50845' lon='16.93948' /><point lat='52.51743' lon='16.93926' /><point lat='52.51784' lon='16.98639' />
                <point lat='52.45494' lon='16.98784' /><point lat='52.45534' lon='17.03491' /><point lat='52.43736' lon='17.03530' />
                <point lat='52.43774' lon='17.08235' /><point lat='52.40180' lon='17.08310' /><point lat='52.40161' lon='17.05960' />
		<point lat='52.32075' lon='17.06129' /><point lat='52.32035' lon='17.01438' /><point lat='52.28441' lon='17.01518' />
		<point lat='52.28401' lon='16.96829' /><point lat='52.30198' lon='16.96787' /><point lat='52.30134' lon='16.89752' />
		<point lat='52.33728' lon='16.89662' /><point lat='52.33638' lon='16.80273' /><point lat='52.37232' lon='16.80176' />
		<point lat='52.37210' lon='16.77828' /><point lat='52.45294' lon='16.77603' /><point lat='52.45244' lon='16.72897' />
                <point lat='52.48838' lon='16.72794' />
            </shape>
        </bounds>
        <country-code>PL</country-code>
        <max-zoom>23</max-zoom>
        <valid-georeference>true</valid-georeference>
    </entry>
```

**Comment by Klumbumbus** [comment]
`permission-ref` and `privacy-policy-url` contain a `&` so these urls need to be wrapped in `<![CDATA[` `]]>` too. See https://josm.openstreetmap.de/wiki/Maps

**Comment by Asteliks** [comment]
wow. Thanks it works now, silly mistake on my side

**Pull request closed without merging**
