### PR TITLE
add Ukraine - Vinnytsia 2020, remove 2018

### PR DESCRIPTION
**Pull request by bezdna**

### CODE REVIEW

**Comment by andrewharvey** [comment]
If the 2018 imagery is still available best to leave it and add a new source for the later imagery. It can be useful for mappers to compare with older imagery when editing.

If the new imagery is "best" then you can remove the best flag from the old imagery.

**Comment by bezdna** [comment]
> If the 2018 imagery is still available best to leave it and add a new source for the later imagery. It can be useful for mappers to compare with older imagery when editing.
> 
> If the new imagery is "best" then you can remove the best flag from the old imagery.

2018 not available now (
only 2020

**Comment by Klumbumbus** [comment]
2018 is still available. Only the URL here was outdated.

https://josm.openstreetmap.de/wiki/Maps/Ukraine
https://josm.openstreetmap.de/mapsview?entry=Ukraine%20-%20Vinnytsia%202018
https://josm.openstreetmap.de/mapsview?entry=Ukraine%20-%20Vinnytsia%202020

**Comment by bezdna** [comment]
> 2018 is still available. Only the URL here was outdated.
> 
> https://josm.openstreetmap.de/wiki/Maps/Ukraine
> https://josm.openstreetmap.de/mapsview?entry=Ukraine%20-%20Vinnytsia%202018
> https://josm.openstreetmap.de/mapsview?entry=Ukraine%20-%20Vinnytsia%202020

thanks, I will add Vinnytsia 2018 later.

**Comment by rbuffat** [comment]
> 2018 is still available. Only the URL here was outdated.
> 
> https://josm.openstreetmap.de/wiki/Maps/Ukraine
> https://josm.openstreetmap.de/mapsview?entry=Ukraine%20-%20Vinnytsia%202018
> https://josm.openstreetmap.de/mapsview?entry=Ukraine%20-%20Vinnytsia%202020

@Klumbumbus @bezdna
I only get 403 Forbidden HTTP codes using these links. Is this server geoblocked?

**Comment by bezdna** [comment]
> I only get 403 Forbidden HTTP codes using these links. Is this server geoblocked?

image
image
from Ukraine work, from other location maybe geoblocked.

**Comment by rbuffat** [comment]
@bezdna Thanks for checking!

**Comment by Klumbumbus** [comment]
>I only get 403 Forbidden HTTP codes using these links. Is this server geoblocked?

Both work fine for me from Germany with JOSM and webbrowser.

**Comment by rbuffat** [comment]
> > I only get 403 Forbidden HTTP codes using these links. Is this server geoblocked?
> 
> Both work fine for me from Germany with JOSM and webbrowser.

They seem not to work from Switzerland and from the github CI location. According to http://www.site24x7.com/public/t/results-1604256921849.html the server works also from the Netherlands.

**Pull request merged**
