### PR TITLE
Update aerial imagery in Capetown, South Africa

### PR DESCRIPTION
**Pull request by tsmock**
Add 2017 and 2018 imagery from Capetown, South Africa.

Largely copied from the 2015 aerial geojson file, with modifications for current years. I did leave a "best" tag in the 2018 imagery properties.

-----

This should fix the travis-ci build error ( https://travis-ci.org/osmlab/editor-layer-index/builds/555263087 ) from the last pull request.

### CODE REVIEW

**Comment by grischard** [comment]
Hi @taylorsmock ! You say that permission for usage in OSM is implicit, but https://www.arcgis.com/sharing/rest/content/items/739759d8127f4d1f9ba8ef9019878147/info/metadata/metadata.xml?format=default&output=html actually says the opposite in "Limitations of use": the attribution requirements are pretty strong, and reproduction, copying or usage without written permission is explicitly forbidden. What makes you say it's implicitly allowed?

**Comment by tsmock** [comment]
I'll be honest, I probably missed that in the wall of text.

I assume it is the 

> The User is required to explicitly state that the City does not warrant or guarantee the quality or accuracy of the data, accessed, extracted and/or used from this site.
Users are required to include the following disclaimer at the site where the software, application or other secondary or derivative application can be accessed or downloaded: “This site provides products or services using data that has been modified for use from its original source, www.capetown.gov.za, the official website of the City of Cape Town. The City of Cape Town makes no claims as to the content, accuracy, timeliness, or completeness of any of the data provided at this site. The data provided at this site is subject to change at any time. It is understood that the data provided at this site is being used at one’s own risk.”

and/or

> 1.2 The User shall not, under any circumstances whatsoever reproduce, copy or use the City’s IP or permit the use of the City’s IP by any third party without the City’s prior written consent

lines that are at issue.

Since I am not a lawyer, I assumed that attribution was required for the applications directly using the data (e.g., JOSM/iD) and that the source tag would be sufficient for everything else (since that is attribution), along with adding them to the Contributors page on the OSM wiki.

As far as implicitly allowed, since it was published under their "[Open Data](https://web1.capetown.gov.za/web1/OpenDataPortal/Document/GetDocument/2)" policy, I assumed that it used the same standard for open data as many other places (e.g., no restrictions on use, except for illegal activity). It looks like I missed the 1.2 line in the Intellectual Rights section. From the non-legal standpoint, I would have assumed that it was talking about the City's logo and emblem.

That being said, I'll reach out and see if I can get explicit permissions.

**Comment by grischard** [comment]
Good, contacting them does indeed now seem to be the best thing to do.

**Comment by Firefishy** [comment]
I asked City of Cape Town for their 2016 imagery in 2016. They were only willing to sell it to OpenStreetMap for a discount rate (R10,000 / ~US$700) at the time. After some negotiation they were willing to give us the older 2015 imagery for mapping usage only in OpenStreetMap.
I announced it here: https://lists.openstreetmap.org/pipermail/talk-za/2016-September/001215.html

It would be great to get more recent imagery. Please do ask them. I am happy to supply the contact details I have from 2016. If you are able to get me their source MrSID imagery files + permission, I'd happily put it up on my site: https://coct.aerial.openstreetmap.org.za/

**Comment by tsmock** [comment]
[RE: Data request - 2018:2017 aerial imagery for OpenStreetMap.pdf](https://github.com/osmlab/editor-layer-index/files/3482461/RE.Data.request.-.2018.2017.aerial.imagery.for.OpenStreetMap.pdf)
[Data request - 2018_2017 aerial imagery for OpenStreetMap (1).eml.zip](https://github.com/osmlab/editor-layer-index/files/3482411/Data.request.-.2018_2017.aerial.imagery.for.OpenStreetMap.1.eml.zip)

I think this is all that is needed (we just have to reference the City of Cape Town as the imagery source).

I'll add a commit with the pdf and a link to the pdf.

**Pull request merged**
