### PR TITLE
Add Croatia TMS server for City of Knin aerial imagery

### PR DESCRIPTION
**Pull request by hbogner**

### CODE REVIEW

**Comment by grischard** [comment]
Cool! What's the licence on these? Could you please add the licence properties?

**Comment by hbogner** [comment]
I got written permission to use it for OSM

**Comment by hbogner** [comment]
I tried, it fails. Now you take over!!!

**Comment by hbogner** [comment]
OK, what license do you mean exactly?
Original data license or license to use our TMS?

**Comment by grischard** [comment]
You can copy-paste from #644. `license` is the license for the imagery specified using a [SPDX identifier](https://spdx.org/licenses/), or 'COMMERCIAL'. In your case, since you got special permission, it's a link with `license_url` that would be useful.

**Comment by andrewharvey** [comment]
@hbogner Could you also include a copy of or link to the written permission?

**Comment by hbogner** [comment]
Here is the law on which the data was released, description of rights, description of license and closest license on that list... please advise what exact license to use....

**Comment by hbogner** [comment]
License for this data is not "commercial" but some sort of "cc-by" or "open data" as it can be read here:
Law on which data was released: https://narodne-novine.nn.hr/clanci/sluzbeni/2013_02_25_403.html
Description of rights: http://data.gov.hr/o-portalu-cijeli
Description of license: http://data.gov.hr/open-licence-republic-croatia
Additional description: http://data.gov.hr/faq#5

It doesn't match https://spdx.org/licenses/ exactly so checks fail.

Also should I create osm wiki page with all this described and link to it for "license_url"?

**Comment by grischard** [comment]
Ok, if you can just drop the 'license' property I'll merge it. The license url is enough.

**Comment by grischard** [comment]
Čestitam!

**Comment by hbogner** [comment]
Hvala :)

And now when I got the syntax right I'll add rest of the layers available for OSM.

**Comment by don-vip** [comment]
The icon is not used?

**Comment by hbogner** [comment]
I forgot to include the icon.
Will fix that with next layer and next pull request: https://github.com/osmlab/editor-layer-index/pull/663

**Pull request merged**
