### PR TITLE
feat(i18n): enable i18n of selected imageries

### PR DESCRIPTION
**Pull request by simon04**
For https://github.com/osmlab/editor-layer-index/issues/17#issuecomment-306755589.

The generated JSON format is supported by Transifex: https://docs.transifex.com/formats/json/

cc: @tyrasd, @manfredbrandl

### CODE REVIEW

**Comment by tyrasd** [comment]
Ok, but how would it work from here onward? Suppose we set up a transifex project for this: how/where would we retrieve and store the translated strings?

And is it really worth the effort to set this up for only a handful of strings to be translated? I personally would still prefer a simpler solution where anything is handled via PRs to this repo (as outlined here: https://github.com/osmlab/editor-layer-index/issues/17#issuecomment-230157833).

//cc @bhousel

**Comment by simon04** [comment]
Either a new transifex project, or a separate string bundle within the iD editor.

Transifex supports automatically updating source files: https://docs.transifex.com/projects/updating-content/#automatically-updating-source-files

**Comment by tyrasd** [comment]
sure, but:

> how/where would we retrieve and store the translated strings [from transifex]?

**Comment by simon04** [comment]
Ah, I overlooked this question. One way would be to use the [Transifex Client](https://docs.transifex.com/client/client-configuration), fetch the changes from time to time and commit them to `i18n/`.

**Comment by bhousel** [comment]
> And is it really worth the effort to set this up for only a handful of strings to be translated? I personally would still prefer a simpler solution where anything is handled via PRs to this repo (as outlined here: #17 (comment)).

The nice thing about this is that it's opt-in - only the imagery sources that should be translated would have the i18n flag set.  I think we'd want to set it for everything under `sources/world/`, so it would be more than just the few included in this PR.

We'd also want to get the descriptions too, not just the names.  They would need to have a unique id generated too like `layer_id + '_description'`.

Also, I think I prefer having the translation resources separate instead of as part of the source itself (like `name:fr`, `description:fr`) .  Mostly because if we do start translating it on the iD side, there are around 70 languages, so potentially 140 additional strings per source, which would make the files considerably larger.

> how would it work from here onward? Suppose we set up a transifex project for this: how/where would we retrieve and store the translated strings?

I can definitely push this to the iD Transifex project as a separate resource, and happy to grant admin access to anyone who needs it.

We could have a script like the iD one that connects to Transifex and pulls down the latest sources into this repo.  Anyone who is maintaining this repo would need to do `make translations` sometimes, which isn't too different than how we already have to regenerate the target files sometimes.  

(Yes, in the back of my mind is moving this project to having more proper versions and releases)

**Comment by simonpoole** [comment]
Please do not include translated strings in the data itself, having them in separate files enables them

- to be easily transformed to a different format (assuming that .po format wont happen here in a month of Sundays)
- avoids having to parse lots of stuff that you are not interested in when reading the imagery configs

Naturally I should point out that there is an OpenStreetMap organisation on transifex that can be used for this project.. but I'm not holding my breath,

**Comment by bhousel** [comment]
> Naturally I should point out that there is an OpenStreetMap organisation on transifex that can be used for this project.. but I'm not holding my breath,

@simonpoole I think this has changed since we last looked at it 2 years ago - it looks like now we can transfer iD to the openstreetmap organization and keep all of our translators and teams intact 🤞 

https://docs.transifex.com/projects/transferring-a-project-to-another-organization

If that is the case now, would it be ok for this `editor-layer-index` to be a resource under the iD project, but under the openstreetmap organization?  I'd also send out an announcement to let the iD teams know about the change and encourage them to translate the other openstreetmap projects too!

**Comment by bhousel** [comment]
> @simonpoole I think this has changed since we last looked at it 2 years ago - it looks like now we can transfer iD to the openstreetmap organization and keep all of our translators and teams intact 🤞

Followup: It worked and iD is now moved 🎉 
https://www.transifex.com/openstreetmap/id-editor/announcements/7227/

**Comment by simonpoole** [comment]
@bhousel thanks.

**Comment by simon04** [comment]
How to proceed?
* Add new editor-layer-index project to https://www.transifex.com/openstreetmap/public/?
* Add new resource to https://www.transifex.com/openstreetmap/id-editor/?
* Do not translate at all and close this PR and #17 (wont-fix)

**Comment by bhousel** [comment]
> Add new resource to https://www.transifex.com/openstreetmap/id-editor/?

I'll do this, since the imagery strings all need to be translated to the iD languages anyway.   I can setup the integration with Transifex using the client and write up some instructions and add something to the project `Makefile` to have it run.  (Will probably get to this tomorrow - I'm on vacation today.)

**Comment by bhousel** [comment]
Just merged this.. I also added code to localize the attribution text if present.
TODO: Next steps for integration with Transifex are on me.

**Comment by bhousel** [comment]
> Next steps for integration with Transifex are on me.

This was done!
see https://github.com/osmlab/editor-layer-index/blob/gh-pages/CONTRIBUTING.md#translations

**Pull request merged**
