### PR TITLE
Updated URL for DK imagery 

### LINKED ISSUE #1405: [Watchdog] Imagery "SDFE DTK Kort25": sources/europe/dk/SDFEDTKKort25.geojson broken
Watchdog failed for 5 consecutive days for:
"SDFE DTK Kort25" -> [sources/europe/dk/SDFEDTKKort25.geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/dk/SDFEDTKKort25.geojson)

Reason:
Error: WMS -: URL: https://kortforsyningen.kms.dk/topo25?SERVICE=WMS&REQUEST=GetCapabilities&LOGIN=OpenStreetMapDK2015&PASSWORD=Gall4Peters Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://kortforsyningen.kms.dk/topo25?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0&LOGIN=OpenStreetMapDK2015&PASSWORD=Gall4Peters Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://kortforsyningen.kms.dk/topo25?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1&LOGIN=OpenStreetMapDK2015&PASSWORD=Gall4Peters Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://kortforsyningen.kms.dk/topo25?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.0&LOGIN=OpenStreetMapDK2015&PASSWORD=Gall4Peters Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://kortforsyningen.kms.dk/topo25?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.0.0&LOGIN=OpenStreetMapDK2015&PASSWORD=Gall4Peters Error: Could not parse XML.
Error: WMS -: URL: https://kortforsyningen.kms.dk/topo25?service=WMS&request=GetCapabilities&login=OpenStreetMapDK2015&password=Gall4Peters Error: Could not parse XML.
Error: WMS 1.3.0: URL: https://kortforsyningen.kms.dk/topo25?service=WMS&request=GetCapabilities&version=1.3.0&login=OpenStreetMapDK2015&password=Gall4Peters Error: Could not parse XML.
Error: WMS 1.1.1: URL: https://kortforsyningen.kms.dk/topo25?service=WMS&request=GetCapabilities&version=1.1.1&login=OpenStreetMapDK2015&password=Gall4Peters Error: Could not parse XML.
Error: WMS 1.1.0: URL: https://kortforsyningen.kms.dk/topo25?service=WMS&request=GetCapabilities&version=1.1.0&login=OpenStreetMapDK2015&password=Gall4Peters Error: Could not parse XML.
Error: WMS 1.0.0: URL: https://kortforsyningen.kms.dk/topo25?service=WMS&request=GetCapabilities&version=1.0.0&login=OpenStreetMapDK2015&password=Gall4Peters Error: Could not parse XML.

CC contributors to this imagery:
@rbuffat, @grischard

### LINKED ISSUE #1415: [Watchdog] Imagery "SDFE Surface Shadow Map (40 cm)": sources/europe/dk/SDFESurfaceShadowMap(40cm).geojson broken
Watchdog failed for 5 consecutive days for:
"SDFE Surface Shadow Map (40 cm)" -> [sources/europe/dk/SDFESurfaceShadowMap(40cm).geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/dk/SDFESurfaceShadowMap(40cm).geojson)

Reason:
Error: Layers 'dhm_overflade_skyggekort' not advertised by WMS GetCapabilities request. In rare cases WMS server do not advertise layers.

CC contributors to this imagery:
@rbuffat, @grischard

### LINKED ISSUE #1416: [Watchdog] Imagery "SDFE Terrain Shadow Map (40 cm)": sources/europe/dk/SDFETerrainShadowMap(40cm).geojson broken
Watchdog failed for 5 consecutive days for:
"SDFE Terrain Shadow Map (40 cm)" -> [sources/europe/dk/SDFETerrainShadowMap(40cm).geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/dk/SDFETerrainShadowMap(40cm).geojson)

Reason:
Error: Layers 'dhm_terraen_skyggekort' not advertised by WMS GetCapabilities request. In rare cases WMS server do not advertise layers.

CC contributors to this imagery:
@rbuffat, @grischard

### PR DESCRIPTION
**Pull request by sulfo**
Most of the Danish imagery is broken due to changes in the credentials. 
I don't know why it was changed, but I was told by a well known mapper in the Danish community told me, that the updated 
 URLs and credentials [can be found here](https://josm.openstreetmap.de/wiki/Maps/Denmark).

So here's my pull request trying to implement the updated URLs :)

Fixes #1416, Fixes #1405, Fixes #1415

### CODE REVIEW

**Comment by rbuffat** [comment]
@sulfo Thanks for your PR. The script seems the have an issue with one of the entries:

```
INFO:root:Processing sources/europe/dk/SDFEDTKKort25.geojson
ERROR:root:Layers 'dkt25' not advertised by WMS GetCapabilities request (Some server do not advertise layers, but they are very rare).: https://api.dataforsyningen.dk/dtk_25_DAF?service=WMS&request=GetMap&token=52065b2ec5fda5a46a50b451f3f24473&FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&Layers=dkt25&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
```
They seem to have an excellent error message!:

`https://api.dataforsyningen.dk/dtk_25_DAF?service=WMS&request=GetMap&token=52065b2ec5fda5a46a50b451f3f24473&FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&Layers=dkt25&STYLES=&CRS=EPSG:3857&WIDTH=256&HEIGHT=256&BBOX=1008357.2769976808,7398492.840748902,1008968.7732238761,7399104.336975095`

gives me the following response:

```
ServiceExceptionReport version="1.1.0">
<ServiceException>No workhorse available: All workhorses, including quarantined, are exhausted.</ServiceException>
</ServiceExceptionReport>
```

**Comment by rbuffat** [comment]
The WMS server supports the following layers:
```
Layers:
0: dtk_25 (DTK25 - Danmarks Topografiske Kortværk 1:25.000)
1: dtk25 (DTK25)
2: dtk25_2021 (DTK25 2021)
3: dtk25_2020 (DTK25 2020)
4: dtk25_2019 (DTK25 2019)
5: dtk25_2017 (DTK25 2017)
6: dtk25_2016 (DTK25 2016)
7: dtk25_2015 (DTK25 2015)
8: dtk25_2014 (DTK25 2014)
9: dtk25_2013 (DTK25 2013)
10: dtk25_2012 (DTK25 2012)
11: dtk25_2011 (DTK25 2011)
12: dtk25_2010 (DTK25 2010)
13: dtk25_2009 (DTK25 2009)
14: dtk25_2008 (DTK25 2008)
15: dtk25_2007 (DTK25 2007)
16: dtk25_2006 (DTK25 2006)
17: dtk25_2005 (DTK25 2005)
18: dtk25_2004 (DTK25 2004)
19: dtk25_2002 (DTK25 2002)
```

@sulfo should `dkt25` be `dtk25``?

**Comment by sulfo** [comment]
> The WMS server supports the following layers:
> 
> ```
> 
> Layers:
> 
> 0: dtk_25 (DTK25 - Danmarks Topografiske Kortværk 1:25.000)
> 
> 1: dtk25 (DTK25)
> 
> 2: dtk25_2021 (DTK25 2021)
> 
> 3: dtk25_2020 (DTK25 2020)
> 
> 4: dtk25_2019 (DTK25 2019)
> 
> 5: dtk25_2017 (DTK25 2017)
> 
> 6: dtk25_2016 (DTK25 2016)
> 
> 7: dtk25_2015 (DTK25 2015)
> 
> 8: dtk25_2014 (DTK25 2014)
> 
> 9: dtk25_2013 (DTK25 2013)
> 
> 10: dtk25_2012 (DTK25 2012)
> 
> 11: dtk25_2011 (DTK25 2011)
> 
> 12: dtk25_2010 (DTK25 2010)
> 
> 13: dtk25_2009 (DTK25 2009)
> 
> 14: dtk25_2008 (DTK25 2008)
> 
> 15: dtk25_2007 (DTK25 2007)
> 
> 16: dtk25_2006 (DTK25 2006)
> 
> 17: dtk25_2005 (DTK25 2005)
> 
> 18: dtk25_2004 (DTK25 2004)
> 
> 19: dtk25_2002 (DTK25 2002)
> 
> ```
> 
> 
> 
> @sulfo should `dkt25` be `dtk25``?

Looks right 🙃
Let me find my laptop and find it 💪

**Comment by rbuffat** [comment]
Thanks @sulfo

**Pull request merged**
