### PR TITLE
Do not verify ssl connections in case of failure

### PR DESCRIPTION
**Pull request by rbuffat**
In https://github.com/osmlab/editor-layer-index/pull/821 verification of a SSL connection fails. For the purpose of ELI, an SSL connection is not strictly required.

With this PR, first, an SSL connection using up-to-date Root Certificates (using the certifi library) is tried.
If this connection fails, as fallback a connection without SSL verification is tried. 

@grischard  I did not extensively test this, please have a careful look at it.

### CODE REVIEW

**Comment by stefanb** [comment]
A sane workflow for cases when the TLS certificate of the service is not trusted would be to provide a public key in the source json description, so that other services can use the service while validating the certificate, not just ignoring it altogether.

**Comment by rbuffat** [comment]
@stefanb This check is only applied to sources changed in a PR. The goal of it is to provide feedback to the creator of the PR if the URL exists or not (e.g. if there is a typo). There is never the need for transmission of any data. 

In my opinion, requiring a public key for a certificate, that can change at any point and will never be tracked, does not provide a significant benefit. 

The best way imho would be to fix why requests fails to verify "https://kentucky.gov" in https://github.com/osmlab/editor-layer-index/pull/821, while common web browsers don't. 
I don't see at the moment a solution for that, maybe you can look at it.

**Comment by stefanb** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=kentucky.gov
> This server's certificate chain is incomplete. Grade capped to B.

**Comment by 1ec5** [comment]
Thank you for the analysis, @stefanb. I’m not sure what to do at this point about #821. For what it’s worth, the tile server at kyraster.ky.gov [also earns a B](https://www.ssllabs.com/ssltest/analyze.html?d=kyraster.ky.gov) for supporting TLS 1.0–1.1, but it has no chain issues. Only the privacy policy at kentucky.gov has chain issues.

As @rbuffat points out, the reachability check is only intended to guard against typos at the time that a PR is authored. The check runs only in PR builds, not push builds, so this repository provides no guarantee about the ongoing reachability of the privacy policies it lists. (It also doesn’t prevent existing layers from pointing to unencrypted HTTP tile server URLs.)

> provide a public key in the source json description

So I’d follow the links in [this post](https://stackoverflow.com/a/46604917/4585461) and paste the keys into the JSON somewhere, correct? Since the reachability check doesn’t run on push builds, is there a risk of this data silently going stale?

If the privacy policy’s certificate is a showstopper, then I suppose a simpler workaround would be to set the `privacy_policy_url` to a page on a correctly configured server that contains a link to kentucky.gov. It isn’t as if any clients would do anything automatic with this URL.

**Comment by grischard** [comment]
Our friends on the JOSM side have the same issue. I'd much rather see something that uses the system certificates, like the browsers do and like https://stackoverflow.com/questions/42982143/python-requests-how-to-use-system-ca-certificates-debian-ubuntu describes.

**Comment by rbuffat** [comment]
Closing this as it seems not to be the solution.

**Pull request closed without merging**
