### PR TITLE
Create Brandenburg-DOP20c.json

### PR DESCRIPTION
**Pull request by tordans**
This adds the areal images of Brandenburg, which have been available for a while now; based on the information from https://josm.openstreetmap.de/wiki/Maps/Germany#BrandenburgGeoBasis-DELGBDTM1m, extended with updated date information (sehe linked PDF in the code and https://geobasis-bb.de/lgb/de/geodaten/luftbilder/luftbilder-aktuell/).

- [ ]  TODO: shape coordinates seem to be off. I copied the shape from the XML but when I test it in geojson.io, its in the wrong place on the word. Who can fix this?

--

Note, I did not include https://josm.openstreetmap.de/wiki/Maps/Germany#BrandenburgGeoBasis-DELGBDTM1m since this is IMO not good enough with 1m detail-level to be used for mapping.

I also did not add https://wiki.openstreetmap.org/wiki/Brandenburg/Geoportal#N.C3.BCtzliche_WMS-Layer_f.C3.BCr_OSM `wms:https://isk.geobasis-bb.de/ows/alkis_wms?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=adv_alkis_flurstuecke,adv_alkis_gebaeude,adv_alkis_gewaesser,katastergrenzen,adv_alkis_verkehr,adv_alkis_vegetation,adv_alkis_siedlung,adv_alkis_oeff_rechtl_sonst_festl&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}` since this requires the mapper do unterstand that those shapes need to be reviewed locally and not just copied. Quite a few of those houses (…) are not up to date.

### CODE REVIEW

**Comment by tordans** [comment]
One more thing: If someone knows how to edit the JOSM layer index, please update the information about the image-year similar to this PR. The fact, that is says 2020 without acknowledging that some images are from 2017 was confusing for me while mapping locally.

**Review by andrewharvey — CHANGES_REQUESTED** [review]
by convention the filename should have the .geojson extension, could you change that please?

**Comment by Klumbumbus** [comment]
> One more thing: If someone knows how to edit the JOSM layer index, please update the information about the image-year similar to this PR.

Changed in https://josm.openstreetmap.de/wiki/Maps/Germany?action=diff&version=248
(You can adjust things there yourself too by editing that page: https://josm.openstreetmap.de/wiki/Maps/Germany.)

**Comment by tordans** [comment]
I changed the Filetype as requested.

Do you guys know why the coordinates are off? https://github.com/osmlab/editor-layer-index/pull/933/files?short_path=c468300#diff-c468300d3ebc1204e2c10aac22571647 shows the coordinates not in Brandenburg. How would I transpose them to the right/which? projection?

Update: Thanks Klumbumbus! (For Reference: https://josm.openstreetmap.de/wiki/Maps/Germany?sfp_email=&sfph_mail=&action=diff&version=248&old_version=247&sfp_email=&sfph_mail=)

**Comment by rbuffat** [comment]
@tordans The WMS URL is for WMS 1.1.1 while the server supports WMS 1.3.0. The URL for WMS 1.3.0 would look like this:

```
        "url": "https://isk.geobasis-bb.de/ows/dop20c_wms?LAYERS=bebb_dop20c&STYLES=&FORMAT=image/png&CRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap",
        "available_projections": [
            "EPSG:25832",
            "EPSG:25833",
            "EPSG:3034",
            "EPSG:3035",
            "EPSG:3045",
            "EPSG:3857",
            "EPSG:4258",
            "EPSG:4326",
            "EPSG:4839",
            "EPSG:5650",
            "EPSG:900913"
     ],
```

The WMS server reports the following license:

> WMS Server Metadata:
> Access constraints:
> Nutzungsbedingungen: Datenlizenz Deutschland - Namensnennung - Version 2.0, https://www.govdata.de/dl-de/by-2-0; dl-de-by-2.0, Namensnennung: "GeoBasis-DE/LGB“, Beispiel: „© GeoBasis-DE/LGB, dl-de/by-2-0, (Daten geändert)“, (Klammer = optional) Hinweis: werden auch Daten des Bundeslandes Berlin genutzt, ist der Copyright-Vermerk um den Hinweis “© Geoportal Berlin, dl-de/by-2-0“ zu ergänzen. Beispiel: „© GeoBasis-DE/LGB, dl-de/by-2-0; © Geoportal Berlin, dl-de/by-2-0 (Daten geändert)“, (Klammer = optional)

**Comment by andrewharvey** [comment]
> Do you guys know why the coordinates are off?

GeoJSON uses longitude, latitude order. Perhaps you've entered as latitude, longitude order?

**Comment by andrewharvey** [comment]
> WMS Server Metadata:
Access constraints:
Nutzungsbedingungen: Datenlizenz Deutschland - Namensnennung - Version 2.0, https://www.govdata.de/dl-de/by-2-0; dl-de-by-2.0, Namensnennung: "GeoBasis-DE/LGB“, Beispiel: „© GeoBasis-DE/LGB, dl-de/by-2-0, (Daten geändert)“, (Klammer = optional) Hinweis: werden auch Daten des Bundeslandes Berlin genutzt, ist der Copyright-Vermerk um den Hinweis “© Geoportal Berlin, dl-de/by-2-0“ zu ergänzen. Beispiel: „© GeoBasis-DE/LGB, dl-de/by-2-0; © Geoportal Berlin, dl-de/by-2-0 (Daten geändert)“, (Klammer = optional)

From a quick glance at the translation, it looks like this might have the same concerns about chained attribution as CC BY which needs a waiver. Is there any prior discussion about this license for OSM? 

https://wiki.openstreetmap.org/wiki/Import/ODbL_Compatibility doesn't list it.

**Comment by tordans** [comment]
~~Btw, this PR would close https://github.com/osmlab/editor-layer-index/issues/828~~

Update: No it would not, this issue is about the Alkis data, which IMO should not be part (see comment in the description)

**Comment by pathmapper** [comment]
> From a quick glance at the translation, it looks like this might have the same concerns about chained attribution as CC BY which needs a waiver. Is there any prior discussion about this license for OSM?

The NRW orthophotos had the same license "Datenlizenz Deutschland - Namensnennung - Version 2.0" (de-by-2.0) until March 1st 2020. Here is the related discussion (in German language) which came to the conclusion that de-by-2.0 is not compatible with OSM:
https://forum.openstreetmap.org/viewtopic.php?id=60528 

To my knowledge this was one of the reasons why NRW changed the license to "Data licence Germany - Zero - Version 2.0".
(The NRW data was just added to the layer index in https://github.com/osmlab/editor-layer-index/pull/919)

**Comment by tordans** [comment]
Just a quick note: the license is fine; but need to look at some more details; will write more+links ASAP.

---

Update: Quick reminder for me to remember: JOSM and iD (soon again) use the :name field in the changeset, so this needs to hold the legal information; reference https://github.com/openstreetmap/iD/issues/7842#issuecomment-704628299

**Comment by andrewharvey** [comment]
> Just a quick note: the license is fine; but need to look at some more details; will write more+links ASAP.

Sorry @tordans could you explain that? If what @pathmapper said is correct then "Data License Germany - Attribution - Version 2.0" (translated) is not compatible without a waiver, but as far as I can tell that's the license being used here..?

> The NRW orthophotos had the same license "Datenlizenz Deutschland - Namensnennung - Version 2.0" (de-by-2.0) until March 1st 2020. Here is the related discussion (in German language) which came to the conclusion that de-by-2.0 is not compatible with OSM:
https://forum.openstreetmap.org/viewtopic.php?id=60528

> To my knowledge this was one of the reasons why NRW changed the license to "Data licence Germany - Zero - Version 2.0".
(The NRW data was just added to the layer index in #919)

**Comment by tordans** [comment]
Hi, sorry for not answering for a while.

**I will stop working on this for now and will close my PR for the time being.**

Two reasons: 
1. https://github.com/openstreetmap/iD/issues/8086#issue-721843893 suggests that ELI is "deprecatable" and I don't want to invest time if that is the case; I also find this conversation and process very frustrating
2. it turned out to be a lot more complex than I hoped. I though I could just copy the JOSM data to ELI because the JOSM data is thought through but thanks to your questions I now realise that there are IMO still open issues that need to be discussed.

Thanks for helping me getting this far!

--- 

**This is the status quo of my research:**

**Licence:**

The licence page that the JOSM index and this PR links is not good. A better page would be https://wiki.openstreetmap.org/wiki/Brandenburg/Geoportal#Rechtliche_Grundlagen, which explains why the licence is OK to use. Or maybe a separate page just about this.

FYI, there was a year long process with the data providers to figure out how to solve the licensing which resulted in a good solution which is documented on the wiki page and the basis for all the uses of this data ATM. Unfortunatelly, this wiki page is quite hart do read IMO.

Status quo: I think we need to change the URL in this PR

**Attribution:**

The attribution text that the JOSM index uses is IMO not complete. The problem is, that the data we use also includes data about Berlin, not just Brandenburg because the Brandenburger merged both datasets for the URL we use. And on https://geobroker.geobasis-bb.de/gbss.php?MODE=GetProductInformation&PRODUCTID=253b7d3d-6b42-47dc-b127-682de078b7ae it says for "Digitale Orthophotos 20cm Bodenauflösung Farbe Cache Brandenburg mit Berlin (WMS)" (which is what we use IMO), to also reference the Berlin data:
> Namensnennung: "GeoBasis-DE/LGB“, Beispiel: „© GeoBasis-DE/LGB, dl-de/by-2-0…“, …Hinweis: werden auch Daten des Bundeslandes Berlin genutzt, ist der Copyright-Vermerk um den Hinweis “© Geoportal Berlin, dl-de/by-2-0“ zu ergänzen. 
> Beispiel: „© GeoBasis-DE/LGB, dl-de/by-2-0; © Geoportal Berlin, dl-de/by-2-0…“…

Status quo: I think we need to extend the attribution text which makes it very long **_or_** to exclude the Berlin Data from the JSON (which I dont know if possible) **_or_** use the Brandenburg-Only-Data.

**Sidestep: Other data sets:**

Just to close my tab: I think we should not do https://github.com/osmlab/editor-layer-index/issues/828. This data is about the shapes of buildings and the data looks like it can be trusted and just copied in OSM but in fact needs checking locally (I confirmed this myself). Adding this to iD will encourage armchair mapping which will not help in the end. This data source should IMO stay in the wiki for advanced users to use with a custom wms-source-feature. Or we should add a "how to use this data"-info to ELI + iD.

**Changeset data:**

(I discussed this issue before [here in the repo](https://github.com/osmlab/editor-layer-index/issues/646#issuecomment-536280940) + [in the iD repo](https://github.com/openstreetmap/iD/issues/6300#issuecomment-495860839) + there was [a more recent issue in the iD repo](https://github.com/openstreetmap/iD/issues/7876) and a discussion in the JOSM repo. The status is, not to change anything.)

The issue is: The licence "recomments" a certain wording to use for the source-attribute. However, ELI and JOSM index dont use this wording; they cannot store it. This is an issue with the berlin data as well. Right now, we ignore it and see if anyone objects. And in case anyone does, we would update the changeset comments with the correct wording. Which would be enough to satisfy the licence. 

Status quo: For now this topic is closed IMO; but I wanted to reference it.

**Boundingbox**

IMO, it is a good idea to use less values to describe Brandenburg, since the file is very big which affects load time.

Status quo: Not a must have, but nice to have.

**"name" attribute**

In https://josm.openstreetmap.de/wiki/Maps/Germany?sfp_email=&sfph_mail=&action=diff&version=248&old_version=247&sfp_email=&sfph_mail= the name was changed for the JOSM index, but now I am not sure if its satisfies the licence anymore, which asks for something like this "© GeoBasis-DE/LGB, dl-de/by-2-0; © Geoportal Berlin, dl-de/by-2-0" (see above). We also need to check, that this is the text that is used for the source-tag in changesets (see changeset data above). So it should be correct but not too long.

Status quo: Decide which is the best name value for all usecases

**Comment by andrewharvey** [comment]
> Hi, sorry for not answering for a while.
> I will stop working on this for now and will close my PR for the time being.

That's okay, no problem.

> openstreetmap/iD#8086 (comment) suggests that ELI is "deprecatable" and I don't want to invest time if that is the case; I also find this conversation and process very frustrating
it turned out to be a lot more complex than I hoped. I though I could just copy the JOSM data to ELI because the JOSM data is thought through but thanks to your questions I now realise that there are IMO still open issues that need to be discussed.
Thanks for helping me getting this far!

Yeah it's an ongoing discussion, in the meantime I find GitHub/GitLab etc a better workflow for maintaining a set of imagery for editors, so I'm still keen to try and maintain it so long as it's useful. If there were no downstream users then we might consider archiving this repo, but for now I'd still like it to thrive.

> The attribution text that the JOSM index uses is IMO not complete. The problem is, that the data we use also includes data about Berlin, not just Brandenburg because the Brandenburger merged both datasets for the URL we use. And on https://geobroker.geobasis-bb.de/gbss.php?MODE=GetProductInformation&PRODUCTID=253b7d3d-6b42-47dc-b127-682de078b7ae it says for "Digitale Orthophotos 20cm Bodenauflösung Farbe Cache Brandenburg mit Berlin (WMS)" (which is what we use IMO), to also reference the Berlin data:
> 
> Namensnennung: "GeoBasis-DE/LGB“, Beispiel: „© GeoBasis-DE/LGB, dl-de/by-2-0…“, …Hinweis: werden auch Daten des Bundeslandes Berlin genutzt, ist der Copyright-Vermerk um den Hinweis “© Geoportal Berlin, dl-de/by-2-0“ zu ergänzen.
Beispiel: „© GeoBasis-DE/LGB, dl-de/by-2-0; © Geoportal Berlin, dl-de/by-2-0…“…
> 
> Status quo: I think we need to extend the attribution text which makes it very long or to exclude the Berlin Data from the JSON (which I dont know if possible) or use the Brandenburg-Only-Data.

If it's a long attribution, I think that's okay, not much we can do if it's legally required. Editors which display this attribution could build in some kind of "..." to shorten the attribution with it expanded on click or something like that.

> (I discussed this issue before here in the repo + in the iD repo + there was a more recent issue in the iD repo and a discussion in the JOSM repo. The status is, not to change anything.)
> 
> The issue is: The licence "recomments" a certain wording to use for the source-attribute. However, ELI and JOSM index dont use this wording; they cannot store it. This is an issue with the berlin data as well. Right now, we ignore it and see if anyone objects. And in case anyone does, we would update the changeset comments with the correct wording. Which would be enough to satisfy the licence.

Legally required attribution is only provided through https://www.openstreetmap.org/copyright and https://wiki.openstreetmap.org/wiki/Contributors. Object tags or changeset tags are not where legal attribution is provided, source=* tags are just for mappers to understand what sources were used only.

So where the license recommends a particular attribution that's what should be used for the corresponding entry at https://wiki.openstreetmap.org/wiki/Contributors. This is a big reason why CC BY licenses need a waiver where we say that attribution happens on the Contributors wiki page.

> In https://josm.openstreetmap.de/wiki/Maps/Germany?sfp_email=&sfph_mail=&action=diff&version=248&old_version=247&sfp_email=&sfph_mail= the name was changed for the JOSM index, but now I am not sure if its satisfies the licence anymore, which asks for something like this "© GeoBasis-DE/LGB, dl-de/by-2-0; © Geoportal Berlin, dl-de/by-2-0" (see above). We also need to check, that this is the text that is used for the source-tag in changesets (see changeset data above). So it should be correct but not too long.

Similar to above, the name is not used for attribution, that's only done on the Contributors page.

**Comment by tordans** [comment]
Quick note about the attribution topic, because I was re-reading this thread just now and wanted to write it down for the next time I think I could quickly fix this (…):

> Legally required attribution is only provided through https://www.openstreetmap.org/copyright and https://wiki.openstreetmap.org/wiki/Contributors. Object tags or changeset tags are not where legal attribution is provided, source=* tags are just for mappers to understand what sources were used only.
>
>So where the license recommends a particular attribution that's what should be used for the corresponding entry at https://wiki.openstreetmap.org/wiki/Contributors. This is a big reason why CC BY licenses need a waiver where we say that attribution happens on the Contributors wiki page.

Unfortunately, this is not the practise that is recommended for data from Berlin and Brandenburg.

https://wiki.openstreetmap.org/wiki/Brandenburg/Geoportal#Rechtliche_Grundlagen summarizes the legal base for using the images, which is a combination of licence with general terms of use. The last part is the topic of discussion:

> Die Quelle `GeoBasis-DE/LGB (Jahr)/ [Titel des Datensatzes]` soll jeweils in das source=*-Tag der einzelnen Changesets aufgenommen werden.

Translates to "the source should be part of the source tag of the changeset".

Status quo: I do not understand how binding "should" is. I wish this would be clearer …

**Comment by andrewharvey** [comment]
> Translates to "the source should be part of the source tag of the changeset".

If that's part of the waiver the copyright holder agrees to, then I don't see an issue. It's just in general in OSM, if someone adds a feature with source=* or even attribution=*, someone else might come along later, delete the object and but retain some of the original information. So the original source was still used to derive some information but the source=* and attribution=* are lost. I don't think we should get into a situation where particular tags are legally enforced. Tags on the changeset comment are a bit different though because they are immutable.

**Comment by Strubbl** [comment]
Hello @tordans,
since the move to ELI stalled, can we please pick this PR up again? It would be very helpful for iD user to not use Bing as a default. It would be nice, if this layer could also be the default in Brandenburg.

The topic started again with this forum thread: https://community.openstreetmap.org/t/vorsicht-bei-verwendung-von-bing-luftbildern-im-land-brandenburg/8591

**Comment by tordans** [comment]
@Strubbl I agree, it would be great to have this content in iD and other editors. I documented my understanding of the status quo above. I think a good next step would be if someone – maybe you – creates a new summary of what needs to be done; and then a suggestion of how to solve it. That would be a new start to discuss the details.
I personally will not find the time to go into this again; but can help with input since I looked at it twice already.

**Comment by Strubbl** [comment]
I have no idea how to do this, but i have created a new pull request with your work as a basis and updated the URL:  #1763. I am going to need help to get this merged.

**Pull request closed without merging**
