### PR TITLE
Poland: Outdated maps removal

### PR DESCRIPTION
**Pull request by Asteliks**
This PR is a result of months of checking which sources are still available and which we can use. In general the story goes as follows:  the data has been moved to the national system thus we no longer maintain it. Based on that I request that first the missing layers should be added from the national system (https://github.com/osmlab/editor-layer-index/pull/1063) and only then this PR can be merged as a form of clean up. As for the other sources highlighted by the [watchdog](https://rbuffat.github.io/eli_watchdog/) these still work / can be updated to work.

### CODE REVIEW

**Comment by Asteliks** [comment]
@rbuffat  check failed probably due to: https://github.com/osmlab/editor-layer-index/issues/1039?

**Comment by rbuffat** [comment]
Yes I think this is the reason that the tests fail. I hope that I will have time too look at it in the next days.

**Comment by rbuffat** [comment]
@Asteliks I hope I found a fix for https://github.com/osmlab/editor-layer-index/issues/1039. Would it be possible to rebase / merge the current gh-pages in your branch to test it?

**Comment by Asteliks** [comment]
@rbuffat seems to be working here

**Comment by rbuffat** [comment]
@Asteliks Thanks for making the effort and going through all the sources!

**Pull request merged**
