### PR TITLE
Czechia - IPR ortofoto

### PR DESCRIPTION
**Pull request by zbycz**
Hi,

I am adding Prague ortophoto imagery from IPR, who agreed to derive data for OSM.

see https://wiki.openstreetmap.org/wiki/Cs:WikiProjekt_%C4%8Cesko/freemap#Ortofotomapy_IPR_Praha

Thanks!

### CODE REVIEW

**Comment by tyrasd** [comment]
Thanks for the pull request!

But one of the imagery layers looks a bit broken. There seem to be vertical stripes (I've rotated the screenshot by 90 degrees to fit on github):

selection_022

**Comment by tyrasd** [comment]
//ping @zbycz: has this issue been fixed in the meantime?

**Comment by zbycz** [comment]
Thanks for the PING. I've just fixed the URL for the right one - both layers should be fine.

Btw, do you know how to guess the date of iD editor deployment to osm.org?

**Comment by tyrasd** [comment]
Works fine now. Thanks!

> Btw, do you know how to guess the date of iD editor deployment to osm.org?

Not really, but there hasn't been a [release](https://github.com/openstreetmap/iD/releases) in quite a while now, so maybe there will come one relatively soon. //cc @bhousel

**Comment by tyrasd** [comment]
@zbycz ps: the tile cache still seems to be a bit unstable: for me, many tiles of the `ortofoto last` layer error out. You can test it on https://osmlab.github.io/editor-layer-index/

selection_023

**Comment by bhousel** [comment]
> Btw, do you know how to guess the date of iD editor deployment to osm.org?

I'm wrapping up changes to the walkthrough, then I will give the translators some time to translate all of the new text strings.. So maybe 1-2 weeks?

**Comment by zbycz** [comment]
@bhousel cool - thank you! :-)

@tyrasd Thanks for the report - I have tweaked the cache a little and will investigate further. It wouldnt affect the URL.

**Comment by andree182** [comment]
Looks like the last ortophoto is somewhat out of date, any idea why?

http://www.geoportalpraha.cz/mapy-online - if I choose "orotofoto", it looks newer than "IPR ortofoto LAST (tmsproxy)" in iD.

**Comment by zbycz** [comment]
Hi @andree182 , it could be caused by caching feature at tmsproxy. I invalidated all caches, so now it should load new data.

**Comment by andree182** [comment]
Unfortunately, doesn't look that that was the issue... You can check e.g. in Chýně, Ecksteinova street - "IPR ortofoto LAST (tmsproxy)" shows some really old low-res ortophoto there. Low vegetation version appears to match the one from geoportal.

**Pull request merged**
