### PR TITLE
Check.py improvements

### PR DESCRIPTION
**Pull request by grischard**
Partially addresses #428 

Usage improvements:

* Show progress bar instead of dots
* Add -v argument to increase verbosity
* Colour output and better logging

Check improvements:

* Report embedded icons. Disembedding all icons would save 578.54 KB - worth it on a 1.71 MB file, I think!
* Check for missing license_url - see #439
* Check for wms/tms tokens in URLs - we've had some missing `{proj}` before.
* Check for either `default` or geometry polygon. Many layers have neither, and will never be shown.

### CODE REVIEW

**Comment by grischard** [comment]
The build is failing because of the missing geometries.

**Comment by grischard** [comment]
As part of this, I'll mark all the layers in `sources/world` as `default`. @bhousel I think that you intentionally blacklist many of these layers in iD, do you want to preemptively add them?

Heads up to @bryceco @simonpoole too.

**Comment by simonpoole** [comment]
@grischard we currently only use the default attribute in sorting, so likely no big impact. I'm not that convinced that it really has useful semantics, or if it is suppose to have them, then maybe they have to be spelled out more clearly.

**Comment by bhousel** [comment]
> as part of this, I'll mark all the layers in sources/world as default. @bhousel I think that you intentionally blacklist many of these layers in iD, do you want to preemptively add them?

I'm not sure what you mean by this?  I just did a search and I don't think iD is using the `default` property, so feel free to change it..

**Comment by grischard** [comment]
Ok, I think I'm happy with this and will merge it.

**Pull request merged**
