### PR TITLE
Update OrtoSat2023 imagery geometry (Portugal)

### PR DESCRIPTION
**Pull request by mikedld**

### CODE REVIEW

**Comment by grischard** [comment]
The detailed coastline needlessly takes up space, can you simplify it like shown in http://download.geofabrik.de/europe/portugal.html but presumably without the islands?

**Comment by mikedld** [comment]
I wasn't tracing the coastline, rather the actual limits of the imagery. Do you maybe want me to simplify all of it, not only the coast part?

**Comment by grischard** [comment]
In general I'd say anything that simplifies within 500 metres outside the imagery boundary is fine. Over the water you can just pull a very simple boundary with 3-4 points.

**Comment by mikedld** [comment]
Steps for the land part are about 4-5km so I'm not sure I can meet the 500m rule. Reduced the water boundary to 4 points now.

**Comment by matheusgomesms** [comment]
Looks great I believe, thank you (again) @mikedld!

For clarification: Portuguese government recently update their imagery to cover the whole country, not only the central part. So the layer is the same, with the update of the new geometry (covering whole continental part) and the name.

**Pull request merged**
