### PR TITLE
North Carolina imageries cleanup

### LINKED ISSUE #1348: [Watchdog] Imagery "Coastal Plain NC Orthoimagery 2020 (NDVI)": sources/north-america/us/nc/NC_Coastal_Plain_Orthoimagery2020_(NDVI).geojson broken
Watchdog failed for 5 consecutive days for:
"Coastal Plain NC Orthoimagery 2020 (NDVI)" -> [sources/north-america/us/nc/NC_Coastal_Plain_Orthoimagery2020_(NDVI).geojson](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/nc/NC_Coastal_Plain_Orthoimagery2020_(NDVI).geojson)

Reason:
Error: WMS -: Error: Could not parse XML.
Error: WMS 1.3.0: Error: Could not parse XML.
Error: WMS 1.1.1: Error: Could not parse XML.
Error: WMS 1.1.0: Error: Could not parse XML.
Error: WMS 1.0.0: Error: Could not parse XML.

CC contributors to this imagery:
@cicku

### PR DESCRIPTION
**Pull request by cicku**
1. Fix #1348 
2. Pulls in CIR imagery

### CODE REVIEW

**Comment by cicku** [comment]
```
  File "/home/runner/work/editor-layer-index/editor-layer-index/scripts/libeli/wmshelper.py", line 7, in <module>
    import regex
ModuleNotFoundError: No module named 'regex'
Error: Process completed with exit code 1.
```

Not my issue here.

**Comment by rbuffat** [comment]
Looks like a library is not installed. I will look into it!

**Comment by rbuffat** [comment]
@cicku should be fixed in https://github.com/osmlab/editor-layer-index/pull/1361 Sorry for that. Could you merge the current gh-pages branch in your branch or rebase?

**Comment by cicku** [comment]
Rebased now. Because I'm trying to add an icon to the repo, the check result can be ignored.

**Pull request merged**
