### PR TITLE
Add Rhode Island Aerial Photo

### PR DESCRIPTION
**Pull request by cicku**
For #1035.

I'd prefer putting the copyright clarification into a single page.

### CODE REVIEW

**Comment by cicku** [comment]
I also want to add a note that the latest imagery is from Spring 2021 but the website admin told me that they have no plan to enable WMS support.

The currently supported formats are: JSON, SOAP and WCS. Apparently there is no way to use them right now in iD.

**Comment by rbuffat** [comment]
> I also want to add a note that the latest imagery is from Spring 2021 but the website admin told me that they have no plan to enable WMS support.
> 
> The currently supported formats are: JSON, SOAP and WCS. Apparently, there is no way to use them right now in iD.

@cicku Sometimes the [ArcGIS JavaScript View](https://maps.edc.uri.edu/rigis/rest/services/IMG/RI_202009_RGB_3in_web/ImageServer) can be turned into a WMS source compatible format (Using ESRIs rest API):

```
...
"type": "wms",
"url": "https://maps.edc.uri.edu/rigis/rest/services/IMG/RI_202103_RGB_3in_web/ImageServer/exportImage?f=image&format=jpgpng&imageSR=3857&bboxSR=3857&bbox={bbox}&size={width},{height}&foo={proj}",
"available_projections": ["EPSG:3857"],
...
```

Some suggestions for the 2020 imagery:
* Maybe it would be better to use the year of the imagery in the id and to use latest, if the imagery is not always the latest
* The max zoom looks a bit low. There is a juptyter notebook to check zoom levels you might want to try out: https://mybinder.org/v2/gh/rbuffat/eli-helper/master?urlpath=apps%2F/check_minzoom.ipynb

The imagery seems not to be orthorectified. It might be worthwhile to put this information in the description.https://rigis-edc.opendata.arcgis.com/pages/2021-spring-imagery

>While these aerial photographs are very detailed (3-in pixel resolution), they are not traditionally orthorectified. Their horizontal accuracy may vary throughout the state. Potential users are encouraged to carefully evaluate the suitability of these images before use.

**Comment by cicku** [comment]
@rbuffat Thank you for the hints. I will definitely check it.

Meanwhile, is it possible, in the near future, to add a variable/field in the ELI, so iD will be able to alert user whether the imagery is orthorectified or not?

**Comment by rbuffat** [comment]
There is the valid-georeference property: https://github.com/osmlab/editor-layer-index/blob/gh-pages/schema.json#L196. But I do not know if iD uses this property or not.

**Comment by cicku** [comment]
I will update RI geojson soon again with updated information.

**Pull request merged**
