### PR TITLE
Add Gaza Strip imagery

### PR DESCRIPTION
**Pull request by pnorman**
I couldn't find a license for this imagery.

@pierzen @jgc31, do you happen to know?

### CODE REVIEW

**Comment by pierzen** [comment]
This image is used in task http://tasks.dev.hotosm.org/project/611 where Airbus DS / OSM-FR license is specified.

**Comment by pnorman** [comment]
Is there a public link for the license?

**Comment by pierzen** [comment]
@pnorman,  Specific license agreements  like Nextview and Airbus are integrated in the HOT Tasking Manager.  The Instruction panel links to the License panel.  

Airbus License link: http://tasks.dev.hotosm.org/license/6?redirect=%2Fproject%2F611.

**Comment by pnorman** [comment]
> @pnorman, Specific license agreements like Nextview and Airbus are integrated in the HOT Tasking Manager. The Instruction panel links to the License panel.

This link requires logging in. I can add it to a wiki page if needed

**Comment by pnorman** [comment]
@pierzen Is the license the text of the page http://tasks.dev.hotosm.org/license/6?redirect=%2Fproject%2F611 or at the URL mentioned on that page?

The latter would be a problem for both this index and the JOSM index since it's a time-limited license

**Comment by bhousel** [comment]
Can this be closed?  It does look like a 1 year license.

**Comment by bhousel** [comment]
Closing as stale

**Pull request closed without merging**
