### PR TITLE
Add rights of way tiles for GB

### PR DESCRIPTION
**Pull request by systemed**
These tiles are generated from the Open Government Licence data collated at rowmaps.com by Barry Cornelius.

### CODE REVIEW

**Comment by systemed** [comment]
Anything I can do to help get this merged?

**Comment by boothym** [comment]
Any chance Scotland could be removed from this polygon? AFAIK the ROW maps only cover England and Wales.

**Comment by grischard** [comment]
Yes, you can edit [the geojson](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/gb/LocalAuthorities_RightsOfWay.geojson) in josm or on geojson.io and submit it as a pull request here.

The geojson poly is way too detailed for the imagery boundary, and the many points over the sea, where there's no mapping, can be simplified.

**Comment by grischard** [comment]
Actually I did it in #1445

**Pull request merged**
