### PR TITLE
Update tiris.tirol.gv.at layers

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by simon04** [comment]
Good point. I added `min_zoom: 15`.

**Comment by Klumbumbus** [comment]
`"license_url": "https://www.tirol.gv.at/data/datenkatalog/geographie-und-planung/gelaende-tirol/",` doesn't really give much information. It seems a better link would be https://www.data.gv.at/katalog/dataset/0454f5f3-1d8c-464e-847d-541901eb021a

Is there an explizit permission to use these layers, as "Creative Commons Namensnennung 3.0 Österreich" is by default not compatible with OSM

(see also https://github.com/osmlab/editor-layer-index/pull/324)

**Comment by Klumbumbus** [comment]
The "license extensions" are even harder and seem impossible to reach regarding OSM use:
https://www.tirol.gv.at/data/nutzungsbedingungen/

> Der Lizenznehmer, der Daten aus dem Open Government Portal des Landes Tirol für seine Anwendungen bzw. Dienste verwendet, erklärt sich damit einverstanden, aktiv das Land Tirol unter  opendata@tirol.gv.at darüber zu informieren, wo diese Anwendungen bzw. Dienste aufzufinden sind.

**Comment by tyrasd** [comment]
AFAICR, there was some agreement between Tirol and OSM quite some time ago (maybe around 2012 or so). I can't find anything specific on the wiki, but "Land Tirol" is linked on https://wiki.openstreetmap.org/wiki/Contributors#Austria and even on http://www.openstreetmap.org/copyright

**Comment by Klumbumbus** [comment]
Was added to Contributors page without reference at https://wiki.openstreetmap.org/w/index.php?title=Contributors&diff=770091&oldid=768970
(Sadly we can't ask BorisC anymore.)

**Pull request merged**
