### PR TITLE
Fix NYS Ortho imagery link

### PR DESCRIPTION
**Pull request by cicku**

### CODE REVIEW

**Review by andrewharvey — APPROVED** [review]

**Review by andrewharvey — CHANGES_REQUESTED** [review]
I just tested and it seems both before and after URLs work. What was the reason for changing? https is preferred due to the privacy it affords.

**Comment by cicku** [comment]
Something interesting as the HTTPS didn’t allow access at the time I submitted the PR.

I’m going to close this one because it goes back online.

**Comment by cicku** [comment]
Sorry, I have to reopen the request.

image

**Comment by cicku** [comment]
As far as I can see in iD 2.19.6, the imagery is broken.

**Comment by cicku** [comment]
2.19.6 ships with a broken URL. I see that it had been fixed at f3cac66d354440d0062dfbe0a0bdece943720df8, so I'm going to close this again.

**Pull request closed without merging**
