### PR TITLE
Add Thuringia DOP20

### PR DESCRIPTION
**Pull request by coolultra1**
See also #2443 

Via Email, the responsible authority, the Thuringia Landesamt für Bodenmanagement und Geoinformation has confirmed me deriving data for OSM does not fall under usage under dl-de/by 2.0 under their assumption, as long as, when the imagery is shown in the editor, it's attributed correctly. (which is the case)

### CODE REVIEW

**Comment by coolultra1** [comment]
Failed check is to be ignored as file will be reachable once merged.

**Comment by arch0345** [comment]
Thanks for confirming with them, would you be able to upload a PDF of the email and list that as the license URL?

**Comment by coolultra1** [comment]
@arch0345 

I've put the mail correspondence into a wiki page and linked that as the license URL. Is it okay like this?

**Comment by arch0345** [comment]
Yes, that's fine

**Pull request merged**
