### PR TITLE
Update Belgian layers

### PR DESCRIPTION
**Pull request by jbelien**
Add category attribute + Make filenames consistent

### CODE REVIEW

**Comment by grischard** [comment]
Since iD only refreshes ELI on new releases, this means that the icon will be 404 until a new version comes out. I'd rather we keep the filename, or have two copies of the file to later delete BE_GRB_Flanders_TMS.png once a new version of iD comes out.

**Comment by jbelien** [comment]
@grischard True! I'll put the old icon back and delete it after iD next release!

**Comment by grischard** [comment]
Thank you @jbelien !

**Comment by jbelien** [comment]
@grischard My pleasure!

Do you know when will be the next release of iD ?
So I can put that date in my agenda to clean the ELI 😋

**Comment by Klumbumbus** [comment]
In JOSM we use historicphoto instead of photo if a newer version of the same source is available, see https://josm.openstreetmap.de/wiki/Maps#Documentation. There are 12 such differences of the category, see https://josm.openstreetmap.de/wiki/ImageryCompare.

````
* Different categories ('photo' != 'historicphoto'): [BE] URBIS 2015 aerial imagery - https://geoservices-urbis.irisnet.be/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=Urbis:Ortho2015&WIDTH={width}&HEIGHT={height}&CRS={proj}&STYLES=&BBOX={bbox}
* Different categories ('photo' != 'historicphoto'): [BE] URBIS 2014 aerial imagery - https://geoservices-urbis.irisnet.be/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=Urbis:Ortho2014&WIDTH={width}&HEIGHT={height}&CRS={proj}&STYLES=&BBOX={bbox}
* Different categories ('photo' != 'historicphoto'): [BE] URBIS 2009 aerial imagery - https://geoservices-urbis.irisnet.be/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=Urbis:Ortho2009&WIDTH={width}&HEIGHT={height}&CRS={proj}&STYLES=&BBOX={bbox}
* Different categories ('photo' != 'historicphoto'): [BE] URBIS 2016 aerial imagery - https://geoservices-urbis.irisnet.be/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=Urbis:Ortho2016&WIDTH={width}&HEIGHT={height}&CRS={proj}&STYLES=&BBOX={bbox}
* Different categories ('photo' != 'historicphoto'): [BE] SPW(allonie) 2015 aerial imagery - https://geoservices.wallonie.be/arcgis/services/IMAGERIE/ORTHO_2015/MapServer/WmsServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
* Different categories ('photo' != 'historicphoto'): [BE] SPW(allonie) 2012-2013 aerial imagery - https://geoservices.wallonie.be/arcgis/services/IMAGERIE/ORTHO_2012_2013/MapServer/WMSServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
* Different categories ('photo' != 'historicphoto'): [BE] URBIS 2018 aerial imagery - https://geoservices-urbis.irisnet.be/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=Urbis:Ortho2018&WIDTH={width}&HEIGHT={height}&CRS={proj}&STYLES=&BBOX={bbox}
* Different categories ('photo' != 'historicphoto'): [BE] URBIS 2012 aerial imagery - https://geoservices-urbis.irisnet.be/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=Urbis:Ortho2012&WIDTH={width}&HEIGHT={height}&CRS={proj}&STYLES=&BBOX={bbox}
* Different categories ('photo' != 'historicphoto'): [BE] SPW(allonie) 2016 aerial imagery - https://geoservices.wallonie.be/arcgis/services/IMAGERIE/ORTHO_2016/MapServer/WmsServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
* Different categories ('photo' != 'historicphoto'): [BE] URBIS 2017 aerial imagery - https://geoservices-urbis.irisnet.be/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=Urbis:Ortho2017&WIDTH={width}&HEIGHT={height}&CRS={proj}&STYLES=&BBOX={bbox}
* Different categories ('photo' != 'historicphoto'): [BE] SPW(allonie) 2009-2010 aerial imagery - https://geoservices.wallonie.be/arcgis/services/IMAGERIE/ORTHO_2009_2010/MapServer/WMSServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
* Different categories ('photo' != 'historicphoto'): [BE] AIV Flanders 2013-2015 aerial imagery 10cm - https://geoservices.informatievlaanderen.be/raadpleegdiensten/OGW/wms?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=OGWRGB13_15VL&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
````

**Comment by jbelien** [comment]
@Klumbumbus Oh, okay, sorry about that, I'll fix it ASAP!

**EDIT:** Fixed in #779

**Pull request merged**
