### PR TITLE
Fix south-america / Brazil / GeoPortal sources

### PR DESCRIPTION
**Pull request by rbuffat**
Fix the GeoPortal sources from south-america / Brazil
- Update WMS URLs
- Add missing available_projections attribute
- Add new 2019 orthophotos

@willemarcel If I'm not mistaken I believe you added the permissions in https://wiki.openstreetmap.org/wiki/Pt:GeoPortalDFBrasilia

Would it possible for you to confirm that the new aerial imagery (2016, 2017, 2018, and 2019) are also public domain? Also, in the wiki a "CODEPLAN orthophoto portal" is mentioned. I'm not really sure what this is.

### CODE REVIEW

**Comment by willemarcel** [comment]
@rbuffat I'm checking it and I'll get the confirmation soon.

**Comment by erickdeoliveiraleal** [comment]
Prezado Cidadão, Sr. Erick,

Em atenção a Manifestação nº  00390000039202113, que solicita informações acerca "... imagens disponíveis no site https://www.geoservicos1.segeth.df.gov.br/arcgis/rest/services
são de domínio público (sem licença de copyright) e se podem ser usados 
para derivar outros mapas", consultamos a área técnica no qual nos informou que todas as camadas de dados são públicas e sem licença de copyright. Enquanto que as camadas Raster (Imagens de Satélite) possuem licença de uso especificas que precisam ser respeitadas quando replicadas em outras fontes.
Colocamo-nos à disposição, para obter outros esclarecimentos, por meio do telefone 3214-4180 e 3214-4179 - serviço de informação e atendimento da SEDUH. 
Agradecemos sua participação. A participação social é uma atitude cidadã, ajuda o Governo e beneficia toda a sociedade civil. 
Atenciosamente,
Serviço de Informação ao Cidadão - SIC

**Comment by willemarcel** [comment]
Hi @rbuffat

As the answer received by @erickdeoliveiraleal was not clear about the image licenses, I decided to ask the government about that. The answer was that the Geoeye 2018 and the Pleiades 2017 are not public domain, but the 2016 and 2019 are.

**Comment by rbuffat** [comment]
@willemarcel @erickdeoliveiraleal Thanks a lot for your research. The imagery for 2017 and 2018 seems to already be included in the index, but the good thing was that the available_projections element was missing, thus the imagery was probably defunct anyway. 

Would it be possible also to update https://wiki.openstreetmap.org/wiki/Pt:GeoPortalDFBrasilia to include the new information?

**Pull request merged**
