### PR TITLE
Update of Argentina's National Geographic Institute base map and WMS

### PR DESCRIPTION
**Pull request by Zalitoar**
Update of base map (TMS) and WMS endpoint in JSON and XML files

### CODE REVIEW

**Comment by grischard** [comment]
Hello, thanks for the PR! Could you please commit your changes to https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/ar instead? The imagery.(geo)json files get compiled automatically.

**Comment by Zalitoar** [comment]
Thanks for your comment @grischard, to be sure... Should I delete this PR and make a new one modifying the correct files?

**Comment by grischard** [comment]
Hi Gonzalo, happy new year! You can push more commits to the gh-pages branch on osm-ar/editor-layer-index and this PR should be updated automatically.

**Comment by Zalitoar** [comment]
Thanks and happy new year!

**Comment by grischard** [comment]
Hi @Zalitoar, I'd be happy to merge this if you changed the source files at https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/ar instead of the compiled files.

**Comment by Zalitoar** [comment]
I'll update my fork for work in the last version, then I'll modify the geojson files in https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/south-america/ar and at last I will make another pull request. I'm closing this PR. Thanks!

**Pull request closed without merging**
