### PR TITLE
Maa-amet layer addition (Estonia), attempt 2

### PR DESCRIPTION
**Pull request by kallejre**
This pull request is virtually duplicate of request #817 which became unmergeable and @andrewharvey suggested to open new one instead of rebasing old PR.

Insights to this PR: fixes, improves and optimizes 6 previously existing Estonian map layers (hence 18 000 deleted lines) and adds 17 new layers, featuring 8 historic maps/orthophotos. For more information about contents, visit PR #817. Currently there are issues with WMS server providing historical maps for years 1899 and 1935 and therefore two layers may appear pale white.

### CODE REVIEW

**Comment by andrewharvey** [comment]
> The licensee undertakes to remove the reference to the origin of the data in its products or services in writing by the licensor
on request.

Is this going to be an issue?

Apart from that the license seems to be quite open, just the above clause and attribution.

**Comment by kallejre** [comment]
No, i don't think it's going to be problem, because license with similar clause (from Maa-amet) has been used for OSM mapping for almost 9 years (+2 years with less refined license). However, there are few possible issues with merging this request. 
A) I edited check.py to add support for {wkid} in addition to {proj}. Was it allowed?
B) ~I started this pull request about half year ago. About that time Maa-amet data underwent reorganization due to merging different map applications. Before merging, all sources should be double-checked if they still work.~ I checked all layers and they produce expected result. However cadastral2 and TallinnLV maps might not hold up to quality expected by end users?
C) Also Travis complained about missing `style=` in wms URL. Should it be added before merging?

**Comment by Asteliks** [comment]
Hi this PR seems to be waiting for quite a while now dead in the water. What do we want to do with it?

**Comment by iandees** [comment]
Looks like this has a merge conflict. I'm going to close it out for now. If it's still useful, please resolve merge conflicts, push up to your branch, and leave a comment.

**Pull request closed without merging**
