### PR TITLE
Add MassGIS 2021 orthoimagery

### PR DESCRIPTION
**Pull request by gdt**
The 2019 entry was used as a starting point; the layer basically
differs from 2019 only in URL and capture date.

The licensing and privacy policies are the same as the 2019 imagery, which has already been checked/approved.

### CODE REVIEW

**Comment by cicku** [comment]
Sorry you are late on this one (1 hour approx.).

https://github.com/osmlab/editor-layer-index/commit/6aea8f03fb6dffe70b0cbc11366cd3c7e5d18438

**Comment by gdt** [comment]
Thanks - I will submit a fixup pull request as your version is missing some metadata and doesn't follow the naming scheme used by the previous imagery -- this is newer imagery but the same upstream source and workflow.

**Comment by cicku** [comment]
Sure. But I don't think there is any naming scheme we need to follow here.

**Comment by gdt** [comment]
Not any ELI doctrine, but people in MA are used to how we have been naming MassGIS layers and having the name mostly match except for they year will lead them to the obvious, correct, conclusion.    I should note that MassGIS themselves are not super consistent with their URL fragment names.

**Pull request closed without merging**
