### PR TITLE
Update geometries for north-america / us / tx

### PR DESCRIPTION
**Pull request by rbuffat**
Use geometries provided by data.tnris.org
See https://github.com/osmlab/editor-layer-index/pull/921#issuecomment-698557224

### CODE REVIEW

**Comment by rbuffat** [comment]
The test fails as the requests library is unable to check https://data.tnris.org/collection. I'm still not sure why. However, the links work in the browser.

**Comment by gdt** [comment]
I looked at the travis report and grabbed the URL.   I can open it fine in firefox, but when using "wget" I get a 404.  I wonder if the site behaves differently based on user agent, or something like that.

**Review by andrewharvey — APPROVED** [review]
based on what @gdt pointed out I think this is fine to fail

**Comment by rbuffat** [comment]
Thanks @andrewharvey!

**Pull request merged**
