### PR TITLE
Remove south-america/Brazil entries that are broken for a long time

### PR DESCRIPTION
**Pull request by rbuffat**

### CODE REVIEW

**Comment by matheusgomesms** [comment]
Hi René,

I talked to the Brazilian community (Telegram) and it seems they are still interested on those layers.

I did some research and we could actually save most of them:

Aglomerado Rural Isolado: updated
Pista de Pouso: off
Rios Drenagem: yes (perhaps same data but with different link)
Rodoviário: updated
Terra Indígena: updated
Unidade de Uso Sustentável: updated
Vila: updated

Regarding Londrina, they still have the same imagery but on an updated link. I couldn't make it work neither on iD nor JOSM, but you can [have a look on them](https://geo.londrina.pr.gov.br/server/rest/services/Imagens/OrtofotoCopel2011/MapServer/).

Finally, about Rio, they actually [have more updated imagery](https://pgeo3.rio.rj.gov.br/arcgis/rest/services/Imagens) (up to 2019), so I would say to deprecate 2013 and add 2019.

I submitted PR #1236 with those fixes.

Best,
Matheus

**Comment by rbuffat** [comment]
@matheusgomesms Thank you for looking into this. This is much appreciated!

Would it be possible for you to split your PR into multiple separated by source: IBGE, Rio, Londrina?

> Regarding Londrina, they still have the same imagery but on an updated link. I couldn't make it work neither on iD nor JOSM, but you can [have a look on them](https://geo.londrina.pr.gov.br/server/rest/services/Imagens/OrtofotoCopel2011/MapServer/).

The server seems to support WMTS, which should be supported by JOSM. But as some editors do not support WMTS and the WMTS server seems to support the GoogleMapsCompatible TileMatrixSet, it should be possible to encode it as tms. I will look into this.

**Comment by rbuffat** [comment]
This should work (but not tested):

```
...
"url": "https://geo.londrina.pr.gov.br/server/rest/services/Imagens/OrtofotoCopel2011/MapServer/WMTS/tile/1.0.0/Imagens_OrtofotoCopel2011/default/GoogleMapsCompatible/{zoom}/{y}/{x}",
"type": "tms",
...
```

**Comment by matheusgomesms** [comment]
> Would it be possible for you to split your PR into multiple separated by source: IBGE, Rio, Londrina?

Sure! Just give me some time, and I'll do that (and improve those files, like adding missing permissions and so on). Probably in next weekend I'll take a look.

> This should work (but not tested):

This is very odd. When you sent this, still didn't work. However, today it worked on iD, but didn't on JOSM (neither the TMS you sent nor the original WMTS). Perhaps there's some kind of block?

**Comment by rbuffat** [comment]
> Sure! Just give me some time, and I'll do that (and improve those files, like adding missing permissions and so on). Probably in next weekend I'll take a look.

No worries, there is no rush! Feel free to ask any questions.

**Pull request closed without merging**
