### PR TITLE
Update and rename itu-lotes to SP_Itu_-_Lotes

### PR DESCRIPTION
**Pull request by IgorEliezer**
Hello,

We're committing a new geojson for this city (ref #835). Please review and tell us if something is missing or not working.

Regards,

### CODE REVIEW

**Comment by IgorEliezer** [comment]
Any issues with the PR?

**Review by andrewharvey — CHANGES_REQUESTED** [review]
hi by convention we use the .geojson extension could you please update the filename?

**Comment by andrewharvey** [comment]
could you please also include a link to the licensing information and any other context for the license so we can check that it is okay to use in OSM?

**Comment by IgorEliezer** [comment]
> could you please update the filename?

Done.

> could you please also include a link to the licensing information

The license is the same of the original file here https://github.com/osmlab/editor-layer-index/pull/835.

` "license_url": "http://www.addressforall.org",`

AddressForAll (http://addressforall.org/ and https://github.com/AddressForAll/) is a NGO which receives geographic data from several city halls and survey institutions.

**Comment by andrewharvey** [comment]
Ok, a bit more detail in the FAQ (translated)

> Yes. For each data received, a license is associated. The Brazilian information access law guarantees that data produced by public authorities in Brazil must be open. This law is remembered in each case that applies and if, if you have a different license, the description of this license is available at a link. All the fruit of the Institute's work, when it treats or improves data, is under a free license (CC0).

And then in the Dados section (translated)

> When AddressForAll receives data, it starts by checking the license of these data (looking for data with open license (CC0) or CCBYSA or Odbl.

CC0 or public domain is okay, Odbl should be okay, CCBYSA is not compatible https://wiki.osmfoundation.org/wiki/Licence/Licence_Compatibility#Licences_that_are_not_compatible_with_the_.22Produced_Work.22_concept_of_the_ODbL

I'm reluctant to include this, or continue to include this source unless we can confirm which parts of the AddressForAll collection are CC0 and Odbl to ensure we're not tainting the database with incompatible CCBYSA data.

**Comment by IgorEliezer** [comment]
We've got the permission. We'll make the permission in digital file available along this week.

**Comment by andrewharvey** [comment]
> We've got the permission. We'll make the permission in digital file available along this week.

Great if you could post back with further details when you can, then I can take a look.

**Comment by IgorEliezer** [comment]
Hello,

We planned to get our [API/Metadata server](http://addressforall.org/dados) with the licensing permissions for public access working earlier. Since it's taking longer than expected, I'll post here the permission manually to advance the PR review.

Here's the email from the cityhall with their permission: [link](https://drive.google.com/file/d/14FcBM_4hcNIEX9HMYPgYA8mD9a-PVMId/view?usp=sharing) (in Portuguse)

Translation in chronological order:

<details> 
  <summary>**Emails between us and the cityhall (click to expand)**</summary>

-----

2020-09-17 12:49, Thierry Jean wrote:

Dear colleague,

Thank you for making geographic data from the city hall available for OpenStreetMap, AddressForAll and others.

One of our goals is to provide security for users of this data that they are effectively in the public domain.

To this end, we suggest responding to this email with "agreement" for the following statement:	

===================//===================

Considering that Brazilian governmental institutions produce, among others, non-confidential data and content of interest to the citizen, these are indicated as public domain in accordance with current legislation.

The data and content mentioned, therefore, are free from legal restrictions and the AddressForAll Institute, the OpenStreetMap Foundation and the Wikimedia Foundation, other entities, universities, companies and individuals, may reproduce, transform, distribute and present this data to the public, without the need to request authorization.

RELEVANT LEGISLATION
Brazil has been a signatory to the Berne Treaty since 1975 (Federal Decree No. 75,699), in which article 2.4, which provides for the exclusion of automatic protection of copyright in normative works, was regulated by Federal Law 9,610 of Copyright in 1998:
Art. 8 The following are not protected by copyright as dealt with in this Law:
I - ideas, normative procedures, systems, methods, projects or mathematical concepts as such;
(...)
IV - the texts of treaties or conventions, laws, decrees, regulations, judicial decisions and other official acts;

In other words, normative works produced by governmental authorities are free and, therefore, are in the public domain. In addition, when a work that falls under item IV (laws, decrees, etc.) presents objects such as attachments (with tables, maps, etc.) or cites objects from item I (normative procedure, etc.), these objects are also in the public domain, according to the principle of Art. 3 of the 1942 Introduction Law, "No one excuses himself from complying with the law, claiming he does not know it". For example, maps and tables attached to the laws of the Municipal Master Plans are also in the public domain and, consequently, excluded from copyright protection, as they are cited by said laws and necessary to comply with them.

All of this is reinforced by the Federal Constitution of 1988, which in its articles 5 and 216 guarantees citizens access to information generated by the public administration:

Art. 5 All are equal before the law, (...), in the following terms:
(...)
XIV - access to information is guaranteed to all and confidentiality of the source is safeguarded, when necessary for professional practice;
Art. 216. Goods of material and immaterial nature are constituted in Brazilian cultural heritage (...) bearers of reference to the identity, to the action, to the memory of the different groups that form Brazilian society (...):
(...)
§ 2 The public administration, under the terms of the law, is responsible for the management of governmental documentation and the measures to open its consultation to all who need it.

Such clauses of the Constitution received comprehensive regulation by the Access to Information Act of 2011, including the regulation of the guidelines of the public administration, which foresees, according to article 3, item II, the “disclosure of information of public interest, regardless of requests”.

Yet, the Access to Information Act, in its article 7, item II, paragraph 3, guarantees the right of access to documents and information contained therein used in decision making and administrative act. This means, for example, that a cadastral map used as a subsidy for the drafting of a land use act is also freely accessible, even if the cadastral map itself has not become part of the act.

===================//===================

For simplicity, we recommend cityhalls to adopt the good practice of dedicating their data to the Public Domain by the CC0 license (https://creativecommons.org/publicdomain/zero/1.0/deed.pt_BR ) on the site.

Sincerely,

Thierry Jean


-------

2020-09-28 11:23, Thierry Jean wrote:

Elisabete and Cristiam, 

Did you receive this email?

Thierry Jean


-------

2020-09-29 08:34, Elisabete Maia wrote:

Good Morning!!

Thierry,

We agree with the publication of the spatial data provided by the Touristic Municipality of Itu, for the collaborative platform Open Street Map.

Yours,

Elisabete Maia

--------

2020-09-30 19:49, Thierry Jean wrote:

Elisabete,

This answer is both excellent and bad!

In fact, the data we collect will automatically be made available to the OpenStreetMap project, which inspired us. However, the open address database created by us, will be used by many more individuals and companies. For this we need this data to be in the public domain: The CC0 license is the most suitable for this: https://creativecommons.org/publicdomain/zero/1.0/ 

The OSM license is called ODBL (https://en.wikipedia.org/wiki/Open_Database_License) and is much more restrictive because it forces the user to mention the source. Imagine, for example, that a public transport app like Moovit (https://moovit.com/) uses a base of addresses and has to mention each municipality in the 100 countries where they operate ...

So it would be better to reply to our email with a simple "agreement" without mentioning OpenStreetMap.

Hugs,

Thierry Jean


----- 

2020-10-01 14:29, Elisabete wrote (CC many cityhall email addresses *@itu.sp.gov.br):
Subject: Re: Confirmation that data received is in the public domain

good afternoon!

Agreed to use the databases provided!

yours,

Elisabete Maia

------

05-11-2020 10:51, Thierry Jean - AddressForAll wrote:

As per your request. Hugs.

Thierry Jean

</details>

**Comment by IgorEliezer** [comment]
Any update? The license is here https://github.com/osmlab/editor-layer-index/pull/928#issuecomment-727279047

If the permission is ok, I'll proceed to finish editing the geojson file.

**Comment by rbuffat** [comment]
@IgorEliezer Would it be possible to provide an English translation (E.g. using Google translate or deepl.com) or post the text of the email here?

**Comment by IgorEliezer** [comment]
> post the text of the email here?

It's under "Translation in chronological order: Emails between us and the cityhall (click to expand)" https://github.com/osmlab/editor-layer-index/pull/928#issuecomment-727279047

**Comment by IgorEliezer** [comment]
> > post the text of the email here?
> 
> It's under "Translation in chronological order: Emails between us and the cityhall (click to expand)" [#928 (comment)](https://github.com/osmlab/editor-layer-index/pull/928#issuecomment-727279047)

Any news?

**Comment by IgorEliezer** [comment]
Hi, I'm closing it in order to submit a new and updated file.

**Pull request closed without merging**
