### PR TITLE
Add Swedish imagery

### PR DESCRIPTION
**Pull request by NKAmapper**
This pull request will add 7 imagery sources for Sweden:

**From Trafikverket (the Swedish Transport Administration):**

1) Road network WMS overlay
2) Road network WMS overlay - extra features
3) Road network WMS endpoint overlay - even more extra features
4) Street names WMS overlay
5) Railway network WMS overlay
6) Railway network WMS endpoint overlay - extra features

The Trafikverket sources are licensed under CC0: [License](https://api.trafikinfo.trafikverket.se/Content/ContentDetails/58e384810bb22118e8041667)

**From Lantmäteriet (the Swedish Mapping, Cadastral and Land Registration Authority):**

7) Economic Map TMS - historic map

Lantmäteriet has chosen to forgo the copyright for the Economic map series: [Official statement](http://www.lantmateriet.se/en/Maps-and-geographic-information/Historical-Maps/)

#352 
#348 
#349

### CODE REVIEW

**Comment by grischard** [comment]
Fantastic, thank you!

**Comment by Klumbumbus** [comment]
Why did you use different names/projections/descriptions when adding to JOSM and ELI?
projections for TMS is not useful as it it always 3857.
from https://josm.openstreetmap.de/wiki/ImageryCompare:
````
* Name differs ('Trafikverket Railway Network options' != 'Trafikverket Railway Network options(overlay)'): http://geo-baninfo.trafikverket.se/mapservice/wms.axd/BanInfo?service=wms&request=getCapabilities
* Name differs ('Trafikverket Street Names' != 'Trafikverket Street Names (overlay)'): http://mapproxy.openstreetmap.se/tiles/1.0.0/nvdb_names/EPSG3857/{zoom}/{x}/{y}.png
* Name differs ('Trafikverket Railway Network' != 'Trafikverket Railway Network (overlay)'): http://geo-baninfo.trafikverket.se/mapservice/wms.axd/BanInfo?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=Spar_Huvud_och_sidospar&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
* Name differs ('Trafikverket Road Network' != 'Trafikverket Road Network (overlay)'): http://geo-netinfo.trafikverket.se/mapservice/wms.axd/NetInfo?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=Vagtrafiknat,Funkvagklass,Farjeled&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
* Name differs ('Trafikverket Road Network options' != 'Trafikverket Road Network options (overlay)'): http://geo-netinfo.trafikverket.se/mapservice/wms.axd/NetInfo?service=wms&request=getCapabilities
* Name differs ('Lantmäteriet Economic Map (historic)' != 'Economic Maps (historic)'): https://mapproxy.openstreetmap.se/tms/1.0.0/ek_EPSG3857/{zoom}/{x}/{-y}.jpeg
* Name differs ('Trafikverket Road Network extra' != 'Trafikverket Road Network extra (overlay)'): http://geo-netinfo.trafikverket.se/mapservice/wms.axd/NetInfo?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=VagnummerText,Vaghinder,Rastplats,Rastficka,Hallplats,Farthinder,BroTunnel,ATK_Matplats&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
* Description differs ('Swedish railway network with several options for map layers.' != 'Swedish railway network with several options for map layers'): [SE] Trafikverket Railway Network options(overlay) - http://geo-baninfo.trafikverket.se/mapservice/wms.axd/BanInfo?service=wms&request=getCapabilities
- Missing JOSM projections (EPSG:3857 EPSG:4326): [SE] Trafikverket Railway Network options(overlay) - http://geo-baninfo.trafikverket.se/mapservice/wms.axd/BanInfo?service=wms&request=getCapabilities
* Description differs ('Swedish NVDB street names.' != 'Swedish NVDB street names'): [SE] Trafikverket Street Names (overlay) - http://mapproxy.openstreetmap.se/tiles/1.0.0/nvdb_names/EPSG3857/{zoom}/{x}/{y}.png
- Missing JOSM projections (EPSG:3857): [SE] Trafikverket Street Names (overlay) - http://mapproxy.openstreetmap.se/tiles/1.0.0/nvdb_names/EPSG3857/{zoom}/{x}/{y}.png
* Description differs ('Swedish railway network, including sidings.' != 'Swedish railway network, including sidings'): [SE] Trafikverket Railway Network (overlay) - http://geo-baninfo.trafikverket.se/mapservice/wms.axd/BanInfo?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=Spar_Huvud_och_sidospar&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
* Projections differ ('EPSG:3857 EPSG:4326' != 'EPSG:3006 EPSG:3007 EPSG:3008 EPSG:3009 EPSG:3010 EPSG:3011 EPSG:3012 EPSG:3013 EPSG:3014 EPSG:3015 EPSG:3016 EPSG:3017 EPSG:3018 EPSG:3034 EPSG:3035 EPSG:3044 EPSG:3045 EPSG:3046 EPSG:3047 EPSG:3857 EPSG:4258 EPSG:4326 EPSG:4619'): [SE] Trafikverket Railway Network (overlay) - http://geo-baninfo.trafikverket.se/mapservice/wms.axd/BanInfo?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=Spar_Huvud_och_sidospar&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
* Description differs ('Swedish NVDB road network.' != 'Swedish NVDB road network'): [SE] Trafikverket Road Network (overlay) - http://geo-netinfo.trafikverket.se/mapservice/wms.axd/NetInfo?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=Vagtrafiknat,Funkvagklass,Farjeled&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
* Projections differ ('EPSG:3857 EPSG:4326' != 'EPSG:3006 EPSG:3007 EPSG:3008 EPSG:3009 EPSG:3010 EPSG:3011 EPSG:3012 EPSG:3013 EPSG:3014 EPSG:3015 EPSG:3016 EPSG:3017 EPSG:3018 EPSG:3034 EPSG:3035 EPSG:3044 EPSG:3045 EPSG:3046 EPSG:3047 EPSG:3857 EPSG:4258 EPSG:4326 EPSG:4619'): [SE] Trafikverket Road Network (overlay) - http://geo-netinfo.trafikverket.se/mapservice/wms.axd/NetInfo?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=Vagtrafiknat,Funkvagklass,Farjeled&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
* Description differs ('Swedish NVDB road network with several options for map layers.' != 'Swedish NVDB road network with several options for map layers'): [SE] Trafikverket Road Network options (overlay) - http://geo-netinfo.trafikverket.se/mapservice/wms.axd/NetInfo?service=wms&request=getCapabilities
- Missing JOSM projections (EPSG:3857 EPSG:4326): [SE] Trafikverket Road Network options (overlay) - http://geo-netinfo.trafikverket.se/mapservice/wms.axd/NetInfo?service=wms&request=getCapabilities
* Description differs ('Scan of ´Economic maps´ ca 1950-1980.' != 'Scan of ´Economic maps´ ca 1950-1980'): [SE] Economic Maps (historic) - https://mapproxy.openstreetmap.se/tms/1.0.0/ek_EPSG3857/{zoom}/{x}/{-y}.jpeg
- Missing JOSM projections (EPSG:3857): [SE] Economic Maps (historic) - https://mapproxy.openstreetmap.se/tms/1.0.0/ek_EPSG3857/{zoom}/{x}/{-y}.jpeg
* Projections differ ('EPSG:3857 EPSG:4326' != 'EPSG:3006 EPSG:3007 EPSG:3008 EPSG:3009 EPSG:3010 EPSG:3011 EPSG:3012 EPSG:3013 EPSG:3014 EPSG:3015 EPSG:3016 EPSG:3017 EPSG:3018 EPSG:3034 EPSG:3035 EPSG:3044 EPSG:3045 EPSG:3046 EPSG:3047 EPSG:3857 EPSG:4258 EPSG:4326 EPSG:4619'): [SE] Trafikverket Road Network extra (overlay) - http://geo-netinfo.trafikverket.se/mapservice/wms.axd/NetInfo?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=VagnummerText,Vaghinder,Rastplats,Rastficka,Hallplats,Farthinder,BroTunnel,ATK_Matplats&STYLES=&SRS={proj}&WIDTH={width}&HEIGHT={height}&BBOX={bbox}
````

**Comment by NKAmapper** [comment]
Because I only focused on getting the id identical ...

Names: The difference is mainly “overlay”. This is already evident from the section title in iD but not present in JOSM. The Economic Map names could have been the same - I have updated in JOSM now.

Description: I believe the difference is a dot only. Not deliberate.

Projections: I did not add all those projections, somebody else did (for JOSM).

**Comment by Klumbumbus** [comment]
>Names: The difference is mainly “overlay”. This is already evident from the section title in iD but not present in JOSM.

Ah, OK. There is an overlay flag in JOSM too since today. I added it to the entries in JOSM.

>Description: I believe the difference is a dot only. Not deliberate.

Do you know about the "tools" for easier copy pasting between JOSM and ELI? They are described also [here](https://josm.openstreetmap.de/wiki/ImageryCompare) (search for "For easier syncing")

**Comment by NKAmapper** [comment]
Thank you.
Apologies for an ignorant question, but are the projections in [Maps](https://josm.openstreetmap.de/wiki/Maps) actually used by JOSM?
JOSM seems to work nicely without them.

**Comment by Klumbumbus** [comment]
>Apologies for an ignorant question, but are the projections in Maps actually used by JOSM?
JOSM seems to work nicely without them.

If no projection is specified then JOSM uses the projection which is set in the preferences for the tile download. If the service doesn't provide tiles in this projection then this leads to an error and no tiles are displayed. If projections are specified and the set projection is not in the list then JOSM uses another one of the list and reprojects the tiles to the set projection.
Also sometimes the GetCapabilities lists projections, which do not work and/or projections work, which are not listed in the GetCapabilities.
So by defining the list of working projections ourself in the XML code the chances that you don't get tiles when you actually could are minimized.

**Pull request merged**
