### PR TITLE
Adding a second 'World Imagery (Clarity)' layer

### PR DESCRIPTION
**Pull request by jgravois**
[Esri World Imagery (Clarity)](http://www.arcgis.com/home/item.html?id=ab399b847323487dba26809bf11ea91a) - two for the price of one!

ref: https://github.com/osmlab/editor-layer-index/pull/358#issuecomment-359237579

### CODE REVIEW

**Comment by bhousel** [comment]
Awesome, thanks @jgravois 🙌

**Comment by simonpoole** [comment]
The imagery files were not regenerated in/after this PR.

**Comment by bhousel** [comment]
@simonpoole I think 9b52fb1 includes the regenerated files?
In any case, I just did a clean build and git tells me nothing changed.

**Comment by simonpoole** [comment]
Operator error on my behalf, sorry. The underlying issue is that we don't minimize the output of concatenating the sources in the repo, which forces an extra step for no good reason on consumers that need to be data size aware. I minimize with minimize-js (node), would it be acceptable to do that for the output files for the whole repo?

**Comment by bhousel** [comment]
> would it be acceptable to do that for the output files for the whole repo?

Sure, seems fine to me..

**Pull request merged**
