### PR TITLE
Add Hungarian FÖMI 2011-2014 orthophotos

### PR DESCRIPTION
**Pull request by Yogurt4**
The older one (FÖMI 2007-2010) will be made "category": "historicphoto" once it's available again.

### CODE REVIEW

**Comment by Yogurt4** [comment]
I don't want to be too pushy but I do want to inform you that with the (hopefully temporary) loss of the older FÖMI server, there is currently no country-wide, accurately georeferenced aerial imagery for Hungarian editors.

If anything is in the way of accepting this PR, please let me know.

**Comment by TomaszKozlowski-TomTom** [comment]
Hello! @grischard
As I see currently old FÖMI 2007-2010 data is not available in OSM and there is a need to update new one to be available in iD editor - new one is already available in JOSM. Could you act on that, so Hungarian database can be improved with local sources?

Thank You in advance!

**Comment by BathoryPeter** [comment]
I added the English translation of the license text (see [https://wiki.openstreetmap.org/wiki/Hungary/Ortofot%C3%B3k#F%C3%96MI_%28Lechner%29_ortofot%C3%B3k](https://wiki.openstreetmap.org/wiki/Hungary/Ortofotók#FÖMI_%28Lechner%29_ortofotók)).

**Comment by Yogurt4** [comment]
Is there anything preventing it to get merged?
For all Hungarian edits this layer should be used as THE reference.

**Comment by Yogurt4** [comment]
I've added an [Issue](https://github.com/osmlab/editor-layer-index/issues/2425) also.
However, I cannot link the PR with the issue.

**Pull request merged**
