### PR TITLE
Add more imageries in PA and NJ

### PR DESCRIPTION
**Pull request by cicku**
1. DVRPC 1-ft ortho 2020
2. Philly 3-in ortho 2020

### CODE REVIEW

**Comment by rbuffat** [comment]
@andrewharvey @grischard Could you have a quick look at https://www.opendataphilly.org/organization/about/city-of-philadelphia Especially the phrase "The City of Philadelphia reserves all rights in the GIS database and any data contained therein"

**Comment by cicku** [comment]
It is a little bit confusing here. I can ask PASDA director again on this.

The data is hosted at PASDA as well (I chose ESRI because it is faster), usually data hosted on PASDA are open to public use without restriction.

https://www.pasda.psu.edu/uci/DataSummary.aspx?dataset=2050

**Comment by rbuffat** [comment]
If possible it would be good if you could clarify this. I'm not familiar enough with the implications of this sentence.

**Comment by cicku** [comment]
They finally replied my email and told me to wait until next Wednesday. Let's see if there is any good news.

**Comment by cicku** [comment]
Confirmed that it is public domain.

image

**Pull request merged**
