### PR TITLE
Update BE_OrthoPhoto2017_Brussels_WMS.geojson

### PR DESCRIPTION
**Pull request by jbelien**
Switch to TMS to be available in iD editor

### CODE REVIEW

**Comment by jbelien** [comment]
See #363 comments for more details about this update ! :)

**Comment by bhousel** [comment]
Cool @jbelien this is great!.. 

Do you mind if I hold of merging this for a few days?  I was looking through the sources and it looks like a lot of WMS sources are already specified as supporting EPSG:3857.  I think I can add a quick change on the iD side to just support these sources directly without using the proxy, then they can stay as WMS sources in the index and we don't need to change anything.

(Your comment about the url path was really helpful)

**Comment by jbelien** [comment]
Awesome ! I do not mind at all ! :)

Really happy to help !
Tell me if I can do anything else !

**Comment by simonpoole** [comment]
Having the TMS sources is still positive for other editors and applications that don't support WMS servers and are not going to implement workarounds as @bhousel is thinking of, any time soon (for numerous reasons). 

Unluckily the current format of the index requires duplicating the entry for this which is not beautiful, but on the other hand really not a lot of work.

**Comment by jbelien** [comment]
Any news on this merge ? :)

**Comment by jbelien** [comment]
Any news on this merge ? :)

**Comment by jbelien** [comment]
Poke @bhousel

**Comment by jbelien** [comment]
Could this PR be merged please ? :)

**Comment by tyrasd** [comment]
@bhousel what's the current status regarding https://github.com/openstreetmap/iD/issues/1141?

**Comment by bhousel** [comment]
I'm really sorry for dropping the ball on this - I don't have time now to work on openstreetmap/iD#1141, so let's just merge this as-is.

**Pull request merged**
