### PR TITLE
Added new orthophotos, corrected the other old ones

### PR DESCRIPTION
**Pull request by Oni-DOS**
Hello guys again, i changed the name of the existent files, Orthophoto instead of Ortophoto, that's my mistake. :D Added new (well, they technically are old, but they will be important to OSM contributors) orthophotos. :)

### CODE REVIEW

**Comment by cicku** [comment]
I don’t think of any value hosting 2006/2007 imageries in 2021.

**Comment by Oni-DOS** [comment]
> I don’t think of any value hosting 2006/2007 imageries in 2021.

2006 imagery is tagged as historicalphoto, and it can be helpful in some areas, for example there are some objects on this imagery which were in construction and can be drawed more qualitative.
This 2007 imagery is still used by the national cadastral agency (you can see it on cadastru.md/ecadastru but only on IPs from Moldova) because there are some areas that were not photographed in 2016 and 2020 (thanks to the separatists from the left bank of the Dniestre), these imageries are ortorectified and are more great and precise than Bing, Maxar or Esri.

**Comment by Oni-DOS** [comment]
Hey guys what's up with pull requests? Is anybody here?

**Comment by rbuffat** [comment]
@Oni-DOS I try to look at it over the weekend. Would it be possible to merge the current gh-pages branch in your PR?

**Comment by Oni-DOS** [comment]
@rbuffat thanks for your response! If I understand you correct, you mean to leave the old objects (2016, 2016 reserve and 2019 imagery) from the folder europe/md as they were before this PR?

**Comment by rbuffat** [comment]
@Oni-DOS There are conflicting files with the current gh-pages branch. If you could merge them would be great, otherwise, I will have a look at it.

**Comment by Oni-DOS** [comment]
I only renamed these 3 conflicting files, they are not removed. At this version they looks more great, at least I think so. I think that it would be very nice if you will add these orthophotos to the Editor Layer Index. Thanks again for the response!

**Comment by andrewharvey** [comment]
> I don’t think of any value hosting 2006/2007 imageries in 2021.

I agree with keeping older imagery, they can be useful:

- certain current day features are more clear on a particular imagery set
- As Oni-DOS mentions features under construction may be easier to trace during the construction period
- can be useful for `start_date` tags
- useful to understand historical edits to see why/how the mapper made a past change

Still, the branch has conflicts, and those must be resolved before we can merge @Oni-DOS can you try to resolve these with the Resolve conflicts button?

**Comment by Oni-DOS** [comment]
> > I don’t think of any value hosting 2006/2007 imageries in 2021.
> 
> I agree with keeping older imagery, they can be useful:
> 
> * certain current day features are more clear on a particular imagery set
> * As Oni-DOS mentions features under construction may be easier to trace during the construction period
> * can be useful for `start_date` tags
> * useful to understand historical edits to see why/how the mapper made a past change
> 
> Still, the branch has conflicts, and those must be resolved before we can merge @Oni-DOS can you try to resolve these with the Resolve conflicts button?

Hello, and thanks for your reply! I can't press the Resolve conflicts button, it says that these conflicts are too complex to resolve in the web editor, and that only those with write access to this repository can merge pull requests. Are there other ways to resolve this conflict?

**Comment by andrewharvey** [comment]
> Hello, and thanks for your reply! I can't press the Resolve conflicts button, it says that these conflicts are too complex to resolve in the web editor, and that only those with write access to this repository can merge pull requests. Are there other ways to resolve this conflict?

You can do it on your local machine if you're confident with Git by rebasing against the upstream gh-pages, otherwise it might be easier to open a new PR.

**Comment by rbuffat** [comment]
@Oni-DOS Sorry for not having time last weekend. I had now a look at the license information regarding the new imagery in this PR. I'm a bit worried as for most there is only mention of "non-commercial" use. @kathleenlu09 or @simonpoole, if you have time, could you have a look at these license terms?

**sources/europe/md/Orthophoto_2006_Chisinau.geojson**
http://geoportalinds.gov.md/geonetwork/srv/eng/catalog.search#/metadata/a959bbff-0489-4985-92ee-5e74b583cd8e

> Spatial data is provided free of charge for viewing through network services and the data provided is for information purposes only. The use of spatial data is permitted without restriction for any non-commercial purpose.
> 
> Public access - free for non-commercial use.


**sources/europe/md/Orthophoto_2007_Moldova.geojson**
http://geoportalinds.gov.md/geonetwork/srv/eng/catalog.search#/metadata/4bdb8b36-0964-4e46-b397-46ef5980ef1b

> Spatial data are provided free of charge for any non-commercial purpose and for their use for the purpose of creating, by derivative, their own cartographic and GIS products, indicating the source and initial materials used. In case of reuse of spatial data for commercial purposes, as a component part of the final product, the user is obliged to contact the Land Relations and Cadastre Agency to obtain admission and use, in accordance with point 2 of Government Decision no. 254/2018.
> 
> Access to the network service for public purposes is unrestricted.


**sources/europe/md/Orthophoto_2011_Chisinau.geojson**
http://geoportalinds.gov.md/geonetwork/srv/eng/catalog.search#/metadata/a959bbff-0489-4985-92ee-5e74b583cd8e

> Spatial data are provided free of charge for any non-commercial purpose and for their use for the purpose of creating, by derivative, their own cartographic and GIS products, indicating the source and initial materials used. In case of reuse of spatial data for commercial purposes, as a component part of the final product, the user is obliged to contact the Land Relations and Cadastre Agency to obtain admission and use, in accordance with point 2 of Government Decision no. 254/2018.
> 
> Access to the network service for public purposes is unrestricted.

**sources/europe/md/Orthophoto_2014_Chisinau.geojson**
http://geoportalinds.gov.md/geonetwork/srv/eng/catalog.search#/metadata/a959bbff-0489-4985-92ee-5e74b583cd8e

> Spatial data is provided free of charge for viewing through network services and the data provided is for information purposes only. The use of spatial data is permitted without restriction for any non-commercial purpose.
> 
> Public access - free for non-commercial use.

**sources/europe/md/Orthophoto_2016_Moldova_Extended.geojson**
http://geoportalinds.gov.md/geonetwork/srv/eng/catalog.search#/metadata/e3bfccb6-259a-4753-bb56-545d277f9bc3

> Spatial data are provided free of charge for any non-commercial purpose and for their use for the purpose of creating, by derivative, their own cartographic and GIS products, indicating the source and initial materials used. In case of reuse of spatial data for commercial purposes, as a component part of the final product, the user is obliged to contact the Land Relations and Cadastre Agency to obtain admission and use, in accordance with point 2 of Government Decision no. 254/2018.
> 
> Access to the network service for public purposes is unrestricted.

**Comment by Oni-DOS** [comment]
I will make a new pull request, maybe this will solve the problem

**Comment by andrewharvey** [comment]
@Oni-DOS could you provide further documentation around why this imagery can be used given the non-commercial conditions @rbuffat points out.

**Comment by Oni-DOS** [comment]
> @Oni-DOS could you provide further documentation around why this imagery can be used given the non-commercial conditions @rbuffat points out.

Well, there are no documentations where it's wrote that these imagery can be used in iD/JOSM (or OSM in general). But when  considered non-commercial it means that these imagery can be used in open-source and non-profit projects like OSM.

**Comment by cicku** [comment]
Is the interpretation official? If the purpose is to prevent selling free data, it is probably fine. Otherwise, still unclear.

**Pull request closed without merging**
