### PR TITLE
improve naming of pl/Geoportal 2 "high res" imagery

### PR DESCRIPTION
**Pull request by tyrasd**
This was split of from #1326, as this should be discussed and decided by the Polish community (see https://github.com/osmlab/editor-layer-index/pull/1326#issuecomment-962191576):

> Regarding the name issue, I think ultimately it would be best if the Polish community can decide on this.

@Asteliks can you perhaps coordinate this?

### CODE REVIEW

**Comment by Asteliks** [comment]
Every Friday the Polish community has a meeting on discord. I’ll do my best to attend today if I manage to finish my work

**Comment by matkoniecz** [comment]
I created https://forum.openstreetmap.org/viewtopic.php?pid=847077#p847077 that has wider audience

**Comment by matkoniecz** [comment]
And in general outcome was that there was no real support for what I proposed.

So while I still think it would be a good idea, this is clearly not shared by others.

**Comment by tyrasd** [comment]
@matkoniecz So the PR can be merged as is, right?

**Comment by matkoniecz** [comment]
yes

**Comment by rbuffat** [comment]
@matkoniecz @Asteliks Thank you for taking the time and effort to discuss this issue and come to a conclusion! ❤️

**Comment by Asteliks** [comment]
To be honest @matkoniecz did most of the work. I just reminded everyone about this topic something like last week. Thanks @matkoniecz for driving this all the way to the end!

**Pull request merged**
