### PR TITLE
Add MassGIS LIDAR Shaded Relief

### PR DESCRIPTION
**Pull request by gdt**
Add MassGIS LIDAR Shaded Relief

This is a TMS layer which instead of having a photograph is based on a a LIDAR DEM and hillshading.   One can see stone walls, streams, etc.

### CODE REVIEW

**Comment by gdt** [comment]
Not sure why checks haven't run.  I can close and resubmit if you want.  I did paste the geojson into the tester page and it seemed good.

**Comment by rbuffat** [comment]
@gdt Travis seems to have stopped working and we switched yesterday to a new github action to replace travis. If you could merge the current gh-pages into your branch the tests should run again. Theoretically, I should also be able to merge gh-pages into your branch, but I need yet to figure out how exactly.

**Comment by gdt** [comment]
Thanks - I have rebased my commit and force pushed, and I see that not only did the checks run but I have a happy green checkmark.

Something odd happened, which is a commit was autogenerated to deploy things.  That started a new  check that didn't really check, but I did see the success report on the first round.   (I get it that this is not about my change.)

**Comment by gdt** [comment]
Now I understand -- the check is still there on the commits view, and the second commit is the build/merge to the main files, so all is likely as intended.

**Comment by rbuffat** [comment]
@gdt Yep, that deploy should not have happen. Thanks for pointing this out, I will look into it.

For this PR this should not be that relevant, as these files will be newly created once the PR is merged . What has happened is that the merge pushed to your repository, which activated the new action to deploy changes of the imagery.* files to your gh-pages branch. As your feature branch happens to be gh-pages, they ended in this PR.  It's probably best to limit the deploy only to this repository.

**Comment by rbuffat** [comment]
> Since MassGIS data is paid for by public tax dollars, the data are in the public domain and therefore can be used by anyone for any purpose. When using MassGIS data on maps or in digital applications, source credit should be stated as "MassGIS (Bureau of Geographic Information), Commonwealth of Massachusetts EOTSS"

https://www.mass.gov/service-details/massgis-frequently-asked-questions

Should we change the attribution text from "MassGIS LIDAR" to "MassGIS (Bureau of Geographic Information), Commonwealth of Massachusetts EOTSS".  @gdt What is your opinion on this?

**Comment by gdt** [comment]
My opinion is that for nerds, MassGIS is suffiicent, and they would like the full form on printed maps that the public and especially government people are going to see.   I see that as the formal legal name vs the "doing business as" name.  We've been using "MassGIS L3 Parcels" as shorthand and I think that's socially comfortable.    Also note that this attribution is a politeness issue, as this data is said to be truly PD.   I do think it's good to name the layer in changesets, which is why I put LIDAR in the attribution text.

**Comment by gdt** [comment]
Example page where the "MassGIS" branding is very loud compared to the formal name:  https://www.mass.gov/service-details/about-massgis

**Comment by rbuffat** [comment]
@gdt Then let's stick to just MassGIS LIDAR. Thanks for the PR and sorry for the inconvenience regarding the tests / deploy. This should hopefully be fixed now.

**Pull request merged**
