### PR TITLE
Adding Cadastral Surveying layer from Bern, Switzerland

### PR DESCRIPTION
**Pull request by habi**
From https://opendata.swiss/en/dataset/amtliche-vermessung-farbig-wmts, with help from http://lists.openstreetmap.ch/mailman/listinfo/talk-ch

### CODE REVIEW

**Comment by habi** [comment]
Mersibien!

**Comment by Klumbumbus** [comment]
The Terms of use of "BY" at https://opendata.swiss/en/terms-of-use/ require: "You must provide the source (author, title and link to the dataset)." This is not compatible with OSM. It would require an explizit permission from the provider or an confimation that mention on https://wiki.openstreetmap.org/wiki/Contributors is sufficient.

**Comment by simonpoole** [comment]
The other problem with this is that I believe only JOSM supports WMTS endpoints, so an actual TMS url would be far better in EPSG:3857 (this should be possible to deduce from the URLs generated by QGIS or JOSM). Not to mention that using a WMTS endpoint for exactly one layer doesn't make sense for JOSM either.

PS: it seems as if the WMTS server doesn't actually support either EPSF:3857 or EPSG:4326 so my complaint is mostly moot.

**Comment by habi** [comment]
As can be seen in the first commit of this PR (https://github.com/osmlab/editor-layer-index/commit/9e8fa8cfd631a412292efc615189584ba7d4516f) we have the explicit permission to use this layer for updating OSM from the head of the office of  'Geoinformation Bern’ via email.

**Comment by Klumbumbus** [comment]
OK, great.

**Comment by habi** [comment]
> The other problem with this is that I believe only JOSM supports WMTS endpoints, so an actual TMS url would be far better in EPSG:3857 (this should be possible to deduce from the URLs generated by QGIS or JOSM). Not to mention that using a WMTS endpoint for exactly one layer doesn't make sense for JOSM either.
> 
> PS: it seems as if the WMTS server doesn't actually support either EPSF:3857 or EPSG:4326 so my complaint is mostly moot.

This actually stems from the earliest communication regarding this layer. It was suggested (by you :) ) that I submit this here.
I've been using the layer in JOSM and wasn't really aware that this repository here ist not per default used by JOSM...

**Comment by simonpoole** [comment]
> This actually stems from the earliest communication regarding this layer. It was suggested (by you :) ) that I submit this here.
> I've been using the layer in JOSM and wasn't really aware that this repository here ist not per default used by JOSM...

That's not the problem, the way the layer is provided by Berne is technically incompatible with most editors. The solution to that would be proxying (that is reprojecting and caching) it through the SOSM mapproxy instance.

**Comment by habi** [comment]
> The solution to that would be proxying (that is reprojecting and caching) it through the SOSM mapproxy instance.

Would that be something that is possible, or is this too convoluted a process?

**Comment by simonpoole** [comment]
Sure, that is what it is there for.

**Comment by habi** [comment]
> Sure, that is what it is there for.

Who do I have to nudge to make this happen?

**Comment by Klumbumbus** [comment]
> I've been using the layer in JOSM

How did you use it? The highest zoom I can get is this, which is kinda useless: https://map.bern.ch/arcgis/rest/services/AV_farbig/MapServer/WMTS/tile/1.0.0/AV_farbig/default/default028mm/4/151/179.png

**Comment by habi** [comment]
> > I've been using the layer in JOSM
> 
> How did you use it? The highest zoom I can get is this, which is kinda useless: https://map.bern.ch/arcgis/rest/services/AV_farbig/MapServer/WMTS/tile/1.0.0/AV_farbig/default/default028mm/4/151/179.png

I've added `https://map.bern.ch/arcgis/rest/services/AV_farbig/MapServer/WMTS?` as WMTS layer in JOSM and it was much better some days/weeks ago.
To double-check I removed the layer and added it again, now it's in the low resolution (exactly how you mention).
I hope this is just a temporary hiccup because like this it is *very* useless.

**Comment by habi** [comment]
Seems to have been a temporary problem, now I see the 'cadastral survey' down to this: https://map.bern.ch/arcgis/rest/services/AV_farbig/MapServer/WMTS/tile/1.0.0/AV_farbig/default/default028mm/9/7559/8959.png (the [Wöschhüsi](https://www.openstreetmap.org/way/38533413) in the Matte).
JOSM takes some seconds to load the highest resolution, though...

**Pull request merged**
