### PR TITLE
maxzoom 21, boundary aerial

### PR DESCRIPTION
**Pull request by AllroadsNL**
Changed maxzoom to 22, because of <ows:Identifier>21</ows:Identifier> for tileMatrixSet=OGC:1.0:GoogleMapsCompatible 

In ID, this was the most zoomed in tile. tileMatrix=19
`https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=Actueel_orthoHR&STYLE=&FORMAT=image/jpeg&tileMatrixSet=OGC:1.0:GoogleMapsCompatible&tileMatrix=19&tileRow=173383&tileCol=270765`

Or should maxzoom be 21?  Is 00 also a layer = 22?

Changed boundary aerial image tiles because of issue
https://github.com/osmlab/editor-layer-index/issues/1518

### CODE REVIEW

**Comment by AllroadsNL** [comment]
It is obvious, I need some help with it.

**Comment by rbuffat** [comment]
@AllroadsNL I will try to look at it. Regarding the geometry error, it should be sufficient to just replace the geometry with the output of the check: 

```
"geometry": {"type": "Polygon", "coordinates": [[[3.40232780457, 51.55402104464], [3.40438705444, 51.5113074306], [3.47167831421, 51.47368591555], [3.4881578064, 51.4197646831], [3.36662223816, 51.39749248361], [3.32748344421, 51.3709234998], [3.35391963959, 51.33726139222], [3.33400691986, 51.32224493197], [3.34773983002, 51.27072258543], [3.39099849701, 51.24493972569], [3.43391384125, 51.22494806273], [3.55442012787, 51.23419259947], [3.54755367279, 51.26921898242], [3.63716091156, 51.27372964386], [3.76178707123, 51.24408004798], [3.763503685, 51.21355107844], [3.77449001312, 51.20150591606], [3.79062618256, 51.19505185457], [3.86169399261, 51.19419124472], [3.87336696625, 51.18795134259], [3.88915981293, 51.18493867362], [3.96881069183, 51.20236638927], [4.01103939056, 51.22516307305], [4.05601467133, 51.22731312099], [4.07695735931, 51.23268780144], [4.18613399506, 51.28468226397], [4.25754512787, 51.34326659941], [4.25720180511, 51.36063437612], [4.31488002777, 51.36213498605], [4.32311977386, 51.34433887505], [4.35058559418, 51.34283768213], [4.38594783783, 51.33940619939], [4.42439998627, 51.34734111337], [4.44328273773, 51.35162968409], [4.45358242035, 51.35784739868], [4.45804561615, 51.37949561081], [4.41410030365, 51.41740888568], [4.42886318207, 51.44651864303], [4.51126064301, 51.46341947182], [4.50439418793, 51.451011879], [4.51297725677, 51.41526773028], [4.53529323578, 51.40755874036], [4.57408870697, 51.41633832052], [4.64515617371, 51.40605983332], [4.68601192474, 51.4146253641], [4.77149929047, 51.48459015812], [4.81098140717, 51.46855266163], [4.79553188324, 51.44887229797], [4.76566280365, 51.44651864303], [4.74540676117, 51.43902893377], [4.74197353363, 51.42233316252], [4.74678005219, 51.40884366228], [4.76394618988, 51.3985632759], [4.78214229584, 51.39385065979], [4.83638729095, 51.39770647271], [4.88307918549, 51.39235108921], [4.91123165131, 51.37842415793], [4.94144405365, 51.38206699541], [5.02830471039, 51.43838690153], [5.03894771576, 51.45464893665], [5.05886043549, 51.45486287219], [5.07533992767, 51.43325031877], [5.04444087982, 51.39406488014], [5.05199398041, 51.38378117155], [5.09250606537, 51.35291617703], [5.10349239349, 51.33790484491], [5.11070217133, 51.31001361016], [5.11894191742, 51.30336011866], [5.16700710297, 51.293914797], [5.19824947357, 51.30357476248], [5.21266902924, 51.29842303386], [5.20168270111, 51.26599681028], [5.22674526215, 51.24665903288], [5.26485408783, 51.24837827581], [5.34416164398, 51.24622921211], [5.36544765472, 51.25310586246], [5.42209590912, 51.24558447342], [5.49659694672, 51.27845462379], [5.52474941254, 51.25976663687], [5.54157222748, 51.20838925174], [5.62019313812, 51.18773615848], [5.64388240814, 51.1705181743], [5.67752803802, 51.16642795804], [5.74275936127, 51.16664324162], [5.75614894867, 51.14037122686], [5.77194179535, 51.13714002846], [5.79219783783, 51.13024604935], [5.77400173187, 51.09791680106], [5.75168575287, 51.07095848075], [5.73314632416, 51.03534943834], [5.73829616547, 51.01850654064], [5.73898281097, 51.00489819362], [5.71907009125, 50.99128585339], [5.697097435, 50.97053556024], [5.69572414398, 50.9521551635], [5.70980037689, 50.94133976857], [5.69915737152, 50.92965631559], [5.67649806976, 50.92121644065], [5.66791500092, 50.90389908457], [5.65589870453, 50.89761995171], [5.62362636566, 50.88245993516], [5.61504329681, 50.86274453674], [5.61469997406, 50.83933521899], [5.631522789, 50.81179256345], [5.66448177338, 50.79812364153], [5.67169155121, 50.78032635597], [5.6576153183, 50.7605677773], [5.66139186859, 50.74927341365], [5.67443778992, 50.7403665379], [5.74413265228, 50.74253893859], [5.7588955307, 50.74840450356], [5.76576198578, 50.75665849831], [5.7805248642, 50.75231447198], [5.79425777435, 50.74384246097], [5.813826828, 50.7403665379], [5.85536922455, 50.73971451559], [5.87013210297, 50.74536319123], [5.89107479095, 50.73819360188], [5.91751029968, 50.73471725949], [5.94325984955, 50.74123537991], [5.95458950043, 50.74384246097], [5.97072566986, 50.73949724523], [5.99166801453, 50.73775926331], [6.05483940125, 50.73906291875], [6.05827262878, 50.78597034839], [6.06033256531, 50.82849380994], [6.09947135925, 50.83066233659], [6.11732414246, 50.85234206268], [6.1303704071, 50.93117121924], [6.11217464447, 50.94155610113], [6.07131923676, 50.94977599252], [6.05827297211, 50.95064115969], [6.05792964935, 50.96750870097], [6.0596459198, 50.9904216591], [6.04591300964, 51.00468237196], [5.9717552948, 51.00986699911], [6.00814750671, 51.0323270207], [6.02668693542, 51.06988003687], [6.06101921082, 51.07419452446], [6.14273002625, 51.12421318879], [6.20384147644, 51.12550605713], [6.20452812195, 51.2120458205], [6.12075737, 51.2120458205], [6.12213066101, 51.23010824815], [6.2525933075, 51.3443390895], [6.25122001648, 51.5283974294], [6.16058280945, 51.60778368326], [6.15852287292, 51.66872297312], [6.03835990906, 51.75679077609], [6.06239250183, 51.82092533504], [6.32469108582, 51.82177418754], [6.37069633484, 51.80734151992], [6.43318107605, 51.80606782732], [6.61033561707, 51.87310001398], [6.75453117371, 51.87606748594], [6.82388237, 51.91377970089], [6.85821464539, 51.94934422266], [6.868514328, 52.00517439325], [6.77238395691, 52.05460207487], [6.79641654968, 52.0930080615], [6.87538078308, 52.09174245668], [7.10884025574, 52.23200550603], [7.11776664734, 52.38691614274], [7.0264427948, 52.48821647535], [6.7627709198, 52.48654398225], [6.7366783905, 52.51037100557], [6.75041130066, 52.53418511776], [6.79092338562, 52.53877933764], [6.79366996765, 52.57551579281], [6.77307060242, 52.60263092589], [6.79092338562, 52.62889573841], [7.01339653015, 52.60846891261], [7.08686759949, 52.60763496215], [7.11639335632, 52.81106341604], [7.25715568542, 52.96807900329], [7.27706840515, 53.24261938156], [6.89392021179, 53.46270843265], [6.5780632782, 53.58190782962], [5.64903190613, 53.49458220165], [5.17936637878, 53.41526212424], [4.81475761414, 53.24138664051], [4.68978813171, 53.07546547623], [4.63210990906, 52.97841624285], [4.60807731628, 52.74668466134], [4.50714042664, 52.46144895362], [4.47418144226, 52.34876360143], [4.39384391785, 52.24756300833], [4.0910332489, 52.01151432894], [3.97773674011, 52.00982376724], [3.91868522644, 51.95950033799], [3.95988395691, 51.87225212888], [3.82118156433, 51.82559382585], [3.81774833679, 51.78355999003], [3.72711112976, 51.76104091772], [3.65981987, 51.73553406684], [3.64128044128, 51.70405577886], [3.65569999695, 51.65850111809], [3.6254875946, 51.62398532998], [3.52386405945, 51.60650435956], [3.40232780457, 51.55402104464]]]}
```

**Comment by rbuffat** [comment]
The tms URL for the `Actueel_orthoHR` layer is `https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0/Actueel_orthoHR/OGC:1.0:GoogleMapsCompatible/{zoom}/{x}/{y}.jpeg`

**Comment by AllroadsNL** [comment]
@rbuffat Thanks.

This raised some thoughts, after some tries.
The used wmts url was working (ID), with zoom=19 because of "maxzoom=19" setting, 20 then there was over-zooming, seeing not as sharp as we used these same wmts url in JOSM. This was the problem asked in the Openstreetmap forum. In JOSM we get zoom=20 "&tileMatrix=20" Now I used the rbuffat tms url in JOSM, and get a layer with "&tileMatrix=21" visible , conclusion this layer 21 is working. Strange that JOSM with wmts url only got layer 20. 

tms url setting JOSM to 21

OSMlab: Conclusion: maxzoom=19 was set wrong. It should be 21 for OGC:1.0:GoogleMapsCompatible

Probably my fault, changing the file, only change the wmts url but the maxspeed=19 was left as it is.

Because wmts and tms both are working:
**What is the benefit for using one or the other?**

Our Government publish this file as wmts, because of performance choice. Advice to use wmts and not so much wms.

Watched other country index files, there more wmts string used, why change to tmsstring?

I like to know the, why. To understand, what the problem is.

Earlier I got this answer:
> Because the URL has parameters {zoom}&tileRow={y}&tileCol={x} then it's tms.
https://github.com/osmlab/editor-layer-index/pull/1332
the file change at that moment:
https://github.com/osmlab/editor-layer-index/pull/1332/files

I find it kind of strange that then it was verified, okay.

Now I have with wmts url also a verified icon.
but still in strick checked
`Error fetching TMS: 'zoom': https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=Actueel_orthoHR&STYLE=&FORMAT=image/jpeg&tileMatrixSet=OGC:1.0:GoogleMapsCompatible&tileMatrix={zoom}&tileRow={y}&tileCol={x}

Error fetching TMS: 'zoom': https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=Actueel_orthoHR&STYLE=&FORMAT=image/jpeg&tileMatrixSet=OGC:1.0:GoogleMapsCompatible&tileMatrix={zoom}&tileRow={y}&tileCol={x}`

but

> WARNING:root:This is a new and improved check for new or changed imagery sources. It is currently in beta stage. Please report any issues.

I changed it from maxzoom 19 to 21, this are two layers, it looks like 20 21 give a problem.

Can the pull request be validated with wmts url, to see how this works out as a test, if we get layers 20 / 21 visible.

If not use the tms url.

**Comment by rbuffat** [comment]
@AllroadsNL

**TMS vs WMTS:**
WMTS and TMS are both similar protocols in the sense that you can request tiles using an URL with zoom, x and y parameters. However, WMTS is more complex compared to TMS. E.g. it allows service discovery or it allows the data to be in different projects (coordinate systems). While a WMTS service must not be compatible with TMS, some services are when they are using the GoogleMapsCompatible / EPSG:3857 projection.

While TMS is understood by most OSM editors, not all support the WMTS protocol. Thus by using TMS the data can be used for more OSM editors.

**Zoom levels:**
When you browse to https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0?SERVICE=WMTS&REQUEST=GetCapabilities&VERSION=1.0.0  and search for `<ows:Identifier>OGC:1.0:GoogleMapsCompatible</ows:Identifier>` you see that there seem to be 21 zoom levels. For WMTS sources, the test script checks this page. For tms, the test script tries to download a tile for each zoom level. It is a good suggestion to try to identify if a TMS entry points to a  WMTS service.

```
`Error fetching TMS: 'zoom': [https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=Actueel_orthoHR&STYLE=&FORMAT=image/jpeg&tileMatrixSet=OGC:1.0:GoogleMapsCompatible&tileMatrix={zoom}&tileRow={y}&tileCol={x}](https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=Actueel_orthoHR&STYLE=&FORMAT=image/jpeg&tileMatrixSet=OGC:1.0:GoogleMapsCompatible&tileMatrix=%7Bzoom%7D&tileRow=%7By%7D&tileCol=%7Bx%7D)
```

I need to look into this. In every case the error message in confusing. When looking at it the first time it looked like something was wrong with the URL, but it might very well also be a bug in the test script.

**Pull request merged**
