### PR TITLE
virginia wms layers

### PR DESCRIPTION
**Pull request by jonahadkins**
building footprints, property lines, and imagery!

### CODE REVIEW

**Comment by grischard** [comment]
Thanks for your PR! Could you please check [why the tests are failing](https://travis-ci.org/osmlab/editor-layer-index/builds/417998642?utm_source=github_status&utm_medium=notification), and include a license?

**Comment by rivermont** [comment]
Unnecessary `"type": "FeatureCollection'` wrapping each `Feature` in the json files. Once removing that it should work.

**Comment by jonahadkins** [comment]
hi 👋 - i've included the license and overlay =`true` for 2 of the layers

**Comment by grischard** [comment]
Great, thank you!

**Comment by Klumbumbus** [comment]
Are these entries working for you? I only get 404 errors for all 3 sources at all zoom levels.

**Comment by Klumbumbus** [comment]
I think the file extension is missing at the end of the URLs

**Comment by grischard** [comment]
Yeah, for example https://gismaps.vita.virginia.gov/arcgis/rest/services/VA_Base_layers/VA_Building_Footprints/MapServer/tile/8/12630/9241 returns a png for me. Not for you?

**Comment by Klumbumbus** [comment]
I see a png with building footprints at your URL. But why is it at z8? At z8 you would see the whole state, not buildings. Is there a offset or reversed function in the zoom parameter?
When I zoom in to Richmond I get e.g. https://gismaps.vita.virginia.gov/arcgis/rest/services/VA_Base_layers/VA_Building_Footprints/MapServer/tile/17/50771/37342

**Comment by jonahadkins** [comment]
im guessing i need to update something here? i used [San Juan County](https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/wa) as a template since it comes from AGOL as well.

**Comment by grischard** [comment]
Ah, so it looks like the virginia tile servers have their own personal url scheme? Great.

**Comment by grischard** [comment]
So something like https://gismaps.vita.virginia.gov/arcgis/rest/services/VA_Base_layers/VA_Building_Footprints/MapServer/WMTS/tile/1.0.0/VA_Base_layers_VA_Building_Footprints/default/GoogleMapsCompatible/17/50771/37342.png should work but it just 404s for me.

**Comment by jonahadkins** [comment]
bummer. i usually use this [tilefy app](https://github.com/JasonSanford/tileify-ags-proxy) to provide the urls to add in the custom background dialog in iD - could we use [these links](https://github.com/jonahadkins/commonwealth/blob/master/agol2osm.md) instead?

**Comment by grischard** [comment]
Hmm, ideally it'd do a redirect, but I guess we could do that. Can you submit a new PR?

**Comment by Klumbumbus** [comment]
The original URLs were added in JOSM (with `{zoom-7}`) in case you want to replace the tilefy URLs here.
https://josm.openstreetmap.de/wiki/Maps/USA?action=diff&version=121

**Comment by grischard** [comment]
Oh dear, who thought that was a good idea? I'm not even sure the editors would support that.

**Comment by simonpoole** [comment]
Well it seems to be a classical JOSM one off, I don't quite see why we should complicate parsing of the placeholders for exactly one use case.

**Pull request merged**
