### PR TITLE
Add Ortho Imagery: Fukaya,Japan

### PR DESCRIPTION
**Pull request by nyampire**
I've created this PR to add an imagery for Fukaya city, Saitama, Japan.

Similar to [Nerima Ortho](https://github.com/osmlab/editor-layer-index/pull/1285), Fukaya-city granted the permission to use this ortho for OpenStreetMap editing.

Details are available on the [wiki page](https://wiki.openstreetmap.org/wiki/Fukaya_ortho) (sorry, written in Japanese...).

### CODE REVIEW

**Comment by rbuffat** [comment]
@nyampire  Thank you for creating this PR! Unfortunately, there was a bug that lead the test script to fail. This should be fixed now with https://github.com/osmlab/editor-layer-index/pull/1361. Would it be possible for you to rebase / merge the current gh-pages branch?

When I run the test script locally, it seems to have trouble accessing the tiles, but this could be a bug in the test script:
```
Zoom: 12
Request: http://nyampire.conohawing.com/ortho-atsugi-shi/12/3632/2490.png -> 404
Zoom: 13
Request: http://nyampire.conohawing.com/ortho-atsugi-shi/13/7265/4980.png -> 404
Zoom: 14
Request: http://nyampire.conohawing.com/ortho-atsugi-shi/14/14530/9961.png -> 404
Zoom: 15
Request: http://nyampire.conohawing.com/ortho-atsugi-shi/15/29060/19922.png -> 404
Zoom: 16
Request: http://nyampire.conohawing.com/ortho-atsugi-shi/16/58120/39844.png -> 404
Zoom: 17
Request: http://nyampire.conohawing.com/ortho-atsugi-shi/17/116240/79689.png -> 404
Zoom: 18
Request: http://nyampire.conohawing.com/ortho-atsugi-shi/18/232480/159378.png -> 404
Zoom: 19
Request: http://nyampire.conohawing.com/ortho-atsugi-shi/19/464961/318757.png -> 404
```

**Comment by nyampire** [comment]
@rbuffat Thank you for checking!

As I checked locally, my PR would be fine as it is. The layer setting include so-called `Y-flip (~~~.{-y}.png)`.  And this should work in iD and JOSM as well.

スクリーンショット 2021-12-06 15 40 40
スクリーンショット 2021-12-06 15 41 20

**Comment by nyampire** [comment]
Or is it better to fix the test script?

Sorry I have few engineering skills, so probably I could not...

**Comment by rbuffat** [comment]
It looks as the geometry is not where the imagery actually is. The JOSM screenshot seems to show the following area: https://www.openstreetmap.org/#map=15/35.4594/139.3375

**Comment by nyampire** [comment]
Oops! So sorry, this is completely my mistake! (Added the layer for Atsugi-shi, instead of Fukaya-shi.)

Will check this in detail, and push once again.

**Comment by nyampire** [comment]
Corrected the line. Please check it!
スクリーンショット 2021-12-13 12 56 03

**Comment by rbuffat** [comment]
@nyampire 
 
> Oops! So sorry, this is completely my mistake! (Added the layer for Atsugi-shi, instead of Fukaya-shi.)

No worries! And thank you again for your PR!  When I looked around to find the extent of the screenshot I was quite surprised how many golf courses there are in this region (or at least it looked like golf courses):

**Pull request merged**
