### PR TITLE
Remove duplicate entry. Set Estonia ortho as local best

### PR DESCRIPTION
**Pull request by RM87**

### CODE REVIEW

**Comment by grischard** [comment]
Hi RM87! Thanks for the PR. We still need that `max_zoom` though.

**Comment by grischard** [comment]
Aitäh RM87!

**Comment by Klumbumbus** [comment]
I just tested the wms and tms sources and for me the min zoom values are 15 for wms (instead of 14) and 6 for tms (instead of 14)

**Comment by grischard** [comment]
Thank you, I've corrected the minzoom then. There's a tms? Is it any faster?

I also see that the polygon could be greatly simplified.

**Comment by Klumbumbus** [comment]
>There's a tms?

Yes and it is already in ELI ;)

**Comment by grischard** [comment]
Ahhhhhhhhh!

**Pull request merged**
