### PR TITLE
Add fresh Berlin 2023 images

### PR DESCRIPTION
**Pull request by tordans**
Same license and all as before.

### CODE REVIEW

**Comment by tordans** [comment]
@polarbearing FYI

**Comment by cicku** [comment]
Can you drop any file prior to 2018? Also you do not need to specify best:false, which means nothing.

**Comment by tordans** [comment]
> Can you drop any file prior to 2018? 

Actually, we still use those. They all have different shadow and lighting and – depending on the mapping, they are helpful. Why do you want them dropped? And why part of this PR?

> Also you do not need to specify best:false, which means nothing.

I find it helpful when all files follow the same structure and data is specified explicitly.

**Comment by tordans** [comment]
@cicku it would be great if you could merge this. We invested a lot of effort to get the fresh images from official sources and prepare them on a community maintained server so people can use it.  IMO there  is nothing holding this PR back.

**Comment by svenpilz** [comment]
I would also like to keep the images from 2016 until now. As @tordans said, sometimes the older images show have less tree cover or shadows. I use the 2016/2017/2028 often for sidewalks.

**Comment by andrewharvey** [comment]
I think `best: false` is fine, it's being explicit to avoid doubt.

> Actually, we still use those. They all have different shadow and lighting and – depending on the mapping, they are helpful.

Agreed.

**Comment by tordans** [comment]
@andrewharvey thanks a lot for merging those PRs!

**Pull request merged**
