### PR TITLE
Add Kanton Basel Stadt 2017

### PR DESCRIPTION
**Pull request by rbuffat**
This source is listed in JOSM but not here.

"This imagery is provided via a proxy operated by https://sosm.ch/"

### CODE REVIEW

**Comment by andrewharvey** [comment]
Any links to the original source or metadata would be great so we can trace it back to the origin and licensing.

**Comment by rbuffat** [comment]
@simonpoole can you help here?

**Comment by simonpoole** [comment]
We have general permission to use their data, as long as we provide attribution on the Contributors wiki page, but it seems that at the time I actually asked them again:

>Subject: WG: Orthofotos April 2015
>Thread-Topic: Orthofotos April 2015
>Thread-Index: AQHSAcTkQFM77vLqTEmK0Yh3Uyh1lqBfhv2ggAAC+RA=
>Date: Mon, 29 Aug 2016 07:30:20 +0000
>Message-ID: <6613A7D88DF64743BD42EB883EC9C7FD50B40D3F@sc000366c1.bs.ch>
>References: <6aef3506-d25a-73a1-afba-a0acb2ae472e@poole.ch>
> <8DA09EE3CFF4CE489E7DE06F446B7538505FAE9B@sc000366c1.bs.ch>
>In-Reply-To: <8DA09EE3CFF4CE489E7DE06F446B7538505FAE9B@sc000366c1.bs.ch>
> ....
>Guten Tag Herr Poole
>
>Die Orthofotos können ohne Einschränkungen für den genannten Zweck genutzt werden. Eine Quellenangabe unter >http://wiki.openstreetmap.org/wiki/Contributors reicht aus.
>Die Orthofotos werden ca. alle 2-3 Jahre aktualisiert. 
>
>Freundliche Grüsse
....

At the time only JOSM had WMS support, so we proxied the WMS server, but it is at http://wms.geo.bs.ch/wmsBS?

**Review by andrewharvey — APPROVED** [review]

**Comment by simonpoole** [comment]
I've copied the mail to the wiki https://wiki.openstreetmap.org/wiki/Orthophotos_Canton_BS 

Note there is an issue in that the WMS server lists at least one imagery layer that is sourced from Swisstopo and is not available on compatible terms.

**Comment by rbuffat** [comment]
@simonpoole Thanks!

The following page https://www.geo.bs.ch/geodaten/geodienste/wmsbs.html links to this WMS server:
https://wms.geo.bs.ch/?service=WMS&request=GetCapabilities

> WMS Server Metadata:
> Access constraints:
> Die Nutzung des Dienstes setzt das Akzeptieren der Nutzungsbedingungen voraus; siehe https://www.geo.bs.ch/agb
> 
> Fees:
> kostenlos


The AGB/Nutzungsbedingungen seems to have changed starting January 2020


> Die öffentlichen Geodaten das Kantons Basel-Stadt werden als Open Government Data (OGD) veröffentlicht. Darunter fallen alle Geodatensätze, welche in den Anhängen der kantonalen Geoinformationsverordnung (KGeoIV) die Zugangsberechtigungsstufe A und einen Downloaddienst ausweisen. Für diese Geodaten ist die Lizenz CC BY 3.0 CH massgebend.

The PDF https://www.geo.bs.ch/dam/jcr:7328c56e-545b-40eb-beda-20ad7ac762ec/20200101_AGB-Geodaten-Jan2020.pdf does not mention CC BY 3.0 CH .

EDIT: For "Öffentliche Geodaten" applies "CC BY 3.0 CH", for "Beschränkt öffentliche Geodaten" apply the terms of the PDF.

**Comment by simonpoole** [comment]
The relevant ordinance is revised once per year it seems, so that is not a direct concern, but the use of CC BY 3.0 CH for a subset of the data (for which you need to go and find the ordinance), is clearly a change relative to 2015 when we got permission (but it is actually a very recent change). So we will need them to provide a waiver (they probably don't realize that by using CC BY they are actually providing this subset on more restrictive terms than the rest of the class A sources), I'll send them a mail.

**Comment by simonpoole** [comment]
@rbuffat I've now received both the CC BY 3.0 waiver and the declaration for the aerial imagery.

**Comment by rbuffat** [comment]
@simonpoole Great news! Thank you!

**Pull request merged**
