### PR TITLE
add au/vic/city_of_melbourne may 2018 imagery

### PR DESCRIPTION
**Pull request by andrewharvey**
See permission at https://wiki.openstreetmap.org/wiki/Data.melbourne.gov.au_explicit_permission

### CODE REVIEW

**Comment by grischard** [comment]
Thank you! Could we have that wiki page as the license_url property actually?

**Comment by andrewharvey** [comment]
Sure, done.

**Comment by andrewharvey** [comment]
I've also added license, icon.

**Comment by grischard** [comment]
Thanks!

**Pull request merged**
