### PR TITLE
open in JOSM using remote control

### PR DESCRIPTION
**Pull request by andrewharvey**

### CODE REVIEW

**Comment by grischard** [comment]
The code looks good; is there an easy way of testing it?

**Comment by andrewharvey** [comment]
`python -m SimpleHTTPServer` here when checked out on this branch, then you should be able to go to `http://localhost:8000`

**Comment by grischard** [comment]
Ah, that's clever. If you've tested it, let's merge it!

**Comment by andrewharvey** [comment]
great, it's now live at https://osmlab.github.io/editor-layer-index/

**Pull request merged**
