### PR TITLE
24 Brazilian WMS layers

### PR DESCRIPTION
**Pull request by Skippern**

### CODE REVIEW

**Comment by tyrasd** [comment]
related: #211

**Comment by Skippern** [comment]
Verified all files against geojsonlint.com, made adjustments accordingly. Moved coordinates deeper according to advise, reversed one shape that was not counterclockwise. Should be ready for merge

20 of these have been generated using a small python script to make it easier to convert the shape into GeoJSON, I have done the necessary updates to the script so future files are generated correctly. The remaining files had to be corrected by hand, so indentation might be off.

**Comment by tyrasd** [comment]
Thanks!

**Comment by Klumbumbus** [comment]
The license url doesn't exist: http://www.cgu.gov.br/acessoainformacaogov/index.asp

**Comment by Skippern** [comment]
Sorry, the link must have moved between I started editing these in February, and the PR last week. At least here is another link related to same license. These layers are released in accordance with LAI (Law of Free Access to Information/Lei de Acesso ao Informações)

http://www.acessoainformacao.gov.br/menu-de-apoio/entenda-a-lai <http://www.acessoainformacao.gov.br/menu-de-apoio/entenda-a-lai>

Aun Johnsen

**Comment by Klumbumbus** [comment]
Can you please create a PR updating the links?

**Comment by Skippern** [comment]
Sure, I can have a new PR during the night

Aun Johnsen

**Pull request merged**
