### PR TITLE
Update imagery for Lyon Metropolitan Area (France)

### PR DESCRIPTION
**Pull request by natolh**
Current available imagery for Lyon Area (France) is from 2015, latest available imagery is from 2018.

Data source & details
https://data.beta.grandlyon.com/en/jeux-de-donnees/orthophotographie-2018-metropole-lyon-format-tiff/info

### CODE REVIEW

**Comment by grischard** [comment]
Looks good!

Please place the file in sources/europe/fr/ instead of the root directory, and remove the 'best' tag from Lyon-Orthophoto-2015-05-8cm.geojson

Can you please also add `https://data.beta.grandlyon.com/en/mentions-legales` as a privacy policy for all Grand Lyon sources?

**Comment by natolh** [comment]
@grischard I didn't notice my file was recorded on the root directory, I have made a few more commits to fix that and the other things you have mentioned. It should be okay now, although I don't know why the build is failing...

**Comment by simonpoole** [comment]
@natolh see https://travis-ci.org/osmlab/editor-layer-index/builds/606722048?utm_source=github_status&utm_medium=notification a syntax error in the file.

**Comment by natolh** [comment]
Yeah I did see this url but it's not very easy to understand, anyway, problem is fixed.

**Comment by grischard** [comment]
Merci beaucoup!

**Pull request merged**
