### PR TITLE
Add Plateau official tile dataset, Japan

### PR DESCRIPTION
**Pull request by nyampire**
Hello team!

I got the permission (waiver) to use Plateau Tile distribution by MLIT, a Japanese ministry. So I would like to add the URL to the index.

With great help by @cicku  (Thank you!) in #1400 , hopefully I could made the geojson file with probably valid format.

(behind the scene) Plateau Project is a project led by MLIT. They are publishing opendata for 56 cities currently. It contains CityGML, GeoTIFF and so on. They starts official tile distribution for 24 cities.

The detailed information is available here. (sorry, available in Japanese.)
https://wiki.openstreetmap.org/wiki/JA:MLIT_PLATEAU
https://wiki.openstreetmap.org/wiki/JA:MLIT_PLATEAU/tiles_official

### CODE REVIEW

**Comment by cicku** [comment]
Hello,

Following checks here, you need to replace {z} with {zoom} in all geojson files.

**Comment by nyampire** [comment]
@cicku Thank you for checking. I've replaced the "z" to "zoom" at the file.

Please take a look.

**Comment by cicku** [comment]
Hi,

You can check errors at the `Details`:

image


First, does it have a privacy policy? I think the data is hosted on AWS so maybe this one:

- https://aws.amazon.com/privacy/

**Comment by nyampire** [comment]
Thank you!
I found it had 3 errors.

1. Privacy Policy
The Plateau project itself [does not have](https://www.mlit.go.jp/plateau/site-policy/) their own Privacy Policy.
But as you mentioned above, the data is hosted by AWS. I'll follow your opinion.
Probably this is fixed.

2. `ring orientation does not correspond to GeoJSON RFC7946`
I've converted the file via [Right Hand Rule GeoJSON Fixer](https://mapster.me/right-hand-rule-geojson-fixer/).
But it still has same errors...

3. `please consider using corrected geometry: `
Is this error related to 2?

**Comment by cicku** [comment]
I think 2 and 3 are related. CC @rbuffat for a review.

**Comment by rbuffat** [comment]
I'm sorry I had lately not much time available for this project, thus my late reply. 

Regarding 1: if there is no privacy policy available it is since a few weeks ago accepted to set the value to `false`.
Regarding 2 and 3: the geojson specification [1] specifies an ordering of rings for Polygons. This check is also quite new.  The check shout output the Polygon in the correct ordering according to the geojson standard. It should be sufficient to just replace the existing geometry in the geojson file with the output of the check script.  If not, then there is a bug in the script. 


Regarding 

[1] https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6

**Pull request merged**
