### PR TITLE
Update urls for San Francisco imagery

### PR DESCRIPTION
**Pull request by arch0345**

### CODE REVIEW

**Comment by andrewharvey** [comment]
Thanks, I was unable to test this as the tile url is not responding for me, perhaps it's applying geo restrictions or down at the moment.

**Comment by arch0345** [comment]
Yeah, I think it might be georestricted to just the US, it's working fine for me:
image

**Comment by andrewharvey** [comment]
Maybe we need a new flag in the schema to inform users access may be geoblocked.

**Comment by arch0345** [comment]
I was about to mention https://ags-proxy.openstreetmap.us to get around geoblocking but it seems like this only works for ArcGIS MapServer/ImageServers

**Pull request merged**
