### PR TITLE
Create AIV_OrthoPhoto_Preliminary.geojson (Flanders, Belgium)

### PR DESCRIPTION
**Pull request by jbelien**
See https://www.geopunt.be/catalogus/datasetfolder/50134be3-f0cd-47c5-8f6e-4a0936287947 for more details

### CODE REVIEW

**Comment by jbelien** [comment]
Looking for the correct licence URL!

**Comment by jbelien** [comment]
Looking for the privacy policy URL!

**Comment by jbelien** [comment]
Ready to be merged (I think)! 😄

**Comment by rbuffat** [comment]
@jbelien Sorry for the long delay! I had a quick look at your PR and have the following comments: The license_url currently points directly to the text of the license. Typically, the URL should point to a page where it states that data X is licensed under license Y. This enables other people to quickly verify under what license the data is.

**Comment by jbelien** [comment]
Thanks for the review @rbuffat !

This is the page of the "Orthofotowerkbestand" service : https://www.geopunt.be/catalogus/webservicefolder/711f82cf-1b68-238c-ae04-4cda-d1cf-deb1-66f6d3d7

In the [metadata of the service](https://metadata.vlaanderen.be/srv/dut/catalog.search#/metadata/711f82cf-1b68-238c-ae04-4cda-d1cf-deb1-66f6d3d7), in "_Toegangs- en gebruiksbeperkingen_" (Access and usage restrictions) it is mentioned "*Geen beperkingen op de publieke toegang*" (No restrictions on public access) with a link to https://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations
Would that metadata page fit as `license_url` ?

**Comment by rbuffat** [comment]
https://metadata.vlaanderen.be/srv/dut/catalog.search#/metadata/711f82cf-1b68-238c-ae04-4cda-d1cf-deb1-66f6d3d7 looks like a good link for the license_url. 

https://overheid.vlaanderen.be/Webdiensten-Gebruiksrecht looks like a good link for the privacy policy url as it explicitly mentions the following:

```
Privacy declaration
The geographic web services are services that have been developed and are managed by the Flanders Information Agency of the Flemish government as controller.

When using the geographic web services, Information Flanders keeps track of, among other things, the IP address (*) of the machine/server from which the question is asked, for security purposes so that suspicious or invasive use can be traced. This processing is part of the public interest task of Information Flanders to manage the aforementioned geographical web services. The collected IP addresses are kept for a maximum period of 90 days and are only accessible to the administrators of the geographical web services of Information Flanders.

The user of the geographical web services can request Information Flanders to inspect and rectify or delete the personal data or limit the processing concerning him. The user also has the right to object to the processing, in which case access to the geographic web services will not be possible. These rights can be exercised via the contact details below, whereby the request must always be accompanied by proof of identity and proof that the relevant IP address relates to the user.

If the user does not agree with the way in which Information Flanders processes personal data or has questions about this, he can always contact the data protection officer of Information Flanders via [privacy@digitaal.vlaanderen.be](mailto:privacy@digitaal.vlaanderen.be)or lodge a complaint with the competent supervisory authority.
```

**Comment by jbelien** [comment]
Thanks a lot @rbuffat ! I've made the changes.

**Comment by rbuffat** [comment]
Thanks @jbelien !

**Pull request merged**
