### PR TITLE
add Ukraine - Vinnytsia 2018 and set default for Mykolaiv

### PR DESCRIPTION
**Pull request by bezdna**

### CODE REVIEW

**Comment by grischard** [comment]
I don't think you want 'default', which will show this in the world-wide menu - what are you trying to achieve? Maybe 'best' to mark this as the best for the region?

**Comment by bezdna** [comment]
> I don't think you want 'default', which will show this in the world-wide menu - what are you trying to achieve? Maybe 'best' to mark this as the best for the region?

yes you are right 
I will fix

**Comment by grischard** [comment]
Thank you @bezdna !

**Comment by Klumbumbus** [comment]
The shape of Vinnytsia is unclosed.

**Comment by bezdna** [comment]
> The shape of Vinnytsia is unclosed.

changed here https://github.com/osmlab/editor-layer-index/pull/802

**Pull request merged**
