### PR TITLE
ASIT VD stored imagery update

### PR DESCRIPTION
**Pull request by yblatti**
- switch to HTTPS
- bump Lausanne imagery to 2016 flight

### CODE REVIEW

**Comment by grischard** [comment]
Looks good!

Do you want to rename Lausanne-Orthopho-2012.geojson to 2016?

Is there any value in keeping the 2012 as a historic imagery layer?

**Comment by yblatti** [comment]
> Do you want to rename Lausanne-Orthopho-2012.geojson to 2016?

Right !

> Is there any value in keeping the 2012 as a historic imagery layer?

Not sure of the value, plus we're cannot guarantee the storage of historic versions on our small server.

**Comment by grischard** [comment]
Ah, and we should have https://www.asitvd.ch/tarifs-conditions.html as a `privacy_policy_url`.

**Comment by grischard** [comment]
Thank you!

**Pull request merged**
