### PR TITLE
add 32 missing license_url

### PR DESCRIPTION
**Pull request by Marc-marc-marc**

### CODE REVIEW

**Comment by bhousel** [comment]
Thank you for tracking these down!  🙇

**Comment by simonpoole** [comment]
Does the imagery/server referenced in CantondeFribourg50cm-2005.geojson still exist?

**Comment by tyrasd** [comment]
@simonpoole – I asked the same question here: https://wiki.openstreetmap.org/wiki/Talk:Switzerland:Fribourg

**Comment by simonpoole** [comment]
Ah, you should really know that OSM is not wikipedia :-) A talk page is roughly equivalent to /dev/null

**Comment by Marc-marc-marc** [comment]
@simonpoole we are talking about it on talk-ch :-) and still waiting news to update the url.
This PR focus on and only on license_url
We need another pr/tools/guideline to check/detect/tag/remove dead/tmp-broken layers after x days/week/months

**Comment by tyrasd** [comment]
> A talk page is roughly equivalent to /dev/null

:woman_shrugging: I got a response from a Latvian community member here: https://wiki.openstreetmap.org/wiki/Talk:Latvia/L%C4%A2IA_ortofoto

**Pull request merged**
