### PR TITLE
2017 and 2018 are not the whole country but specific regions

### PR DESCRIPTION
**Pull request by hbogner**
Renaming the layers and definitions for different regions in two different years.

### CODE REVIEW

**Comment by grischard** [comment]
Hi @hbogner, thanks for the PR! While I have you here: the polygons for the Croatia imagery are some of the biggest in the index. They're just used to decide where to show the imagery as available to the editors - a bit of imprecision isn't bad, and the Adriatic coast can just be a straight line. Our friends over at JOSM have simplified the HR polygons, can you check to see if these polygons are ok?

**Comment by grischard** [comment]
On https://josm.openstreetmap.de/wiki/Maps/Croatia you can hit 'view'.

**Comment by Klumbumbus** [comment]
These are the simplified ones. (I just slightly adjusted 3 of them)

````
* Different number of points for shape 1 (942 ! = 96): [HR] dgu.hr: Croatia 2017 Aerial imagery [dgu-dof-2017]
* Different number of points for shape 2 (893 ! = 49): [HR] dgu.hr: Croatia 2017 Aerial imagery [dgu-dof-2017]
* Different number of points for shape 1 (1045 ! = 113): [HR] dgu.hr: Croatia 2018 Aerial imagery [dgu-dof-2018]
* Different number of points for shape 1 (3338 ! = 232): [HR] dgu.hr: Croatia 2011 Aerial imagery [dgu-dof-2011]
* Different number of points for shape 1 (2486 ! = 175): [HR] dgu.hr: Croatia 2014-2016 Aerial imagery [dgu-dof-2014-2016]
````

**Comment by hbogner** [comment]
Hi @grischard I just checked, and they seem ok to me. How do we get those simplified ones from JOSM to here?

**Comment by Klumbumbus** [comment]
You can create a pull request here. You can find the JOSM versions in ELIs geojson format at https://josm.openstreetmap.de/maps?format=geojson&pretty=true

**Comment by hbogner** [comment]
Pull created: https://github.com/osmlab/editor-layer-index/pull/820

**Comment by hbogner** [comment]
@Klumbumbus @grischard can you check my PR?
Do I need to simplify all the files?

**Pull request merged**
