### PR TITLE
Update imageries of Hungary

### PR DESCRIPTION
**Pull request by BathoryPeter**

### CODE REVIEW

**Comment by tyrasd** [comment]
Nice, thanks!

**Comment by Klumbumbus** [comment]
Whats the correct year of https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/hu/Torokbalint-ortophoto-2015.geojson ?
file name: 2015
name: 2017
id: 2015
start_date: 2015
url: 2015_20160218

**Comment by Klumbumbus** [comment]
The URL of https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/hu/Budapest-XI-district-ortophoto-2017.geojson contains `&amp;` instead of `&` which is invalid afaik.

**Comment by BathoryPeter** [comment]
Thanks for checking my changes!
Date is just a typo, it's from 2015 of course. (I don't know what is 2015_20160218 in the url, maybe the publication date.
&amp; is a copy-paste mistake, comes from JOSM xml.

Both of them have been fixed in a new PR #313

**Pull request merged**
