### PR TITLE
Converted http links to https if response same. Fixes #438.

### LINKED ISSUE #438: https for lots of GB sources
All these source URLs were changed to https in JOSM, also attribution URLs and a few others (logo-URL), see https://josm.openstreetmap.de/wiki/Maps/United%20Kingdom?action=diff&version=46
````
+ Missing https: [GB] NLS - Bartholomew Half Inch, 1897-1907 - http://geo.nls.uk/mapdata2/bartholomew/great_britain/{zoom}/{x}/{-y}.png
+ Missing https: [GB] NLS - OS 1-inch 7th Series 1955-61 - http://geo.nls.uk/mapdata2/os/seventh/{zoom}/{x}/{-y}.png
+ Missing https: [GB] NLS - OS 1:25k 1st Series 1937-61 - http://geo.nls.uk/mapdata2/os/25000/{zoom}/{x}/{-y}.png
+ Missing https: [GB] NLS - OS 25-inch (Scotland), 1892-1905 - http://geo.nls.uk/mapdata2/os/25_inch/scotland_1/{zoom}/{x}/{y}.png
+ Missing https: [GB] NLS - OS 6-inch Scotland 1842-82 - http://geo.nls.uk/maps/os/six_inch/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Aberdeen 1866-1867 (NLS) - http://geo.nls.uk/maps/towns/aberdeen/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Airdrie 1858 (NLS) - http://geo.nls.uk/maps/towns/airdrie/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Alexandria 1859 (NLS) - http://geo.nls.uk/maps/towns/alexandria/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Alloa 1861-1862 (NLS) - http://geo.nls.uk/maps/towns/alloa/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Annan 1859 (NLS) - http://geo.nls.uk/maps/towns/annan/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Arbroath 1858 (NLS) - http://geo.nls.uk/maps/towns/arbroath/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Ayr 1855 (NLS) - http://geo.nls.uk/maps/towns/ayr/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Berwick-upon-Tweed 1852 (NLS) - http://geo.nls.uk/maps/towns/berwick/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Brechin 1862 (NLS) - http://geo.nls.uk/maps/towns/brechin/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Burntisland 1894 (NLS) - http://geo.nls.uk/maps/towns/burntisland/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Campbelton 1865 (NLS) - http://geo.nls.uk/maps/towns/campbeltown/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Coatbridge 1858 (NLS) - http://geo.nls.uk/maps/towns/coatbridge/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Cupar 1854 (NLS) - http://geo.nls.uk/maps/towns/cupar1854/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Cupar 1893-1894 (NLS) - http://geo.nls.uk/maps/towns/cupar1893/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Dalkeith 1852 (NLS) - http://geo.nls.uk/maps/towns/dalkeith1852/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Dalkeith 1893 (NLS) - http://geo.nls.uk/maps/towns/dalkeith1893/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Dumbarton 1859 (NLS) - http://geo.nls.uk/maps/towns/dumbarton/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Dumfries 1850 (NLS) - http://geo.nls.uk/maps/towns/dumfries1850/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Dumfries 1893 (NLS) - http://geo.nls.uk/maps/towns/dumfries1893/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Dundee 1857-1858 (NLS) - http://geo.nls.uk/maps/towns/dundee1857/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Dundee 1870-1872 (NLS) - http://geo.nls.uk/maps/towns/dundee1870/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Dunfermline 1854 (NLS) - http://geo.nls.uk/maps/towns/dunfermline1854/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Dunfermline 1894 (NLS) - http://geo.nls.uk/maps/towns/dunfermline1893/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Edinburgh 1849-1851 (NLS) - http://geo.nls.uk/maps/towns/edinburgh1849/{zoom}/{x}/{y}.png
+ Missing https: [GB] OS Town Plans, Edinburgh 1876-1877 (NLS) - http://geo.nls.uk/maps/towns/edinburgh1876/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Edinburgh 1893-1894 (NLS) - http://geo.nls.uk/maps/towns/edinburgh1893/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Edinburgh 1940s-1960s (NLS) - http://geo.nls.uk/mapdata3/os/edinburgh_1250_out/{zoom}/{x}/{y}.png
+ Missing https: [GB] OS Town Plans, Elgin 1868 (NLS) - http://geo.nls.uk/maps/towns/elgin/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Falkirk 1858-1859 (NLS) - http://geo.nls.uk/maps/towns/falkirk/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Forfar 1860-1861 (NLS) - http://geo.nls.uk/maps/towns/forfar/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Forres 1868 (NLS) - http://geo.nls.uk/maps/towns/forres/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Galashiels 1858 (NLS) - http://geo.nls.uk/maps/towns/galashiels/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Girvan 1857 (NLS) - http://geo.nls.uk/maps/towns/girvan/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Glasgow 1857-1858 (NLS) - http://geo.nls.uk/maps/towns/glasgow1857/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Glasgow 1892-1894 (NLS) - http://geo.nls.uk/maps/towns/glasgow1894/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Greenock 1857 (NLS) - http://geo.nls.uk/maps/towns/greenock/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Haddington 1853 (NLS) - http://geo.nls.uk/maps/towns/haddington1853/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Haddington 1893 (NLS) - http://geo.nls.uk/maps/towns/haddington1893/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Hamilton 1858 (NLS) - http://geo.nls.uk/maps/towns/hamilton/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Hawick 1857-1858 (NLS) - http://geo.nls.uk/maps/towns/hawick/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Inverness 1867-1868 (NLS) - http://geo.nls.uk/maps/towns/inverness/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Irvine 1859 (NLS) - http://geo.nls.uk/maps/towns/irvine/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Jedburgh 1858 (NLS) - http://geo.nls.uk/maps/towns/jedburgh/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Kelso 1857 (NLS) - http://geo.nls.uk/maps/towns/kelso/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Kilmarnock 1857-1859 (NLS) - http://geo.nls.uk/maps/towns/kilmarnock/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Kirkcaldy 1855 (NLS) - http://geo.nls.uk/maps/towns/kirkcaldy1855/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Kirkcaldy 1894 (NLS) - http://geo.nls.uk/maps/towns/kirkcaldy1894/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Kirkcudbright 1850 (NLS) - http://geo.nls.uk/maps/towns/kirkcudbright1850/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Kirkcudbright 1893 (NLS) - http://geo.nls.uk/maps/towns/kirkcudbright1893/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Kirkintilloch 1859 (NLS) - http://geo.nls.uk/maps/towns/kirkintilloch/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Kirriemuir 1861 (NLS) - http://geo.nls.uk/maps/towns/kirriemuir/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Lanark 1858 (NLS) - http://geo.nls.uk/maps/towns/lanark/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Linlithgow 1856 (NLS) - http://geo.nls.uk/maps/towns/linlithgow/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Mayole 1856-1857 (NLS) - http://geo.nls.uk/maps/towns/maybole/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Montrose 1861-1862 (NLS) - http://geo.nls.uk/maps/towns/montrose/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Musselburgh 1853 (NLS) - http://geo.nls.uk/maps/towns/musselburgh1853/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Musselburgh 1893 (NLS) - http://geo.nls.uk/maps/towns/musselburgh1893/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Nairn 1867-1868 (NLS) - http://geo.nls.uk/maps/towns/nairn/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Oban 1867-1868 (NLS) - http://geo.nls.uk/maps/towns/oban/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Paisley 1858 (NLS) - http://geo.nls.uk/maps/towns/paisley/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Peebles 1856 (NLS) - http://geo.nls.uk/maps/towns/peebles/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Perth 1860 (NLS) - http://geo.nls.uk/maps/towns/perth/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Peterhead 1868 (NLS) - http://geo.nls.uk/maps/towns/peterhead/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Port Glasgow 1856-1857 (NLS) - http://geo.nls.uk/maps/towns/portglasgow/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Portobello 1893-1894 (NLS) - http://geo.nls.uk/maps/towns/portobello/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Rothesay 1862-1863 (NLS) - http://geo.nls.uk/maps/towns/rothesay/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Selkirk 1865 (NLS) - http://geo.nls.uk/maps/towns/selkirk/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, St Andrews 1854 (NLS) - http://geo.nls.uk/maps/towns/standrews1854/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, St Andrews 1893 (NLS) - http://geo.nls.uk/maps/towns/standrews1893/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Stirling 1858 (NLS) - http://geo.nls.uk/maps/towns/stirling/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Stonehaven 1864 (NLS) - http://geo.nls.uk/maps/towns/stonehaven/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Stranraer 1847 (NLS) - http://geo.nls.uk/maps/towns/stranraer1847/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Stranraer 1863-1877 (NLS) - http://geo.nls.uk/maps/towns/stranraer1867/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Stranraer 1893 (NLS) - http://geo.nls.uk/maps/towns/stranraer1893/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Strathaven 1858 (NLS) - http://geo.nls.uk/maps/towns/strathaven/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Wick 1872 (NLS) - http://geo.nls.uk/maps/towns/wick/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Wigtown 1848 (NLS) - http://geo.nls.uk/maps/towns/wigtown1848/{zoom}/{x}/{-y}.png
+ Missing https: [GB] OS Town Plans, Wigtown 1894 (NLS) - http://geo.nls.uk/maps/towns/wigtown1894/{zoom}/{x}/{-y}.png
````

### PR DESCRIPTION
**Pull request by grischard**
`scripts/https-300-checker.py` checks for redirects and for resources that could be accessed over https instead of http.

Using its output, I updated the source files.

@tyrasd would it please be possible to run your check script to make sure I didn't break anything?

### CODE REVIEW

**Comment by jbelien** [comment]
Love the idea behind this ! HTTPS all the way ! 🎉 👍

**Comment by grischard** [comment]
I see that my editor cleaned up some white space while I edited the file. This makes the diff a bit less readable. Sorry.

**Comment by tyrasd** [comment]
> @tyrasd would it please be possible to run your check script to make sure I didn't break anything?

Sorry, I haven't adapted my script for the tms layers quite yet (but I'm working on it).

But is that really needed for this PR: as far as I can see, you already check the returned content here: https://github.com/osmlab/editor-layer-index/pull/450/files#diff-c4976011bea9f2bb2a678bab47ddf99cR35 ?

**Comment by Klumbumbus** [comment]
[FR] BANO - https://{switch:a,b,c}.tile.openstreetmap.fr/bano/{zoom}/{x}/{y}.png doesn't work for me in https

**Comment by Klumbumbus** [comment]
I need to correct me. https works, but the change from `.layers.` to `.tile.` breaks the URL

**Pull request merged**
