### PR TITLE
Kentucky Aerial Photography and Elevation Data Program

### LINKED ISSUE #612: Kentucky Aerial Photography and Elevation Data Program
The Kentucky Aerial Photography and Elevation Data Program (KYAPED) publishes 6-inch and 1-foot orthoimagery in metropolitan areas of the U.S. state of Kentucky as part of the [KyFromAbove](http://kyfromabove.ky.gov/) initiative. This layer is a mosaic of the 6-inch and 1-foot imagery, preferring 6-inch where available.

## URL of the imagery
http://kyraster.ky.gov/arcgis/rest/services/ImageServices/Ky_KYAPED_Imagery_WGS84WM/ImageServer

## Two letter country code
US

## Desired layer name
Kentucky Aerial Photography and Elevation Data Program

## License
All KYAPED imagery is [in the public domain](http://kygeonet.ky.gov/kyfromabove/pdfs/KyFromAboveDistributionPolicy.pdf).

## Is the license compatible with OSM?
Yes

## Attribution (text, URL, required?)
[KyFromAbove](http://kyfromabove.ky.gov/), Commonwealth of Kentucky
(not required)

## Privacy policy (URL)
https://kentucky.gov/policies/

## Icon
None

## Bounding polygon
This layer’s coverage area mostly follows county lines, but I had to manually add eastern Meade County, which contains Fort Knox. 💰

* [Original Overpass query](http://overpass-turbo.eu/s/FdL) (excludes eastern Meade County)
* [GeoJSON](https://gist.github.com/1ec5/7ef3ddd2e3bae91e97cadb366c0c2ed7)

The coverage area overlaps slightly with OSIP (#593) in the Cincinnati/Northern Kentucky metropolitan area.

### PR DESCRIPTION
**Pull request by 1ec5**
Added two WMS orthoimagery sources from Kentucky Aerial Photography and Elevation Data Program (KYAPED), commonly known as KyFromAbove:

* “KyFromAbove” is a mosaic of 6-inch and 1-foot leaf-off orthoimagery taken between 2012 and 2014 in [these 38 counties](http://overpass-turbo.eu/s/SI3) in western and central Kentucky, plus parts of Bullitt and Meade counties in the vicinity of [Fort Knox](https://en.wikipedia.org/wiki/United_States_Bullion_Depository). 💰
* “KyFromAbove 2019 6in” contains 6-inch leaf-off orthoimagery taken last year in [these 63 counties](http://overpass-turbo.eu/s/SI4) covering all of eastern Kentucky.

There is some overlap between the two layers, but the second layer is much more up-to-date. It’s the first 6-inch imagery ever released publicly for most of eastern Kentucky, a region that still needs a lot of attention in OpenStreetMap. It would be a “best” layer except for the Lexington area, where Mapbox has higher-resolution coverage. It was released sometime in the past month, and I can’t wait to start tracing from it as soon as iD picks it up.

Fixes #612.

### CODE REVIEW

**Comment by 1ec5** [comment]
[Added to the JOSM wiki](https://josm.openstreetmap.de/wiki/Maps/USA?action=diff&version=207).

**Comment by 1ec5** [comment]
The PR build bot keeps failing with the following error:

```
ERROR:root:Error in sources/north-america/us/ky/KYAPED.geojson : sources/north-america/us/ky/KYAPED.geojson: privacy policy url https://kentucky.gov/policies/ is not reachable: HTTPSConnectionPool(host='kentucky.gov', port=443): Max retries exceeded with url: /policies/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),))
```

https://kentucky.gov/policies/ is reachable but it’s a redirect to https://kentucky.gov/policies/Pages/default.aspx. I had gone with the shorter URL figuring that it’s less likely to change the next time kentucky.gov gets redesigned, but for now I’ll put in the resolved URL.

**Comment by 1ec5** [comment]
Oh, I should read the error message. It’s a certificate error. Oddly, Firefox, Safari, and Chrome seem to have no problem with that site’s certificate. I’ll revert back to the insecure page so the tests pass.

**Comment by 1ec5** [comment]
Reverting to HTTP doesn’t help, because http://kentucky.gov/policies/Pages/default.aspx (correctly) redirects to https://kentucky.gov/policies/Pages/default.aspx, but the certificate issue trips up the reachability check:

https://github.com/osmlab/editor-layer-index/blob/719d4f580d177027401111465d6ba7d3a1e89ccc/scripts/check.py#L180-L182

The only other client that seems to have a problem with this site is curl when verifying certificates:

```
$ curl -v --cert-status https://kentucky.gov/policies/Pages/default.aspx
*   Trying 205.204.237.65...
* TCP_NODELAY set
* Connected to kentucky.gov (205.204.237.65) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Kentucky; L=Frankfort; O=Commonwealth of Kentucky; CN=kentucky.gov
*  start date: Aug 23 18:11:29 2018 GMT
*  expire date: Sep 20 18:41:29 2020 GMT
*  subjectAltName: host "kentucky.gov" matched cert's "kentucky.gov"
*  issuer: C=US; O=Entrust, Inc.; OU=See www.entrust.net/legal-terms; OU=(c) 2012 Entrust, Inc. - for authorized use only; CN=Entrust Certification Authority - L1K
*  SSL certificate verify ok.
* No OCSP response received
* stopped the pause stream!
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (91) No OCSP response received
```

The site is reachable in practice, but because of this error raised by the `requests` library, I’ll have to leave out the privacy policy URL from these layers.

**Comment by 1ec5** [comment]
No dice, the privacy policy URL is required:

> ERROR:root:Error in sources/north-america/us/ky/KYAPED.geojson : sources/north-america/us/ky/KYAPED.geojson has no privacy_policy_url. Adding privacy policies to sources is important to comply with legal requirements in certain countries.

Maybe I could commit a Markdown file to this repository that links to kentucky.gov and use the URL of that file?

**Comment by Marc-marc-marc** [comment]
despite the issue with privacy policy URL, I merged it (imho it's better to add it, the https failure is a minor stuff)

**Comment by don-vip** [comment]
It seems all Kentucky imagery servers are down for a long time.

**Comment by rbuffat** [comment]
Strange. https://rbuffat.github.io/eli_watchdog -> north-america -> north-america / us / ky  did not pick them* up as failing until now (Last check was 2020-12-12 00:44:18.526772 UTC).  This means that a WMS GetCapabilities request was successful and the layer name advertised by the WMS server. But currently, they seem to be down. I will investigate further.

* = 
https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/ky/KYAPED.geojson
https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/north-america/us/ky/KYAPED_2019_6in.geojson

**Comment by don-vip** [comment]
@rbuffat Nice tool! I see you perform the same checks as us, with a much better rendering. It's broken for us since 9th December. We're running tests from a German server, maybe there a connection/network differences if your server is located in the US.

**Comment by rbuffat** [comment]
> @rbuffat We're running tests from a German server, maybe there a connection/network differences if your server is located in the US.

Good idea. I tested the server with www.site24x7.com, not sure how reliable this service is, but it looks as the server is not reachable from everywhere. I guess the server of the github action for rbuffat.github.io/eli_watchdog is somewhere in a Microsoft cloud in the US, but I'm not sure. That would explain the different behavior.

kentucky

**Comment by 1ec5** [comment]
I can still connect to the KyFromAbove layers without any problems. (I just used it to save [this changeset](https://www.openstreetmap.org/changeset/95732950).) I’m requesting these tiles from an ISP in the United States, for what it’s worth. Are you able to request tiles if you use a U.S.-based VPN?

Previously, I’ve heard about Ohio’s OSIP server also blocking overseas connections. I have no idea why they’d block non-Americans from viewing aerial imagery that has plenty of easily accessible alternatives, other than paranoia about foreign election interference or national security or something. 🤷‍♂️

/cc @Karthoo

**Pull request merged**
