### PR TITLE
ICGC Topographic imagery

### PR DESCRIPTION
**Pull request by blacx0**
Include the official ICGC Topographic imagery available for Catalonia (spain) region.

### CODE REVIEW

**Comment by rbuffat** [comment]
@blacx0 Thanks for opening this PR! Please state the link to where to find the license information for this data. This is usually the location where other metadata of the dataset can be found.

**Comment by blacx0** [comment]
It's exactly the same as the already added ICGC layer, we have an authorization from the ICGC to use any of their information under CC BY 4.0. Here is the letter they sended:
https://wiki.openstreetmap.org/w/images/4/47/20230109_CartaObertaICGC-OSM_SIGNADA.pdf

**Comment by blacx0** [comment]
Also here in english: https://www.icgc.cat/en/The-ICGC/Public-Information/Transparency/Re-use-of-the-information

**Comment by rbuffat** [comment]
@blacx0 Can you link the website where to find this information?

**Comment by blacx0** [comment]
The wms link comes from here: https://www.icgc.cat/en/Public-Administration-and-Enterprises/Services/Online-services-Geoservices/WMS-and-tiles-Reference-cartography/Fast-WMS-WMTS-of-raster-cartography/Fast-WMS-of-raster-cartography-in-UTM-coordinates

at the bottom you have the legal notice

I don't know if you need anything else

**Comment by Crashillo** [comment]
Just for the record, this GeoJSON also contains the same _license_url_ and _privacy_policy_url_ fields as [the related ICGC orthophotos PR](https://github.com/osmlab/editor-layer-index/pull/1758), which it was already merged.

**Comment by jmaspons** [comment]
The requirement for usage permission is fulfilled, @rbuffat. The `waitfor - license / usage permission` label can be removed and the PR hopefully merged.

**Comment by blacx0** [comment]
Please @rbuffat can you look at it?, if there is something missing please tell me, if not, can you merge it already?

**Comment by matheusgomesms** [comment]
Look good to me, moltes gràcies! Can you please add (if it makes sense), the same projections as the other ICGC layer?

The list is:

      "EPSG:2154",
      "EPSG:3857",
      "EPSG:4230",
      "EPSG:4258",
      "EPSG:4326",
      "EPSG:23031",
      "EPSG:25831",
      "EPSG:32631"

After that, I can merge it! :)

**Comment by Crashillo** [comment]
> the same projections as the other ICGC layer?

Actually, it has the same available projections that [GetCapabilities service](https://geoserveis.icgc.cat/icc_mapesmultibase/utm/wms/service?REQUEST=GetCapabilities) returns

**Pull request merged**
