### PR TITLE
Fix broken "Hamburg (20 cm)" source

### PR DESCRIPTION
**Pull request by rbuffat**
The WMS server has changed and thus is currently broken: https://geoportal-hamburg.de/info/DOP_GBK_Anpassungen.pdf

> Digitale Orthophotos Hamburg
> WMS Digitale Orthophotos Hamburg
> Name alt: WMS Digitale Orthophotos 20cm Hamburg
> URL alt: https://geodienste.hamburg.de/HH_WMS_DOP20
> URL neu: https://geodienste.hamburg.de/HH_WMS_DOP

The layer did not have any license URL before. The [WMS server](https://geodienste.hamburg.de/HH_WMS_DOP?REQUEST=GetCapabilities&SERVICE=WMS) includes:

```
<Fees>Nutzungsbedingungen: Datenlizenz Deutschland - Namensnennung - Version 2.0; &lt;a href="https://www.govdata.de/dl-de/by-2-0"&gt;https://www.govdata.de/dl-de/by-2-0&lt;/a&gt;; dl-de-by-2.0; Namensnennung: "Freie und Hansestadt Hamburg, Landesbetrieb Geoinformation und Vermessung"</Fees>
<AccessConstraints>Es gelten keine Zugriffsbeschränkungen,Hamburgisches Geodateninfrastrukturgesetz (HmbGDIG)</AccessConstraints>
```

I found the following page: https://metaver.de/trefferanzeige?cmd=doShowDocument&docuuid=B2013F67-EB8A-4629-8E6D-55A5F74CE129&plugid=/ingrid-group:dsc-MV
-> Verfügbarkeit 

> Zugriffsbeschränkungen
> Es gelten keine Zugriffsbeschränkungen
> 
> Nutzungsbedingungen
>  Datenlizenz Deutschland Namensnennung 2.0
> 
> Quellenvermerk: Freie und Hansestadt Hamburg, Landesbetrieb Geoinformation und Vermessung

The link to the WMS server can be found under "Verweise" -> "Weitere Verweise" -> "Dienst "WMS Digitale Orthophotos Hamburg" (GetCapabilities)"

@Klumbumbus would it be possible that you have a look at the license?

### CODE REVIEW

**Comment by rbuffat** [comment]
I found this thread https://forum.openstreetmap.org/viewtopic.php?id=19227&p=2 and https://wiki.openstreetmap.org/wiki/Contributors#Hamburg

I'm personally not familiar with the "Datenlizenz Deutschland Namensnennung 2.0"

The updated wms url is also present in josm: https://josm.openstreetmap.de/wiki/Maps/Germany#Hamburg20cm
But I'm not sure what the value of this is regarding the license.

**Comment by rbuffat** [comment]
@simonpoole are you familiar with the "Datenlizenz Deutschland Namensnennung 2.0"?

**Comment by simonpoole** [comment]
Yes, it is considered incompatible without clarification of attribution requirements.

**Comment by rbuffat** [comment]
> Yes, it is considered incompatible without clarification of attribution requirements.

@simonpoole Thanks!

The source is defunct at the moment, but there is another (working) Hamburg layer with the same information on the WMS server: https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/sources/europe/de/Hamburg-DK5.geojson 
https://geodienste.hamburg.de/HH_WMS_DK5?service=WMS&request=GetCapabilities
```
WMS Server Metadata:
Access constraints:
Nutzungsbedingungen: Datenlizenz Deutschland - Namensnennung - Version 2.0; &lt;a href="https://www.govdata.de/dl-de/by-2-0"&gt;https://www.govdata.de/dl-de/by-2-0&lt;/a&gt;; dl-de-by-2.0; Namensnennung: "Freie und Hansestadt Hamburg, Landesbetrieb Geoinformation und Vermessung"

Fees:
DE: kostenfrei fuer die kommerzielle und nicht-kommerzielle Nutzung

```

@andrewharvey @simonpoole @grischard @Klumbumbus 
Should I adopt the PR to remove both sources?

**Comment by andrewharvey** [comment]
> Should I adopt the PR to remove both sources?

Yes if @simonpoole says we need a waiver and we don't have one or other statement to that affect then we should remove the source until we get it.

**Comment by rbuffat** [comment]
I updated the PR to remove both Hamburg sources until there is a waiver available.

**Pull request merged**
