### PR TITLE
+maxzoom Bavaria-2m

### PR DESCRIPTION
**Pull request by Klumbumbus**

### CODE REVIEW

**Comment by simonpoole** [comment]
Is stating a max zoom actually necessary for a WMS server? If this is a JOSM requirement we need to have a look at all WMS defs.

**Comment by Klumbumbus** [comment]
I don't know. With this layer and without maxzoom I see grey tiles in JOSM. While e.g. VoGIS: Echtfarbenbild 2012 (12cm) works fine in JOSM even without maxzoom.

**Comment by bhousel** [comment]
Max zoom is at least useful to iD - it tells the code at which zoom to stop requesting images and switch to overzooming.  (e.g. there is no reason to ask the server for 4 z19 tiles, when we know that the z18 tile we already have loaded is as good as it gets).

I know iD don't support wms yet, but even if we did, fetching raster tiles would work the same way.

**Comment by simonpoole** [comment]
@bhousel I might be mistaken but IMHO WMS servers return which scales they support so this might simply be a misconfiguration of the WMS server in question.

**Comment by bhousel** [comment]
> @bhousel I might be mistaken but IMHO WMS servers return which scales they support so this might simply be a misconfiguration of the WMS server in question.

I'm thinking of the very simplest case where iD would send bounding box requests to EPSG:3857 supporting servers, per https://github.com/openstreetmap/iD/issues/1141#issuecomment-241298005

Specifying a `maxZoom` would help iD here.  I'm not planning to do `GetCapabilities` calls anytime soon.

**Comment by simon04** [comment]
Merged: 576198ed33d4334676aaad484479fe0a68c6002b

**Pull request closed without merging**
