### PR TITLE
basemap.at URL change 2023

### PR DESCRIPTION
**Pull request by hlfan**
Updated the URLs according to the new URL scheme as stated by [basemap.at](https://basemap.at) in this [PDF](https://cdn.basemap.at/basemap.at_URL_Umstellung_2023.pdf).
Also adapted the JSON entry order for the elevation layers.

### CODE REVIEW

**Comment by cicku** [comment]
Can you squash your commits?

**Comment by andrewharvey** [comment]
@cicku can we just use GitHub's Squash and merge?

**Review by andrewharvey — APPROVED** [review]
LGTM

**Comment by hlfan** [comment]
I don't see an option to squash it, I guess you have to

**Comment by cicku** [comment]
I will do it then, no worry because it keeps your credit.

**Pull request merged**
