### PR TITLE
Spain (Basque country): Add geoEuskadi orthophotos

### PR DESCRIPTION
**Pull request by Crashillo**
Include the official geoEuskadi aerial imagery available for the basque country (spain) region

### CODE REVIEW

**Comment by cicku** [comment]
Please explain what you are doing here.

**Comment by Crashillo** [comment]
Updated title and description

**Comment by Crashillo** [comment]
I'm noticing the checks are failing due to the geometry, but I got it from download.geofabrik.de .poly file. What's wrong with that? :thinking:

**Comment by cicku** [comment]
Does it have a year mention or always latest? Also, there are 3 coordinates with different decimal place at the bottom.

**Comment by Crashillo** [comment]
> Does it have a year mention or always latest?

Nope, all the layers I'm providing displays always the most recent photos.

> there are 3 coordinates with different decimal place at the bottom

Does it matter? I edited the polygon bounds to fit inside the bbox, so I guess geojson.io includes better precision.

**Comment by cicku** [comment]
It does not matter much because the bot may fix it later.

**Pull request merged**
