### PR TITLE
Add Turku ortophoto 2021

### PR DESCRIPTION
**Pull request by crimsondusk**
City of Turku has a new, updated ortophoto from 2021 available. This is from the same wms service as my previous pull requests.

### CODE REVIEW

**Comment by grischard** [comment]
Thank you! Do you want to rename the file with no year in it, to make life easier for 2023 crimsondusk?

**Comment by larmax** [comment]
Should [this issue](https://github.com/osmlab/editor-layer-index/issues/1530) be closed as it's being handled here now?

**Comment by cicku** [comment]
1. Logo should be: https://www.turku.fi/sites/default/files/styles/site_logo/public/sites/all/themes/custom/driveturku/images/sprites/logo.png
2. WMS is using PNG, can you change to JPEG if there isn't any huge difference? Because PNG consumes a lot more bandwidth.

**Comment by crimsondusk** [comment]
Updated the icon.

The WMS appears to only serve PNG. GetCapabilities only lists image/png, and it does not work if I request JPG.

I decided to not rename the ```turku-orto``` one because it does not have the year in the WMS layer, but I thought that having the year in the title is still a good idea. In case the WMS layer is ever updated, we need to update the title.

**Pull request merged**
