### PR TITLE
Update layers for Bavaria

### LINKED ISSUE #2437: Imagery for Bavaria: 20cm and yearly historical imagery since 2003
## URL of the imagery
See https://geodaten.bayern.de/opengeodata/OpenDataDetail.html?pn=dop20

- https://geoservices.bayern.de/od/wms/dop/v1/dop20?
- https://geoservices.bayern.de/od/wms/histdop/v1/histdop?

## Two letter country code
DE

## License
CC BY 4.0

## Is the license compatible with OSM?
Yes, and a waiver was already signed

## Attribution (text, URL, required?)
License requires attribution

## Privacy policy (URL)
https://www.ldbv.bayern.de/datenschutz.html

### PR DESCRIPTION
**Pull request by arch0345**
Replaces 80cm orthophoto with 20cm version (both use the same source)

Also adds the following layers:
- 20cm color infrared orthophoto
- Lidar/hillshade
- Bavaria topographic map
- Bavaria web map
- Parcel/building overlay
- Contour line overlay

These layers are licensed under CC BY 4.0, however [a representative from Bayerischen Vermessungsverwaltung stated](https://wiki.openstreetmap.org/w/images/b/bc/20230526_Nutzung_der_OpenData-Produkte_der_Bayer._Vermessungsverwaltung.pdf) that listing them on the Contributors page is sufficient for attribution so [this data is approved to be used for OSM](https://wiki.openstreetmap.org/wiki/Contributors#Bayerische_Vermessungsverwaltung_%E2%80%93_www.geodaten.bayern.de).

Closes #2437

### CODE REVIEW

**Comment by Swarkin** [comment]
I think it would also be great if the historical maps could be included! They are licensed under 
CC BY 4.0 as well but I dont know enough legal stuff to determine whether we are allowed to use them.
JOSM_YCAiQ7QJAF

**Comment by arch0345** [comment]
> I think it would also be great if the historical maps could be included! They are licensed under 
> CC BY 4.0 as well but I dont know enough legal stuff to determine whether we are allowed to use them.
> JOSM_YCAiQ7QJAF
> 

I was originally going to include this, but it looks like each year only covers part of the state, which would require geometries that differ from the one used from the original Bavaria 80cm geojson. I'll add them when I have a chance

**Comment by qugebert** [comment]
There is still an ongoing discussion as to whether we are even allowed to use these sources at all
https://community.openstreetmap.org/t/bayern-ab-01-01-2023-sind-viele-geobasisdaten-der-vermessungsverwaltung-kosten-frei-verfugbar-nutzbarkeit-fur-osm-ist-noch-zu-prufen/7051

**Comment by iandees** [comment]
Thanks for sharing, @qugebert. It seems that the conversation has been ongoing for a couple years. Although I am definitely not fluent in German, I don't see a conclusion that the information from @arch0345 in the description of this pull request is wrong.

**Comment by miche101** [comment]
Hi, 

There is an error in this file:

https://github.com/osmlab/editor-layer-index/blob/182db409b79a9bfd2567db84f1d70926d9d59d5d/sources/europe/de/BY_Label.geojson

From min_zoom=7 to 17 the images are CC-BY 4.0. From 18 to 22 the image changes to a CC BY ND 4.0 image

From ( CC BY 4.0 )
https://geodaten.bayern.de/opengeodata/OpenDataDetail.html?pn=dok

To  ( CC BY-ND 4.0 )
https://geodaten.bayern.de/opengeodata/OpenDataDetail.html?pn=parzellarkarte

regards 
Mike

**Comment by qugebert** [comment]
> Thanks for sharing, @qugebert. It seems that the conversation has been ongoing for a couple years. Although I am definitely not fluent in German, I don't see a conclusion that the information from @arch0345 in the description of this pull request is wrong.



The situation is simply so confusing that I can't blame anyone for wrongly assuming that we are allowed to use the sources, especially as there is even a document from the rights holder stating that the sources may be used. I'm not a lawyer and would have interpreted it the same way as @arch0345 but obviously others (who are more knowledgeable than me) have doubts that we are allowed to use the sources and as long as this is not conclusively clarified I would be careful about using them.

**Comment by arch0345** [comment]
> There is still an ongoing discussion as to whether we are even allowed to use these sources at all https://community.openstreetmap.org/t/bayern-ab-01-01-2023-sind-viele-geobasisdaten-der-vermessungsverwaltung-kosten-frei-verfugbar-nutzbarkeit-fur-osm-ist-noch-zu-prufen/7051

Thanks for pointing that out, I wasn't aware of this forum thread. After taking a quick look, it seems that besides CC BY ND sources being embedded at high zooms (which got resolved via #2456), the confirmation linked in the Wiki doesn't address the second reason for incompatibility listed in https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/

For this reason, I agree that further clarification from Bayerische Vermessungsverwaltung is needed for this to stay in ELI. I plan on reverting this PR unless if someone else is interested in contacting the data owners.


<details><summary>Some other notes</summary>

* It looks like we got special permission to use the DOP80 layer, but this isn't the case for the ones added in this PR: https://wiki.openstreetmap.org/wiki/DE:Luftbilder_aus_Bayern/Pilotprojekt#Rechtliche_Bedingungen

* I also noticed that this wiki page (https://wiki.openstreetmap.org/wiki/DE:Luftbilder_aus_Bayern) states that we're allowed to use DOP40, however this seems to point back to the same forum thread

* But DOP40 is included in Esri World Imagery?
image

</details>

**Comment by arch0345** [comment]
I've reverted this PR in #2461. Unfortunately it looks like the [DOP80 WMS endpoint has since been decommissioned](https://geodatenonline.bayern.de/geodatenonline/seiten/aktuell.html) (it says June but it was working up until a few weeks ago) so I wasn't able to add this back
image

I've created a new PR (#2462) that will add these layers back

**Comment by miche101** [comment]
hi @arch0345 ,

why revert the change? I think that is exaggerated because if you say this letter [1] is not enough. Then not only Bavaria will have to remove aerial photographs but almost all German ones. I cannot say what the situation is like in the rest of the world or whether all the documents are there. The wiki says what should be included in the letter [2], and in most cases it wasn't done that way. Unless the license ( CC0 )[3] is as free as in "NRW".

[1] - https://wiki.openstreetmap.org/w/images/b/bc/20230526_Nutzung_der_OpenData-Produkte_der_Bayer._Vermessungsverwaltung.pdf
[2] - https://osmfoundation.org/wiki/Licence/Waiver_and_Permission_Templates
[3] - https://wiki.openstreetmap.org/wiki/Import/ODbL_Compatibility

**Comment by arch0345** [comment]
I understand your frustration, this situation is very confusing for me as someone with no legal expertise. However based on what I saw on the forum thread, it looks like there hasn't really been a consensus formed on whether the email uploaded on the Wiki is sufficient. As a former member of the LWG mentioned, it's disputed whether tracing features from aerial imagery counts as a derived work. ELI seems to stay on the more legally safe side, so getting the waiver Simon linked to signed would help clear things up.

If you have any concerns about other imagery in this index, please let me know and I'll try to consult with the LWG.

**Pull request merged**
