### PR TITLE
Restore "Economic maps" for Sweden

### PR DESCRIPTION
**Pull request by magol**
It was removed in pull request #1234 as the server was offline. Now I have found another server that provide it.

### CODE REVIEW

**Comment by NKAmapper** [comment]
EPSG 3857 seems to work as well and is more efficient.
CRS:84 is redundant.

JOSM entry: https://josm.openstreetmap.de/wiki/Maps/Sweden#LantmterietEconomicMapca.1950-1978

**Comment by magol** [comment]
@NKAmapper I have updated now.
Great that you updated for JOSM, I had issues to log in to the wiki.

**Comment by magol** [comment]
I saw that they also have "Generalstabskartan" , and am wondering if it's worth adding that as well. It's even older than the economic map, but it might still be valuable for seeing place names. What do you think @NKAmapper?

* [Info about Generalstabskartan](https://ext-geodata-raster.lansstyrelsen.se/arcgis/rest/services/RasterNationellt/lst_ext_generalstabskartan/ImageServer)
* [ArcGIS for Generalstabskartan](https://www.arcgis.com/home/webmap/viewer.html?url=https%3A%2F%2Fext-geodata-raster.lansstyrelsen.se%2Farcgis%2Frest%2Fservices%2FRasterNationellt%2Flst_ext_generalstabskartan%2FImageServer&source=sd)

**Comment by NKAmapper** [comment]
Thanks, added Generalstabskartan in JOSM now (but perhaps keep the current PR separate).

**Comment by magol** [comment]
@NKAmapper I adjusted the geometry as the map surface is slightly larger on the new server compared to how it was on the old server.
I also made some adjustments to Generalstabskartan compared to what you added for JOSM.

**Comment by magol** [comment]
@NKAmapper I have now also change the url for license_url to a English page.

**Pull request merged**
