### PR TITLE
Recent French orthophotos

### PR DESCRIPTION
**Pull request by Olyon**
I add several recent photos under open license already present in JOSM. 
These are photos made by French towns, most of them on wms.openstreetmap.fr. Except one made after the passage of the storm Alex which caused damage in several French valleys.
I change old photos to "historicphoto".

### CODE REVIEW

**Comment by Olyon** [comment]
I fixed the errors, added license and attribution.
There is a problem for the Enedis source, today there is nothing on wms.openstreetmap.fr for this source, a few days ago it was working. I don't know if it's permanent.

**Comment by rbuffat** [comment]
We can merge the PR  and monitor if the source works in the near future using https://rbuffat.github.io/eli_watchdog

**Comment by don-vip** [comment]
@Olyon are you sure about the zoom decrease for Rennes 2014 and CRAIG 2019 from 21 to 20?

**Comment by Olyon** [comment]
No, I am not sure.
the Check PR indicated an error.
So I tested in a place in Josm to display the tile info then I hit the url.
For Rennes 2014, I have for example:
zoom 20: an image. https://wms.openstreetmap.fr/tms/1.0.0/rennes_2014/20/519434/364029
zoom 21: an error. https://wms.openstreetmap.fr/tms/1.0.0/rennes_2014/21/1038869/728059
Same thing for CRAIG 2019:
https://wms.openstreetmap.fr/tms/1.0.0/craig_2019/20/533464/374041
https://wms.openstreetmap.fr/tms/1.0.0/craig_2019/21/1066928/748082
So I deduced that the zoom 21 does not exist.

**Pull request merged**
