### PR TITLE
Add orthophotos for Helsinki region

### PR DESCRIPTION
**Pull request by NKAmapper**
This PR adds orthophotos for the Helsinki region, including Espoo and Vantaa

In some areas they are better than the existing national orthophotos from MML, so both have been given a "best" attribute.

Please note that tile size is 512 for this wms (tile_size).

Permission: [Link](https://forum.openstreetmap.org/viewtopic.php?pid=710304#p710304)

### CODE REVIEW

**Comment by grischard** [comment]
See #522 for the `tile_size` attribute.

**Comment by grischard** [comment]
But if it's a wms, I'm not sure I understand the `'tile_size'` attribute?

We don't have the `'valid-georeference'` attribute in ELI either. Maybe we should, but that's probably for another PR.

Can you add https://storage.theel0ja.info/imgup3/Screen%20Shot%202018-08-07%20at%2019.15.29.png to the `sources/europe/fi` directory and link to it like we did on https://osmlab.github.io/editor-layer-index/sources/australia/au/act/ACTmapi-Imagery.PDF ?

I'm happy merging Espoo and Vantaa in the same PR too.

**Comment by NKAmapper** [comment]
Ok, done. Please ignore tile size, my mistake.

Espoo, Vantaa and Helsinki are already included in this PR, so no additional imagery needed (one combined wms for all three cities).

**Comment by grischard** [comment]
Thank you!

**Comment by NKAmapper** [comment]
#339 may be closed now :)

**Pull request merged**
