### PR TITLE
add oceania/au/tas/launceston

### PR DESCRIPTION
**Pull request by andrewharvey**

### CODE REVIEW

**Comment by grischard** [comment]
Thanks!

**Comment by Klumbumbus** [comment]
These sources don't work anymore for about 4 weeks. The server returns "Your ArcGISServer license has expired."

https://mapping.launceston.tas.gov.au/arcgis/rest/services/Public/OrthoPhoto_Feb2013_10cm/MapServer/tile/13/5134/7444

**Comment by grischard** [comment]
Gah. Any thoughts @andrewharvey? Wanna ping them?

**Comment by andrewharvey** [comment]
I think they are already aware of it "Note:  Most map services are currently unavailable due to ongoing system outage 10/12/2019" http://launceston.maps.arcgis.com/home/index.html

I'd just wait and see as it might start working again.

**Comment by Klumbumbus** [comment]
cc @don-vip

**Comment by don-vip** [comment]
I've pinged them on December 13th and their reply was: 

> I apologise, yes our web services are currently down at the moment and likely be this way for another week.  
> 
> In the meantime you can access Launceston's  imagery via the Tasmanian State Government service, we jointly own the imagery over Launceston city.
> 
> Service at https://services.thelist.tas.gov.au/arcgis/rest/services/Basemaps/Orthophoto/MapServer
> 
> I hope this assists, and we appreciate the work that Open Street Map  contributors provide to the mapping of Launceston !

But the replacement is useless with its "CC BY-NC-ND 3.0 AU" license. So I'm just waiting, same as you.

**Comment by don-vip** [comment]
The Launceston test is back to stable.

**Pull request merged**
