### PR TITLE
Ukraine - Andriivska OTG 2020

### PR DESCRIPTION
**Pull request by bezdna**

### CODE REVIEW

**Comment by andrewharvey** [comment]
Thanks for the PR.

> https://zakon.rada.gov.ua/laws/show/2939-17

Is there an evaluation of this if this is compatible with OSM or not?

**Comment by bezdna** [comment]
> Thanks for the PR.
> 
> > https://zakon.rada.gov.ua/laws/show/2939-17
> 
> Is there an evaluation of this if this is compatible with OSM or not?

https://wiki.openstreetmap.org/wiki/Uk:Вікіпроект_Україна/Публічні_дані

**Comment by andrewharvey** [comment]
Thanks @bezdna seems like this has had the due diligence done and okay to be used.

**Comment by bezdna** [comment]
> Thanks @bezdna seems like this has had the due diligence done and okay to be used.

same for all other map tiles from Ukraine, please merge all other PR

**Pull request merged**
