### PR TITLE
Added Luxembourg Nordstad Lidar

### PR DESCRIPTION
**Pull request by grischard**
New source: geoportail.lu LIDAR prototype Nordstad 2017

Thanks!

### CODE REVIEW

**Comment by tyrasd** [comment]
I think the supplied geojson polygon geometry is a bit broken: [Luxembourg-GeoportailLidarPrototype.geojson](https://github.com/grischard/editor-layer-index/blob/7fb7a2747d7488ce320dcad3945a8fb17ab099b4/sources/europe/lu/Luxembourg-GeoportailLidarPrototype.geojson) shows a self-intersection in the middle. Can you please try to fix that?

Also, I seem to be able to "only" load tiles up to zoom level 21, for example [/21/1084156/712611.jpeg](https://wmts4.geoportail.lu/opendata/wmts/ortho_10cm_proto_lidar/GLOBAL_WEBMERCATOR_4_V3/21/1084156/712611.jpeg) works fine, but [/22/2168306/1425225.jpeg](https://wmts4.geoportail.lu/opendata/wmts/ortho_10cm_proto_lidar/GLOBAL_WEBMERCATOR_4_V3/22/2168306/1425225.jpeg]() returns a HTTP/400 error.

Btw: Any idea why this is called the _LIDAR_ prototype? Just wondering… :blush:

**Comment by grischard** [comment]
Thank you, I've fixed all of those now.

The orthoimagery is part of a lidar test project, see https://act.public.lu/fr/cartographie/lidar and https://data.public.lu/en/datasets/lidar-projet-pilote-dun-releve-3d-du-territoire-luxembourgeois/

**Comment by rbuffat** [comment]
@grischard @tyrasd The  [geoportail.lu LIDAR prototype Nordstad 2017](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/lu/Luxembourg-GeoportailLidarPrototype.geojson) imagery seems to be broken since 26 days.

**Comment by grischard** [comment]
I'll notify them, but also just remove that now-obsolete layer.

**Comment by rbuffat** [comment]
merci @grischard !

**Pull request merged**
