### PR TITLE
add Esri satellite imagery to list of providers

### LINKED ISSUE #357: Add ESRI World Imagery
It looks like we can now use ESRI's "World Imagery" Layer for deriving public vector data from it. :tada: For details, see https://github.com/Esri/arcgis-osm-editor/issues/104#issuecomment-323879799.

~~Related ticket on iD's issue tracker: https://github.com/openstreetmap/iD/issues/4164~~

### PR DESCRIPTION
**Pull request by jgravois**
resolves #357 

- [x] substitute a real base64 encoded Esri logo
- [x] create [new](https://wiki.openstreetmap.org/wiki/Esri) OpenStreetMap wiki page
- [ ] ?

### CODE REVIEW

**Comment by jgravois** [comment]
still waiting on a confirmation email to create the new wiki page.

does this copy work for everyone?

---

> **Esri** ([/ˈɛzriː/](https://en.wikipedia.org/wiki/Help:IPA/English), a.k.a. Environmental Systems Research Institute) is an international supplier of [geographic information system](https://en.wikipedia.org/wiki/Geographic_information_system) (GIS) software, web GIS and [geodatabase](https://en.wikipedia.org/wiki/Spatial_database#Geodatabase) management applications. The company is headquartered in [Redlands](https://en.wikipedia.org/wiki/Redlands,_California), [California](https://en.wikipedia.org/wiki/California).

> ### Esri partnership
---

> As of Aug 21 2017, Esri announced availability of satellite imagery to the OSM community directly through their existing [World Imagery Service](http://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9).

> Esri World Imagery provides one meter or better satellite and aerial imagery in many parts of the world and lower resolution satellite imagery worldwide. The map includes 15m TerraColor imagery at small and mid-scales (~1:591M down to ~1:72k) and 2.5m SPOT Imagery (~1:288k to ~1:72k) for the world. The map features 0.3m resolution imagery in the continental United States and parts of Western Europe from DigitalGlobe. Additional DigitalGlobe sub-meter imagery is featured in many parts of the world. In the United States, 1 meter or better resolution NAIP imagery is available. In other parts of the world, imagery at different resolutions has been contributed by the GIS User Community. In select communities, very high resolution imagery (to 0.03m) is available down to ~1:280 scale. You can contribute your imagery to this map and have it served by Esri via the [Community Maps Program](https://livingatlas.arcgis.com/en/participate/#v=community&subTab=what-to-contribute). View the list of [Contributors for the World Imagery Map](http://esriurl.com/WorldImageryContributors).

> Sources: Esri, DigitalGlobe, Earthstar Geographics, CNES/Airbus DS, GeoEye, USDA FSA, USGS, Getmapping, Aerogrid, IGN, IGP, and the GIS User Community

> ### Using Esri imagery in editors
---
> The easiest way to do this is to select the “Esri satellite imagery” layer as an option in either iD or JOSM.

> **Legal permissions**

> Esri and its imagery contributors grant Users the non-exclusive right to use the World Imagery map to trace features and validate edits in the creation of vector data. Users that create vector data from the World Imagery map may want to publicly share that vector data through a GIS data clearinghouse of its own or through another open data site. This public sharing could be achieved through [ArcGIS Open Data](https://hub.arcgis.com/datasets?q=buildings) or the OpenStreetMap (OSM) Initiative. For ArcGIS users that want to contribute such vector data to OSM, Esri provides applications and services directly accessible from ArcGIS platform. Users acknowledge that any vector data contributed to OSM is then governed by and released under the OpenStreetMap License (e.g. ODbL).

> Except for the additional limited rights granted above, any and all other uses of the World Imagery map remain subject to the terms and conditions set forth in the Esri Master Agreement or Terms of Use, as applicable. Esri and its imagery contributors retain all right, title, and interest in and to their respective imagery data contributed to the World Imagery map.

 > For More Info, visit: http://goto.arcgisonline.com/maps/World_Imagery

> Attribution should be `source=Esri`.

> Helpful information about [Using Imagery](https://wiki.openstreetmap.org/wiki/Using_Imagery) to be aware of.

**Comment by bhousel** [comment]
Thanks for this @jgravois!  It is exciting to have another global imagery source available for OpenStreetMap users 👍 

The only comment I have is about:
>Attribution should be `source=Esri.`

We don't actually enforce users adding a `source` tag in iD (although the next release will make this easier to do, see https://github.com/openstreetmap/iD/pull/4223#issuecomment-322561014). 
 
iD will automatically add a changeset tag like `imagery_used=EsriImagery`, if a user has activated this layer while they edit.  This string is just taken from the imagery `id` property.  You could set the `id` to `Esri` if you want - it doesn't really matter what the `id` is, as long as it doesn't conflict with anything or contain url-unsafe characters.

**Comment by jgravois** [comment]
good to know! full confession though, i blindly copied that part from [DigitialGlobe's](https://wiki.openstreetmap.org/wiki/DigitalGlobe#Legal_permissions) wiki page 😸 .

given that the **Data Collection and Editing Uses Permitted** doesn't explicitly call out including attribution as a requirement, i think its safe to just :hocho: it.

**Comment by slibby** [comment]
@jgravois I would suggest using `EsriWorldImagery` as the `id` if you're OK with that?

**Comment by jgravois** [comment]
good suggestion @slibby. and thanks for the help creating the wiki page!

we are ready for takeoff! 🚀

**Comment by bhousel** [comment]
So exciting!  Thanks again @jgravois @slibby & and the rest of the ESRI team!!

**Comment by tyrasd** [comment]
@jgravois @slibby – does the permission above also apply to the (new?) [_World Imagery (Clarity)_](https://www.arcgis.com/home/item.html?id=ab399b847323487dba26809bf11ea91a) (`https://clarity.maptiles.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/tile/{zoom}/{y}/{x}`) layer? If yes, we'd love to add that layer to this repository as well, given that some osm mappers seem to prefer this one over the updated standard _ESRI World Iagery_ in some locations (discussion [1](https://www.reddit.com/r/openstreetmap/comments/7punq5/esri_world_gallery_layer_doesnt_work_in_editing/), [2](https://forum.openstreetmap.org/viewtopic.php?id=60988)).

**Comment by jgravois** [comment]
I'll confirm internally. if Clarity can be used in OSM editors I'll submit another PR to add it as another canonical background layer.

**Comment by bhousel** [comment]
Thanks @jgravois 👍

**Comment by jgravois** [comment]
we have updated the [World Imagery (Clarity)](https://www.arcgis.com/home/item.html?id=ab399b847323487dba26809bf11ea91a) Terms of Use to grant approval to the OSM community to generate features from this layer as well.

since **Clarity** is still technically a _Beta_ service, some Esri folks have reservations about updating the canonical OSM provider list to include it. i'll keep trying to convince them, but in the interim please feel free to tell users that it is 100% kosher to supply the url @tyrasd shared manually.

**Pull request merged**
