### PR TITLE
Add vgin sources (new links)

### PR DESCRIPTION
**Pull request by jonahadkins**

### CODE REVIEW

**Comment by grischard** [comment]
Thanks! Looks ok to me if those conflicts are resolved.

**Comment by jonahadkins** [comment]
dunzo 👍

**Comment by grischard** [comment]
It now says:

`ERROR:root:Error in sources/north-america/us/va/VGINBuildingFootprints.geojson : {z} found instead of {zoom} in tile url`

**Comment by jonahadkins** [comment]
re-dunzo 👍 (soooory for all the issues)

**Comment by grischard** [comment]
Looks perfect!

**Pull request merged**
