### PR TITLE
Update OS Open Map Local

### LINKED ISSUE #1362: New GB OS Imagery Oct 2021
The file: [../europe/gb/OSOpenMapLocal.geojson](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/gb/OSOpenMapLocal.geojson) (added by @TurnrDev ) currently refers to the April 2021 imagery in GB, which is currently being hosted at [os.openstreetmap.org](https://os.openstreetmap.org/) and is usable within iD.

However, @Firefishy uploaded the new [October 2021 imagery](https://github.com/openstreetmap/chef/pull/471) to the same server, which I believe is accessible via the URL structure: https://{switch:a,b,c}.os.openstreetmap.org/layer/gb_os_om_local_2021_10/{zoom}/{x}/{y}.png

Does the editor-layer-index prefer a new reference file for the new imagery, or could the existing [../europe/gb/OSOpenMapLocal.geojson](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/europe/gb/OSOpenMapLocal.geojson) file be updated to make use of the newest image data?

### PR DESCRIPTION
**Pull request by Cj-Malone**
Fixes #1362

### CODE REVIEW

**Comment by boothym** [comment]
Is there an issue with this or is it ready to be merged?

**Comment by Cj-Malone** [comment]
I made a similar edit to the JOSM imagery, and it's working great there.

**Comment by boothym** [comment]
Yeah I've used it as a custom layer in iD, but I was meaning why has it not been merged into ELI?

**Review by TurnrDev — APPROVED** [review]

**Comment by rbuffat** [comment]
@Cj-Malone @boothym Sorry for the long delay. There is nothing wrong with the PR, it is just that the current work lead is/was higher than the available time and I guess the PR slipped too fast down.

**Pull request merged**
