### PR TITLE
oceania/au/nsw include LHI in TopoMap (#743), thanks @andrewharvey @GenericError

### PR DESCRIPTION
**Pull request by andrewharvey**
this superseeds #735

cc @GenericError

### CODE REVIEW

**Comment by grischard** [comment]
Can we simply include the whole ocean? No mappers go there, and it simplifies the polygon.

**Comment by andrewharvey** [comment]
> Can we simply include the whole ocean? No mappers go there, and it simplifies the polygon.

Err I'd rather not since it technically doesn't cover the ocean. It would be misleading to say it's covered there, but in reality it's not. Is there an issue with multiple Polygon rings?

**Comment by GenericError** [comment]
Late follow up, but thank you for going ahead and modifying it. I second that it shouldn't include the ocean unless it is necessary.

**Comment by grischard** [comment]
It's not 'necessary' but the geojson is 2 MB already, and the points don't add any value for our purpose since no one will ever map the ocean.

We already do this for the LPI NSW Base Map, and for many sources elsewhere - see Spain on https://osmlab.github.io/editor-layer-index/ for a good example.

If there is any land in that polygon or anything mappers would potentially want to map, we shouldn't do it of course.

**Comment by Klumbumbus** [comment]
I would use the middle way. Use about 5 nodes for the coastline of australia and one (or two) rectangle(s) for the two islands. This way you have only a handful of nodes more than the current shape, while it is nearly as exact as the first version and it doesn't falsify the shape that much.

**Comment by andrewharvey** [comment]
> It's not 'necessary' but the geojson is 2 MB already,

There are many options to compress this for downstream users who need smaller file sizes without sacrificing quality of the data, like Mapbox Vector Tiles or geobuf or flatgeobuf. So I still think the original one I proposed at https://github.com/osmlab/editor-layer-index/blob/e31f75bb8d9b8bc071f29c0eb71f48c197c37ff5/sources/oceania/au/nsw/NSW-LPI-WebServices-TopographicMap.geojson is the one we should use, it's not like we have the coastline traced out here, it's just a very rugged footprint polygon.

>  points don't add any value for our purpose since no one will ever map the ocean.

They show the footprint more accurately. There are many other sources where have the same level of detail and it's absolutely important for editors to have that precision if they are editing on the boundary of the coverage.

> We already do this for the LPI NSW Base Map

Because the LPI NSW Base Map does cover that area, it's an accurate representation of the footprint.

**Comment by grischard** [comment]
We don't need to show the footprint accurately though - for what purpose would we do that? We need the editors to get the imagery over land, and that's it.

Very good idea for vector tiles - I was thinking it could be part of a solution to #586?

**Comment by andrewharvey** [comment]
@grischard  End of the day each of these files are only 1.7K compressed, that's tiny. I took some time to reduce the coordinate precision in my version at https://github.com/osmlab/editor-layer-index/pull/743/commits/e811a01b70a08b9971fca27f3e7cf0f77852b67a, but I realised I probably still can't convince you so, I've reinstated your version.

I'd still much prefer it not covering the ocean if there is no actual content here, but it's not worth our time to argue over this so let's just merge this.

**Comment by grischard** [comment]
You actually made me laugh out loud. I hope I'm not that stubborn :).

The build script actually simplifies coordinates to, IIRC, five digits after the comma.

It would actually be interesting to see what the biggest source files are.

**Pull request merged**
