### PR TITLE
add NRW orhtophoto and dtm hillshade

### PR DESCRIPTION
**Pull request by rbuffat**
Add orthophto and dtm hillshade (requested in https://github.com/osmlab/editor-layer-index/issues/851)

The license for both sources is  „Datenlizenz Deutschland – Zero“ (https://www.govdata.de/dl-de/zero-2-0)
https://www.bezreg-koeln.nrw.de/brk_internet/geobasis/lizenzbedingungen_geobasis_nrw.pdf

```
INFO:root:Processing sources/europe/de/NRW_dtm_wms.geojson
INFO:root:AccessConstraints: NONE
INFO:root:Fee: Die Geobasisdaten des amtlichen Vermessungswesens werden als öffentliche Aufgabe gem. VermKatG NRW und gebührenfrei nach Open Data-Prinzipien über online-Verfahren bereitgestellt. Nutzungsbedingungen: siehe http://www.bezreg-koeln.nrw.de/brk_internet/geobasis/lizenzbedingungen_geobasis_nrw.pdf
INFO:root:Finished processing sources/europe/de/NRW_dtm_wms.geojson
INFO:root:Processing sources/europe/de/NRW_ortho_wms.geojson
INFO:root:AccessConstraints: NONE
INFO:root:Fee: Die Geobasisdaten des amtlichen Vermessungswesens werden als Ã¶ffentliche Aufgabe gem. VermKatG NRW und gebÃ¼hrenfrei nach Open Data-Prinzipien Ã¼ber online-Verfahren bereitgestellt. Nutzungsbedingungen: siehe http://www.bezreg-koeln.nrw.de/brk_internet/geobasis/lizenzbedingungen_geobasis_nrw.pdf
INFO:root:Finished processing sources/europe/de/NRW_ortho_wms.geojson

```

### CODE REVIEW

**Comment by pathmapper** [comment]
This is great, these are the official governmental orthophotos with 10cm resolution. 

@andrewharvey any idea when this will be merged?

**Comment by andrewharvey** [comment]
> @andrewharvey any idea when this will be merged?

I try to help out with reviewing PRs where I can, but there has been a lot of activity here (which is great! and I'm glad to see), but it can be overwhelming so if there are others who want to help out with reviewing PRs I can try to help get you permissions. Really the point of the review is just to make sure things look reasonable and check that the license is clear, the automated checks do the rest of the work.

**Comment by pathmapper** [comment]
Thanks @andrewharvey 👍 

> if there are others who want to help out with reviewing PRs I can try to help get you permissions. 

Sure, I'm happy to help out reviewing PRs if wanted/needed.

**Comment by Elefant-aus-Wuppertal** [comment]
Yeah, it worked today! Thank you very much for all of your work!

**Pull request merged**
