### PR TITLE
Set best to false of NJ imagery

### PR DESCRIPTION
**Pull request by cicku**
https://github.com/openstreetmap/iD/issues/8777

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks! This was driving me nuts too..

**Comment by bhousel** [comment]
Actually might be better to just remove the `best` prop.  I don’t know what `best: false` will actually do.

**Comment by cicku** [comment]
I noticed that Go Map is having trouble understanding best = false though.

**Comment by rbuffat** [comment]
We could drop `best: false` in the script that generates the imagery.geojson?

**Pull request merged**
