### PR TITLE
Poland geoportal update

### PR DESCRIPTION
**Pull request by Asteliks**
This PR solves issue https://github.com/osmlab/editor-layer-index/issues/1060 and adds three new sources form Geoportal 2:

- building layouts map,
- street names,
- address points

### CODE REVIEW

**Comment by Asteliks** [comment]
@rbuffat could you help with this failed check? I'm having trouble understanding what the problem is. When trying the test locally I get no errors:
image

**Comment by Asteliks** [comment]
@rbuffat Could you help with this error? I am having a hard time understanding it. I’ve tried the test locally, but all the changes have passed it without a problem:
image

**Comment by rbuffat** [comment]
@Asteliks I think this is this issue: https://github.com/osmlab/editor-layer-index/issues/1039 There is currently a bug that the list of changed files causes an error when passed to the script when a filename contains some characters (such as `(` or `)`).

**Comment by Asteliks** [comment]
@rbuffat OK. Thanks! In that case since this is not an error on my side I'm requesting a merge

**Comment by Asteliks** [comment]
@rbuffat but over here something is still wrong 
Edit: If I’m reading this right you can re-run the test without me: https://docs.github.com/en/actions/managing-workflow-runs/re-running-a-workflow

**Comment by rbuffat** [comment]
> sources/europe/pl/Geoportal2EwidencjabudynkówWMS.geojson

WMS Access constraints:
```
There shall be no restriction on the use of the service, except for the automatic extraction and collection of images or descriptive information extracted using the GetFeatureInfo feature (harvesting). There shall also be no restriction on the generation and further use of information which results from the direct use of the service or the aggregation of its content with other spatial data.
```

> sources/europe/pl/Geoportal2Nazwyulic.geojson

```
INFO:root:AccessConstraints: b'otherRestrictions'
INFO:root:Fee: b'no conditions apply'
```

> sources/europe/pl/Geoportal2Orthophotomap(aerialimage).geojson

```
There shall be no restriction on the use of the service, except for the automatic extraction and collection of images (image harvesting). There shall also be no restriction on the generation and further use of information which results from the direct use of the service or the aggregation of its content with other spatial data.
```

> sources/europe/pl/Geoportal2OrthophotomapHighQuality(aerialimage).geojson
```
INFO:root:AccessConstraints: b'No restrictions on public access'
INFO:root:Fee: b'Use of the spatial data service constitutes acceptance without limitation or qualification of the Terms and Conditions available on the Geoportal website http://www.geoportal.gov.pl/'
```

> sources/europe/pl/Geoportal2Punktyadresowe.geojson

```
INFO:root:AccessConstraints: b'otherRestrictions'
INFO:root:Fee: b'no conditions apply'
```

**Comment by Asteliks** [comment]
I do not see what is wrong with that, could you elaborate on your replay? According to my information we can use these layers.

**Comment by rbuffat** [comment]
@Asteliks Nothing wrong. I just try to document the situation that hopefully in X years it is possible to understand the context regarding license etc. 


See also: https://github.com/osmlab/editor-layer-index/issues/960#issuecomment-720652663 and https://wiki.openstreetmap.org/wiki/Geoportal.gov.pl

https://www.geoportal.gov.pl/regulamin:

> SERVICE REGULATIONS - www.geoportal.gov.pl
> 
> § 1.
> 
> GENERAL PROVISIONS
> 
> These regulations define the terms and conditions of operation and use of the website www.geoportal.gov.pl (hereinafter referred to as the Website ), including in particular the rights and obligations of website users and the Administrator.
> The provisions of the regulations constitute the sole basis for the above rights and obligations, with the exception of circumstances governed by applicable law.
> The Website Administrator within the meaning of the Act of 18 July 2002 on the provision of electronic services. (Journal of Laws of 2002, No. 144, item. 1204, as amended) is the Chief National Surveyor.
> § 2.
> 
> INFORMATION SERVICES
> 
> The Website publishes public and publicly available information.
> The website allows searching for information and combining information from the resources of various suppliers into a coherent whole and presenting it in graphic form.
> The information presented on the Website is for illustrative purposes only and under no circumstances may it be treated as an official document. Nor can they be the basis for any administrative or official activities.
> § 3.
> 
> RESPONSIBILITY
> 
> Information published on the Website in accordance with Art. 4 section 2 of the Act on Copyright and Related Rights (Journal of Laws of 1994, item 83, as amended) are not subject to the protection provided for by the above-mentioned law.
> Publication of materials from the Website is allowed provided that information about the source of origin is provided.
> The Website Administrator is not responsible for the correctness and accuracy of the data provided therein.
> The User uses the information published on the Website at his own risk.
> The Website Administrator is not responsible for any disruptions in the operation of the IT system resulting from unauthorized actions of users, force majeure or interference of third parties.
> § 4.
> 
> FINAL PROVISIONS
> 
> The Regulations enter into force on August 26, 2019.
> The Administrator reserves the right to unilaterally change the provisions of the Regulations at any time and without having to justify the reason.
> The Administrator reserves the right to leave complaints unrecognized if they result from ignorance of the provisions of these Regulations or the provisions of applicable law.
> The Administrator is not liable for damages resulting from incorrect information posted on the Website . Liability for lost profits is excluded. 
> The User using the Website declares that he has read the Regulations of the Website and accepts its terms.

**Comment by rbuffat** [comment]
Thanks @Asteliks !

**Comment by Asteliks** [comment]
And thank you too @rbuffat

**Comment by maro-21** [comment]
Thanks for adding this, but all the descriptions and names should be in English, please fix it.

**Comment by Asteliks** [comment]
> Thanks for adding this, but all the descriptions and names should be in English, please fix it.

All the layer names have been settled with the management of Geoportal and can not be changed under any circumstances. They need to be able to find these layers in our system with ease and by the names given to us.

**Comment by maro-21** [comment]
Don't worry, I will translate them into Polish like they are now. But for other languages, we have to provide English text to translate - translations into other languages are from English only.

* `Geoportal 2 Nazwy ulic` -> `Geoportal 2: Street names`
* `Geoportal 2: Punkty adresowe` -> `Geoportal 2: Addresses`
* `Geoportal 2: Ewidencja budynków WMS` -> `Geoportal 2: Buildings`
----
* Ortofotomapa o rozdzielczości 10 cm lub większej. Dane posortowane są wg rozdzielczości a następnie wg aktualności, np. arkusz z 2012 roku o rozdzielczości 8 cm przysłania arkusz z 2019 roku o rozdzielczości 10 cm.
* English: `Orthophoto with a resolution of 10 cm or higher. The data is sorted by resolution and then by date, e.g. a 2012 sheet with 8 cm resolution obscures a 2019 sheet with 10 cm resolution.`
----
* I think we can get rid of descriptions like: `Usługa przeglądania WMS Krajowa Integracja Numeracji Adresowej umożliwiająca pobieranie obrazów mapowych utworzonych na podstawie danych przestrzennych z Państwowego Rejestru Granic w zakresie ewidencji ulic i adresów.` because they don't bring any useful information. All of the layers are WMS so this description should be shortened. For example:
* English: `Based on data by National Register of Boundaries (PRG).`
----
* This should be deleted: `Usługa przeglądania (Web Map Service,WMS) umożliwiająca przeglądanie ortofotomap dla obszaru Polski. Dane udostępniane za pomocą tej usługi stanowią ortofotomapę wykonaną ze zdjęć lotniczych. Usługa oferuje wsparcie dla interfejsu WMS 1.3.0.` - in iD and other editors there are no descriptions like "This is WMS" - people don't have to know it. In descriptions there is usually information like the resolution of a layer.
----
* Similar with: `Usługa Krajowa Integracja Ewidencji Gruntów jest usługą zbiorczą prezentacji danych ewidencyjnych pochodzących bezpośrednio z jednostek szczebla powiatowego. Usługa zawiera jedynie dane tych jednostek, które dysponują usługą WMS o odpowiednich parametrach i zdecydowały się włączyć swoją usługę WMS do usługi zbiorczej KrajowaIntegracjaEwidencjiGruntow.` - this isn't information we want to provide to an average iD user.

**Comment by Asteliks** [comment]
Well, what can I tell you. You are a bit lite for the party, the changes have already been merged. This could be updated in the next PR. As for the descriptions they are also required the way they are.

**Comment by rbuffat** [comment]
@maro-21 This sounds like a reasonable suggestion. Would you be willing to make a PR for this? Otherwise, I could try to create one based on your suggestions.

**Comment by Asteliks** [comment]
Note for future changes:
For some reason when opening the id editor it opens with the wrong layer as default. It chooses the street names (red) overlay where as it should be the orthophoto layer (green). @rbuffat any suggestions how can I fix this?

image

**Pull request merged**
