### PR TITLE
Create TW NLSC EMAP layers.

### PR DESCRIPTION
**Pull request by chihchun**
Add two layers from Taiwan National Land Surveying and Mapping Center, which are license under Taiwan Government Open Data license[1].

[1] http://data.gov.tw/license#eng

### CODE REVIEW

**Comment by tyrasd** [comment]
@chihchun: Are you sure we can use these layers under the mentioned license? At least in the English translations, it sounds like as if there's a rather strict attribution requirement (see below) which is hard to fulfill in OSM (see [this table](https://wiki.openstreetmap.org/wiki/Import/ODbL_Compatibility)). But I do see that the source is already mentioned [on the osm wiki](https://wiki.openstreetmap.org/wiki/Contributors#Taiwan). :thinking: 

> 3.2. When User makes use of the Open Data and its Derivative Work, he/she must make an explicit notice of statement as attribution requested in the Exhibit below by the Data Providing Organization. If User fails to comply with the attribution requirement, the rights granted under this License shall be deemed to have been void ab initio.

**Comment by tyrasd** [comment]
A few remarks to the imagery itself, regardless of licensing issues:

* As far as I can see, these two layers are identical except for the additional contour lines on one of them. Does it really make sense to have both of them in the index? I mean, to me it looks like as if the contour lines are a good addition and don't hinder the visibility of the rest of the map. So, the map without contour lines should probably be dropped from this PR. Or was there a specific reason for having both layers in here?
* In my opinion, we shouldn't mark a layer with `"best": true` if it is not an aerial imagery. This is because we should always encourage people to map what is on the ground and not just copy from a map or other "official" source (which may be implied when we display such a map by default in a specific region).

**Comment by chihchun** [comment]
@tyrasd The Taiwan OSM community posted the tiles link in the [contributor page](https://wiki.openstreetmap.org/wiki/Contributors#Taiwan) because we believe it can be used under 'Creative Commons Attribution License 4.0 International', and holder agrees on the attribution requirements.

> 4.2. The License is compatible with the Creative Commons Attribution License 4.0 International. This means that when the Open Data is provided under the License, User automatically satisfies the conditions of this License when he/she makes use of the Open Data in compliance with the Creative Commons Attribution License 4.0 International thereafter. - http://data.gov.tw/node/18250

The local community had the several meetings[1] with the minister of Taiwan government to sort out the legal issues[2] during the license been designed. (Sorry, meeting minutes are in Chinese).  

However, we do not have a written agreement about the attribution requirement , though.

[1] https://osmtw.hackpad.com/ep/group/ris0k0TIuFZ
[2] https://osmtw.hackpad.com/Open-Geo-Data-for-Government-legal-issues#Open-Geo-Data-for-Government-legal-issues

**Comment by chihchun** [comment]
- fair enough, I agreed that we can just keep the map with contour lines.
- I also agree on removing "best": true. Even though the open data version of the map does not provide the name for lane or alley, the mapper needs to do the site survey to collect the information.
- The original idea was to provide the [borders](https://gist.github.com/chihchun/349fcc643cc6fe46738b0eb569c4db6e). Because there are some small islands are more close to mainland China, the NLSC map does provide the data for the small islands. But the MultiPolygon is quite complex, so I provided a boundary box just big enough to cover all of the islands, and small enough to be cover by the WMTS server.

**Comment by tyrasd** [comment]
Thanks a lot for the quick clarification about the license and the adaptions! Regarding the bounding polygon: couldn't we use a simplified polygon, e.g. like this one: https://gist.github.com/tyrasd/c54293956f99fcc6cd7b52c006701463 ?

**Comment by Klumbumbus** [comment]
We can use the one from JOSM https://josm.openstreetmap.de/mapsview?entry=Taiwan%20e-Map%20Open%20Data%20%28with%20Contour%20Line%29

I can convert it to geojson.

**Comment by tyrasd** [comment]
ok, let's use that one, @Klumbumbus can you please do the conversion?

**Comment by Klumbumbus** [comment]
```
      "geometry":{
        "type":"Polygon",
        "coordinates":[
          [
            [
              [
                120.4570579,
                26.3970586
              ],
              [
                120.4425600,
                26.3708009
              ],
              [
                120.4471300,
                26.3531513
              ],
              [
                120.4673009,
                26.3405831
              ],
              [
                120.4978723,
                26.3340866
              ],
              [
                120.5141036,
                26.3401594
              ],
              [
                120.5341168,
                26.3641649
              ],
              [
                120.5297045,
                26.3842128
              ],
              [
                120.4956661,
                26.4015754
              ],
              [
                120.4570579,
                26.3970586
              ]
            ],
            [
              [
                119.9007221,
                25.9858609
              ],
              [
                119.8960071,
                25.9648902
              ],
              [
                119.9131301,
                25.9470399
              ],
              [
                119.9503542,
                25.9278478
              ],
              [
                119.9905563,
                25.9260623
              ],
              [
                120.0198392,
                25.9363284
              ],
              [
                120.0277804,
                25.9557423
              ],
              [
                120.0275322,
                25.9845224
              ],
              [
                119.9989937,
                26.0010288
              ],
              [
                119.9404278,
                26.0028131
              ],
              [
                119.9007221,
                25.9858609
              ]
            ],
            [
              [
                122.089,
                24.5485000
              ],
              [
                121.709,
                23.4541000
              ],
              [
                121.717,
                22.698
              ],
              [
                121.818,
                21.950
              ],
              [
                121.803,
                21.8735000
              ],
              [
                121.759,
                21.8087000
              ],
              [
                121.694,
                21.7653000
              ],
              [
                120.861,
                21.5631000
              ],
              [
                120.815,
                21.5576000
              ],
              [
                120.739,
                21.5728000
              ],
              [
                120.661,
                21.6296000
              ],
              [
                120.202,
                22.1809000
              ],
              [
                119.270,
                23.0542000
              ],
              [
                119.153,
                23.2049000
              ],
              [
                119.128,
                23.2485000
              ],
              [
                119.103,
                23.400
              ],
              [
                119.118,
                23.4765000
              ],
              [
                119.137,
                23.512
              ],
              [
                119.361,
                23.8885000
              ],
              [
                119.406,
                23.9407000
              ],
              [
                120.968,
                25.2284000
              ],
              [
                121.408,
                25.4687000
              ],
              [
                121.989,
                25.8147000
              ],
              [
                122.065,
                25.8299000
              ],
              [
                122.141,
                25.8147000
              ],
              [
                122.216,
                25.7663000
              ],
              [
                122.260,
                25.7015000
              ],
              [
                122.297,
                25.480
              ],
              [
                122.196,
                24.9696000
              ],
              [
                122.089,
                24.5485000
              ]
            ],
            [
              [
                116.6855033,
                20.8547596
              ],
              [
                116.6309071,
                20.8149565
              ],
              [
                116.5941695,
                20.7600846
              ],
              [
                116.5797214,
                20.6967501
              ],
              [
                116.5893056,
                20.6325865
              ],
              [
                116.6217660,
                20.5753367
              ],
              [
                116.6731874,
                20.5319171
              ],
              [
                116.7373678,
                20.5075783
              ],
              [
                116.8065659,
                20.5052653
              ],
              [
                116.8724354,
                20.5252581
              ],
              [
                116.9270316,
                20.5651373
              ],
              [
                116.9637692,
                20.6200797
              ],
              [
                116.9782173,
                20.6834462
              ],
              [
                116.9686331,
                20.7475883
              ],
              [
                116.9361727,
                20.8047732
              ],
              [
                116.8847512,
                20.8481147
              ],
              [
                116.8205709,
                20.8723990
              ],
              [
                116.7513728,
                20.8747063
              ],
              [
                116.6855033,
                20.8547596
              ]
            ],
            [
              [
                118.2261504,
                24.4563345
              ],
              [
                118.2936439,
                24.4538527
              ],
              [
                118.2851467,
                24.4751026
              ],
              [
                118.3097372,
                24.4916821
              ],
              [
                118.3767709,
                24.4729348
              ],
              [
                118.4100947,
                24.5332285
              ],
              [
                118.4479031,
                24.5284069
              ],
              [
                118.4746394,
                24.4599272
              ],
              [
                118.5129920,
                24.4315479
              ],
              [
                118.5065839,
                24.4202318
              ],
              [
                118.4811625,
                24.4332439
              ],
              [
                118.4610567,
                24.4089192
              ],
              [
                118.4261450,
                24.3970385
              ],
              [
                118.3970055,
                24.4284184
              ],
              [
                118.3765564,
                24.4258395
              ],
              [
                118.3397565,
                24.3814628
              ],
              [
                118.3031926,
                24.3705764
              ],
              [
                118.2574234,
                24.4139213
              ],
              [
                118.1381276,
                24.3724838
              ],
              [
                118.1617342,
                24.4022433
              ],
              [
                118.2094226,
                24.4139604
              ],
              [
                118.1895784,
                24.4352201
              ],
              [
                118.2176338,
                24.4302050
              ],
              [
                118.2261504,
                24.4563345
              ]
            ],
            [
              [
                120.2234496,
                26.3004500
              ],
              [
                120.2550843,
                26.3100412
              ],
              [
                120.2698880,
                26.3368716
              ],
              [
                120.2591889,
                26.3652192
              ],
              [
                120.2292544,
                26.3784823
              ],
              [
                120.1976197,
                26.3688968
              ],
              [
                120.1828160,
                26.3420738
              ],
              [
                120.1935151,
                26.3137205
              ],
              [
                120.2234496,
                26.3004500
              ]
            ],
            [
              [
                119.4374461,
                25.0047541
              ],
              [
                119.4342024,
                24.9886249
              ],
              [
                119.4541901,
                24.9722553
              ],
              [
                119.4827444,
                24.9718376
              ],
              [
                119.4898402,
                24.9937882
              ],
              [
                119.4715877,
                25.0069239
              ],
              [
                119.4374461,
                25.0047541
              ]
            ],
            [
              [
                119.8869914,
                26.1803810
              ],
              [
                119.8932270,
                26.1203128
              ],
              [
                119.9285109,
                26.1080224
              ],
              [
                119.9779388,
                26.1223611
              ],
              [
                120.0366775,
                26.1517280
              ],
              [
                120.1098054,
                26.2134921
              ],
              [
                120.1192690,
                26.2713663
              ],
              [
                120.0629175,
                26.3172592
              ],
              [
                119.9923706,
                26.3164881
              ],
              [
                119.9467732,
                26.2898799
              ],
              [
                119.9020362,
                26.2439761
              ],
              [
                119.8869914,
                26.1803810
              ]
            ]
          ]
        ]
      }
```

**Comment by chihchun** [comment]
@Klumbumbus Thank you, PR updated with the GeoJSOn.

**Comment by Klumbumbus** [comment]
{z} should be changed to {zoom} in the URL

**Comment by chihchun** [comment]
oops, fixed. (but the PR is closed, github does not generate a new change)

**Comment by tyrasd** [comment]
I've manually cherry-picked the fix in 4ce978c948dcc92fe4900db9faf1a0891c9fbca1. Thanks!

**Comment by woodpeck** [comment]
Pardon me for piggybacking onto this old issue. DWG has received a complaint about someone using an imagery layer in ID that is shown like this: "Custom (http://maps.nlsc.gov.tw/S_Maps/wmts/EMAP5/default/EPSG:3857/{z}/{y}/{x})", or: "Custom (https://wmts.nlsc.gov.tw/wmts/EMAP/default/EPSG:3857/{z}/{y}/{x}") - we are told that this imagery is *not* part of the "open" data and must not be used. Is anyone in this thread able to comment on the issue?

**Comment by chihchun** [comment]
@woodpeck correct, These two tiles you mentioned are not licensed under Taiwan Government Open Data license. The difference is the open data version does not provide the house number, also fewer details of map features.

**Pull request merged**
