### PR TITLE
Switch from travis to github workflows

### LINKED ISSUE #981: Travis sunsetting?
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

We will get 1000 free minutes before we have to do something.

### PR DESCRIPTION
**Pull request by rbuffat**
This PR switches the CI from travis to github actions and eventually fixes https://github.com/osmlab/editor-layer-index/issues/981

- [x] Add github workflow with strict checks for pull requests
- [x] Add github workflow that runs basic checks, exports imagery.* files and deploy to gh-pages when something is pushed to the repository
- [x] Validate imagery.xml against the maps.xsd schema from JOSM
- [x] Missing: migrate i18n script / Transifex
- [x] Missing: Completly eliminate the need for shell commands (e.g. find). This should enhance cross-platform compatibility.

One important change is that with this PR there will be two branches required. E.g. a "develop" or "main" branch, where new changes are pushed and "gh-pages" (which should pretty much correspond to the current gh-pages branches without the scripts). The workflow then generates updated imagery* files and pushes them to gh-pages ([as well as all sources, site and *md files](https://github.com/osmlab/editor-layer-index/blob/b2a4911ccae1fbf3cd3d35a17ff6ff0cea474dd8/.github/workflows/push.yml#L47-L56)). This solves https://github.com/osmlab/editor-layer-index/issues/894 and should be backward compatible, as hardcoded URL will still work.

### CODE REVIEW

**Comment by rbuffat** [comment]
The PR is ready to be reviewed. If everything is fine it is probably easier to directly push this branch to osmlab/editor-layer-index instead of merging it into gh-pages and then creating a new branch. 

The WMS sync bot only works on the default branch set in the github UI: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/changing-the-default-branch
I don't have permission to change this. Although as long as also the scripts are "deployed" into gh-pages, it should be possible to change the target branch of the PRs created by the bot manually afterward. 

To name the second branch `develop` is just a suggestion. I'm not good at naming things, thus it would be appreciated if somebody else has an idea.

**Comment by grischard** [comment]
Wow. This is an impressive and huge PR, and I think it might take a while to review.

You're changing quite a number of things unrelated to switching from Travis to github workflows.

The gh-pages deploy needs to include all the files that are statically hosted on github, like icons. It could be easiest to just dump everything across. The thought behind having just one branch was that it would be more newbie-friendly. Using the string 'gh-pages' was fossilised for certain editors; I'm not sure if that's still the case.

You've changed the check scripts to run on directories instead of files. Can a check still run on a file?

**Comment by rbuffat** [comment]
> You're changing quite a number of things unrelated to switching from Travis to github workflows.

You are right, that's true. One thing lead to another... I will create a new PR with just the github actions and as less as possible other things, probably later this week.

**Comment by grischard** [comment]
Heh, I know how that goes :). If you've tested it and are happy with how it works and solves the two things I've noticed, I don't want to be the cause of extra effort.

**Comment by rbuffat** [comment]
@grischard  sorry, it took a bit longer than I hoped for. I think it is always very valuable if somebody else can look at the changes before something is merged.  I will look into creating new PRs for the other changes after the github actions are finished. This is the most urgent issue at the moment.

**Pull request closed without merging**
