### PR TITLE
Add Berlin Webatlas as WMS

### LINKED ISSUE #646: Berlin building shapes
## URL of the imagery
https://fbinter.stadt-berlin.de/fb/index.jsp?loginkey=zoomStart&mapId=wmsk_webatlasberlin@senstadt

Example image based on the URL from the PR:
https://fbinter.stadt-berlin.de/fb/wms/senstadt/wmsk_webatlasberlin?FORMAT=image/png&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&SRS=EPSG:4326&WIDTH=256&HEIGHT=256&BBOX=13.45001220703126,52.47274306920924,13.451385498046882,52.47357958606801

## Two letter country code
DE

## Desired layer name
Berlin WebAtlas (Straßen, Hausumringe & -Nr.)

## License
Same as the other Berlin Layer (Areal Images).

https://fbinter.stadt-berlin.de/fb/index.jsp?loginkey=zoomStart&mapId=wmsk_webatlasberlin@senstadt

> Nutzungsbedingungen: 
Nutzungsbedingungen: Für die Verwendung der Daten gelten folgende Nutzungsbestimmungen: http://www.stadtentwicklung.berlin.de/geoinformation/download/nutzIII.pdf - Der Quellenvermerk gemäß §2 lautet "Geoportal Berlin / [Titel des Datensatzes]". 

With the specification for OSM, that a changeset source is valid to satisfy this license, see https://forum.openstreetmap.org/viewtopic.php?pid=367583#p367583.

### TODO: What does `"attribution"."required": true` do?
I think we discussed this before. All Berlin layer don't have this required flag. Is that correct?

## Is the license compatible with OSM?
YES

## Attribution (text, URL, required?)
Geoportal Berlin / WebAtlas Berlin

## Privacy policy (URL)
./.

## Icon
./.

## Bounding polygon
See PR.

### PR DESCRIPTION
**Pull request by tordans**
This PR add the Berlin shapes "Webatlas" für Building shapes and house numbers and streets as a WMS service.

Specs at https://github.com/osmlab/editor-layer-index/issues/646.

I am working on getting a TMS version going at https://github.com/jochenklar/berlin-maps/issues/4 since the WMS service is typically pretty slow.

(closes #646)

### CODE REVIEW

**Comment by tordans** [comment]
This does not work ATM. I tried it out with a local version of iD. The tiles don't match. I don't know enough about those geometries to figure out what is going on, so I hope for https://github.com/jochenklar/berlin-maps/issues/4 so we have a simpler integration.

**Comment by grischard** [comment]
That's strange! Does it work in, say, JOSM?

**Comment by simonpoole** [comment]
@grischard it doesn't support any of the "simple" projections  that iD and vespucci support.

**Comment by tordans** [comment]
Is there a place that explains which projections are supported? I could not find it in this repo.

Thanks for the hint, Simon.

**Comment by simonpoole** [comment]
@tordans EPSG:4326 and EPSG:3857 (including the various typo variants and EPSG:900913) 

See https://github.com/openstreetmap/iD/blob/a992d016adf78f8a92bffa2eaaad90ba39843df7/data/update_imagery.js line 55 ff

**Comment by grischard** [comment]
Definitely something jochenklar/berlin-maps#4 would fix then!

**Pull request closed without merging**
