### PR TITLE
Add aerial imagery for Albania

### PR DESCRIPTION
**Pull request by jbelien**

### CODE REVIEW

**Comment by jbelien** [comment]
No problem !
I'll fix it as soon as possible :)

**Comment by jbelien** [comment]
Still have to simplify the geometry and check the licences ; work in progress !

**Comment by grischard** [comment]
@jbelien hi, just wondering if you'd been able to find out about the albanian license and boundary. Thanks!

**Comment by jbelien** [comment]
Hello @grischard ,
Unfortunately it's still a work in progress...

Ping @dbaboci @rskikuli

**Comment by jbelien** [comment]
I see the `waitfor - boundary geometry` ; is there still something wrong with the geometry ? I simplified it on 23 Sep 2017 :)

**Comment by grischard** [comment]
Looks good! Small bits around the border sometimes gets cut off, if you want to adjust that. I tried the .poly from https://download.geofabrik.de/ but it isn't any better.

**Comment by grischard** [comment]
The terms of use in the lower right corner at https://geoportal.asig.gov.al/map/ are quite restrictive and incompatible. I'll close this for now, but feel free to ping to reactivate if we ever hear back.

**Comment by jbelien** [comment]
Hey Guillaume,

Which part makes you say it's incompatible ? :/

---


    Geoportal Terms of Use and Terms

    Use of the site http://geoportal.asig.gov.al (Geoportal) means accepting the following terms and conditions:
    Definitions

    For purposes of this document, these definitions will apply:

        "Geoportal Administrator" is the State Authority for Geospatial Information - "ASIG", which establishes and maintains the National Geoportal.
        "Public Authority" is:
            any central and local government body that carries out administrative functions as well as public entities performing administrative functions
            any natural or legal person who has the responsibility or performs public functions or provides public services under the control of the authorities provided for in point (a) of this paragraph.
        "BIG" is the Geospatial Information Board.
        "Geospatial Data" is any data that directly or indirectly refers to a particular country or geographic area.
        "Geoportal" is a system that uses a central and unique graphical interface through which users can discover, view and use geospatial information and network services associated with this information, as defined in This law.
        "Geospatial Information" are metadata, data, and geospatial data sets that relate to a phenomenon of any reality whose georeferencing is provided by a common coordinate spatial system.
        "Geospatial Information Services" are operations that can be accomplished, through computer applications, geospatial information, geospatial data and geospatial data sets, or related metadata
        "National Geospatial Information Infrastructure" is the infrastructure that includes the national authorities responsible for geospatial data, metadata, geospatial data sets and geospatial data services, network services and technologies, exchange agreements, access and use, As well as the coordination and monitoring mechanisms, processes and procedures created, put in place or made available in accordance with Law 72/2012.
        "User" is any individual, natural or legal person using Geoportal.

    I. General

        Access to geospatial information and geospatial information services is governed by:
            Law no. 72/2012 dated 28.06.2012 "On the Organization and Functioning of the National Geostationary Information Infrastructure in the Republic of Albania"
            Law no. 10 325, dated 23.09.2010 "On the State Data Basis"
            VKM Nr. 147 dated 20.02.2013 "On the approval of the Regulation" On the Organization and Functioning of the State Authority for Geospatial Information ""
            Order no. 87, dated 25.7.2013, updated with the Order No. 235 dated 3.12.2013 "On the Composition, Organization and Functioning of the Board for Geospatial Information"
        The terms and conditions set out in this document are valid for:
            Private users
            Public Institutions
        Every Geoportal user should be familiar with the terms and conditions of use before using the Geoportal.
        Users and public institutions are obliged to use Geoportal in accordance with law no. 72/2012 On the Organization and Functioning of the National Infrastructure of Geospatial Information in the Republic of Albania "and with the terms of this document.

    II. Types and extent of services

    Geospatial data and services made available through Temporary Geoportal include:

        Consultation, which minimizes display, navigation, zooming or downsizing, layered geospatial data groups, and the display of legend information and any relevant metadata content

    III. Terms / rules for using data and services from users

        Access to the consultation service referred to in Chapter II is currently available to individuals, natural and legal persons and public authorities free of charge.
        After the construction of the permanent National Geoportal, ASIG in accordance with Article 26 of Law 72/2012 "On the Organization and Functioning of the National Geostation Information Infrastructure in the Republic of Albania" applies tariffs for this service (in cases when This tariff is justified by the particularly high costs of creating and updating certain geospatial data) as well as for download and transformation services. The tariffs are approved by the DCM as set out in section 26 of Law 72/2012
        Users have the right to use Geopark resources only for non-profit and non-commercial purposes, in accordance with the provisions of Law 72/2012 "On the Organization and Functioning of the National Geostationary Information Infrastructure in the Republic of Albania" and Law no. 9380 dated 2804/2005 "On copyright and related rights"

    IV. Terms / rules for the exchange of geospatial data by public authorities.

        Public authorities exchange among themselves geospatial data sets and services, approved by ASIG, according to point 4 of article 12 of Law 72/2012 "On the Organization and Functioning of the National Geostation Information Infrastructure in the Republic of Albania" , Guaranteeing each other access to them and their use solely for the purpose of exercising their public functions.
        Access to Geospatial Data published in Geoportal is free of charge for state institutions in the performance of their public duties.

    V. Technical Terms of Use of Data and Services in Geoportal

        For the use of the National Geospatial Data Hub and Geospatial Services, it is necessary to:
            an internet connection
            a device that enables Internet access as well as programs (web browser, web GIS) that enable displaying and importing geo-portal data
        While using the Geoportal is prohibited:
            Use of viruses, bots, worms or other computer code, scripts or programs that interrupt, restrict the functionality of its Geoportal or its services, or allow unauthorized use of limited access services
            Use of computer codes, scripts, or automated programs to use the services provided by the Geoportal.

    VI. Copyright

    The content of this site and its resources is protected by the Albanian legislation in force, namely:

        Law no. 9947 dated 07.07.2008 "On Industrial Property"
        Law no. 9380 dated 2804/2005 "On copyright and related rights"

    VII. Additional information

    For more detailed clarifications regarding the content of this document, you can contact the State Authority for Geospatial Information at: "Papa Gjon Pali" Street No. 3, Floor 2, Tirana, e-mail: info@asig.gov.al
    VIII. Recent Provisions

        These terms and conditions apply from the date of publication to Geoportal
        These terms and conditions are free of charge in a format that allows downloading, and printing them
        These terms and conditions are in compliance with the applicable law especially the law no. 72/2012, dated 28.06.2012 "On the Organization and Functioning of the National Infrastructure of Geospatial Information in the Republic of Albania" and by-laws in its implementation
        The administrator (ASIG) is not responsible for the lack of access to the Geoportal for reasons that do not depend on it
        Administrator (ASIG), for security reasons and for any other cause of inability, has the right to temporarily suspend access to Geoportal until the extinction of inability conditions
        The Geospatial Administrator (ASIG) is not responsible for any damages arising from the use of Geopolitical Data related to errors, defects, or distortions that relate to the responsible authority of their creation or disrespect Terms and conditions from users
        These terms and conditions can be changed at any time and in every respect. The changes will take effect after being published on the Geoportal Site
        The Geospatial Administrator (ASIG) is not responsible for the accuracy or quality of the data reflected on the websites (GeoGebra) that can be accessed through the Geoportal Site

**Comment by grischard** [comment]
It's more what *isn't* in it. Parts III and VI don't contain any kind of open license.

**Comment by jbelien** [comment]
Okay, that makes sense ! :)

That's exactly why I asked my Albanian friends to contact ASIG. I hope @dbaboci @rskikuli @sidorelauku (or anyone else) will make a follow up on this topic !

Thanks Guillaume for your insights on this :)

**Comment by jbelien** [comment]
Topic will be raise at next [Open Labs](https://openlabs.cc/en/) meeting on 10th of March 2018 🎉

**Comment by grischard** [comment]
In the meanwhile, I'd be very happy to merge a PR for the Tirana data from https://geoportal.openlabs.cc

**Comment by jbelien** [comment]
> In the meanwhile, I'd be very happy to merge a PR for the Tirana data from https://geoportal.openlabs.cc

It's on my to-do list indeed :)
I'll add this ASAP !

**Comment by grischard** [comment]
https://cloud.openlabs.cc/s/3lzVn1ZzUEMifHq#pdfviewer for the Tirana data looks perfect!

**Comment by jbelien** [comment]
> https://cloud.openlabs.cc/s/3lzVn1ZzUEMifHq#pdfviewer for the Tirana data looks perfect!

That's indeed the agreement :)
It's on my to-do list for this weekend ! Stay tuned :P

**Comment by jbelien** [comment]
Done : https://github.com/osmlab/editor-layer-index/pull/451

**Pull request closed without merging**
