### PR TITLE
Add orthophotos for Linköping

### PR DESCRIPTION
**Pull request by NKAmapper**
Three more Swedish orthophoto.

No standard license, but clear statements here:

Sollentuna: [Official web page](https://www.sollentuna.se/sv/kommun--politik/om-sollentuna/Fakta-och-statistik/oppna-data-i-sollentuna/) ([Google translate](https://translate.google.com/translate?sl=sv&tl=en&js=y&prev=_t&hl=no&ie=UTF-8&u=https%3A%2F%2Fwww.sollentuna.se%2Fsv%2Fkommun--politik%2Fom-sollentuna%2FFakta-och-statistik%2Foppna-data-i-sollentuna%2F&edit-text=))
Linköping: [Official web page](https://www.linkoping.se/open/data/geodata/) ([Google translate](https://translate.google.com/translate?sl=sv&tl=en&js=y&prev=_t&hl=no&ie=UTF-8&u=https%3A%2F%2Fwww.linkoping.se%2Fopen%2Fdata%2Fgeodata%2F&edit-text=))
Norrköping: [Official web page](https://norrkoping.se/boende-trafik-och-miljo/kartor/flygbilder.html) ([Google translate](https://translate.google.com/translate?sl=sv&tl=en&js=y&prev=_t&hl=no&ie=UTF-8&u=https%3A%2F%2Fnorrkoping.se%2Fboende-trafik-och-miljo%2Fkartor%2Fflygbilder.html&edit-text=))

### CODE REVIEW

**Comment by grischard** [comment]
https://www.linkoping.se/open/ is CC-BY and would need a waiver. Norkopping's website is down at the moment. Sollentuna indeed seem to want to open this in spirit, but I'd really be more comfortable with a clear license or even an email from them saying it's cool.

**Comment by NKAmapper** [comment]
Ok, I will get the confirmations.

**Comment by NKAmapper** [comment]
Permission from Linköping has been obtained and is included now.

Norrköping says it will launch a new service with a proper license in a couple of months, so I have removed it and will wait for the new service.

No reply yet from Sollentuna. I have removed it and will submit separately when I get the confirmation.

Ready for merging.

**Comment by grischard** [comment]
Thank you very much!

**Pull request merged**
