### PR TITLE
Add VoGIS 2022 imagery

### PR DESCRIPTION
**Pull request by hlfan**
replaces VoGIS 2020 imagery as newest.

### CODE REVIEW

**Comment by cicku** [comment]
Can you squash your commits here?

**Review by andrewharvey — APPROVED** [review]
LGTM

**Comment by andrewharvey** [comment]
@cicku Can we use GitHub's Squash and merge?

**Comment by cicku** [comment]
@andrewharvey I don’t remember if this will override the contributor as myself 😅

**Comment by andrewharvey** [comment]
I don't think it does. https://github.com/mapbox/mapbox-gl-js/pull/11549 had two commits squashed and merged by someone else but GitHub still shows the commit as from myself. The only thing it might do comited by you but still attribute the original contributor as the author.

**Comment by hlfan** [comment]
squash it, merge it, the resulting commit will reference the PR anyway afaik

**Comment by cicku** [comment]
Done

**Comment by osmhomeblog** [comment]
Hello, I'm currently trying to use the VoGIS aerial image in JOSM (Vorarlberg [Austrian state]), but I'm getting an error message from JOSM. "Couldn't query the list of WMS layers" what am I doing wrong.

**Comment by hlfan** [comment]
Have you set the map parameter in the URL?

**Comment by AustrianMapper** [comment]
The VOGIS standard entry preset in JOSM is wms_endpoint:https://vogis.cnv.at/mapserver/mapserv?map=i_luftbilder_r_wms.map

**Comment by osmhomeblog** [comment]
I contacted a local JOSM supporter, he found a certificate error and gave the service provider a tip, it's working again. Thanks

**Pull request merged**
