### PR TITLE
Add Dakota County 2017 imagery

### PR DESCRIPTION
**Pull request by DcJoeS**
First time contributor, so if it's messed up let me know and I'll get it fixed.  I'll have others if this works.  Thanks.

### CODE REVIEW

**Comment by grischard** [comment]
Hi Joe! Sorry you've been kept waiting for two weeks. It looks like your imagery geometry is broken. You need to simply define one polygon with multiple rings, like https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/sources/europe/gb/NLS-OS1-inch7thSeries1955-61.geojson

**Comment by DcJoeS** [comment]
Thanks for the help.  Two polygons, that's weird, the different tools I attempted to use to create the boundary essentially output the same thing.  I will say I had a boundary shpfile and was trying to convert it to geojson.  If I'm going to contribute more, I need to find a better tool to convert with.

**Comment by grischard** [comment]
Thank *you*!

Maybe the source you used actually has the ring twice? Hopefully you'll be able to just re-use this polygon as a template if you have more imagery for Dakota county.

**Comment by DcJoeS** [comment]
I certainly will, I'll have a new aerial that will be online in a few months.  I do have a great statewide service I'll try soon too.  Thanks for all the help.

**Comment by Klumbumbus** [comment]
Does this source work for you? I only get an error:

`<ServiceException code="InvalidLayers">
Parameter 'Layers' contains invalid values.
  </ServiceException>`

e.g. at https://gisimg.co.dakota.mn.us/arcgis/services/AerialPhotography/2017AirPhotoLeafOff6Inch/ImageServer/WMSServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&SRS=EPSG:4326&WIDTH=512&HEIGHT=512&BBOX=-93.1091346,44.6923848,-93.0981483,44.7033711

**Comment by DcJoeS** [comment]
Ugh, I ran across that today too.  Trying to sort it out:  
https://community.esri.com/message/857459-wms-issues

It worked before, not sure why not now.  Hopefully, I get this sorted out soon.

**Comment by DcJoeS** [comment]
@Klumbumbus Esri support sorted it out.  The datasets have raster function templates defined, so they have to accessed via the LAYERS call.  Your link updated:  https://gisimg.co.dakota.mn.us/arcgis/services/AerialPhotography/2017AirPhotoLeafOff6Inch/ImageServer/WMSServer?FORMAT=image/jpeg&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&LAYERS=2017AirPhotoLeafOff6Inch_Spring:None&STYLES=&SRS=EPSG:4326&WIDTH=512&HEIGHT=512&BBOX=-93.1091346,44.6923848,-93.0981483,44.7033711

I'll get my file updated and resubmitted for pull.

**Comment by grischard** [comment]
Ah, but that PR has already been merged, so re-commiting to it makes things messy and hard to re-merge. You can simply create a new PR if you click on 'edit' at the top right of the file on github.

**Comment by DcJoeS** [comment]
@grischard I think I did it.  I really appreciate your help and patience.

**Comment by Klumbumbus** [comment]
fixed in #675

**Pull request merged**
