### PR TITLE
Create JapanGSIairphotoImagery.geojson

### PR DESCRIPTION
**Pull request by higa4**
Widely covered and/or newer than GIS ortho Imagery.

### CODE REVIEW

**Comment by grischard** [comment]
Hi Higa4, thank you for your PR!

The polygon can be greatly simplified since the east coast of Japan is just water. The whole line from Hokkaido to Taiwan can be simplified to just one point in the middle of the Pacific.

Let me know if you'd like to try that, otherwise I'll merge it as it is.

**Comment by higa4** [comment]
@grischard Thanks for your notice. Sorry, it seems hard to me because there are many islands to include toward east-southern pacific area underneath Tokyo, Japan.

**Comment by grischard** [comment]
Thank you very much, it's merged 👍

**Comment by higa4** [comment]
Thanks a lot!

**Pull request merged**
