### PR TITLE
Argentina: adding new services and updating / removing old ones 

### PR DESCRIPTION
**Pull request by Zalitoar**
New base maps and mosaics from National Geographic Institute of Argentina added, existing files renamed, fallen services removed and old URLs updated.

License applying on sources are defined globally for all government public data (included in 'license_url' property): https://datos.gob.ar/acerca/seccion/Marco%20legal

### CODE REVIEW

**Comment by Zalitoar** [comment]
There's a reference in the concatenated geojson to a file with parenthesis in it's name wich causes an error while running the check script, but this file is removed by this pull request. 

The CONTRIBUTING.md file says that a pull request update automatically the main geojson file so I didn't modify it.

**Comment by ignaciolep** [comment]
> There's a reference in the concatenated geojson to a file with parenthesis in it's name wich causes an error while running the check script, but this file is removed by this pull request.
> 
> The CONTRIBUTING.md file says that a pull request update automatically the main geojson file so I didn't modify it.

@rbuffat could you help with this failed check? Thanks!

**Comment by rbuffat** [comment]
@ignaciolep @Zalitoar I hope I find in the next few days more time to look at this PR, sorry for that. There is a fix for filenames with ( or ), but I'm not sure if it works in all case. Thus rebasing / merging the current gh-pages could solve the issue with the tests. 

Also, is there already somewhere documented that the license terms stated in https://datos.gob.ar/acerca/seccion/Marco%20legal are compatible with OSM?

**Comment by Zalitoar** [comment]
> @ignaciolep @Zalitoar I hope I find in the next few days more time to look at this PR, sorry for that. There is a fix for filenames with ( or ), but I'm not sure if it works in all case. Thus rebasing / merging the current gh-pages could solve the issue with the tests.
> 
> Also, is there already somewhere documented that the license terms stated in https://datos.gob.ar/acerca/seccion/Marco%20legal are compatible with OSM?

Thanks for your answer René, the validation script fails but the files with parenthesis no longer exist. We forked the repo long time ago, I updated it from upstream (this repo) and then I made the changes so it would be ok from 'our' side.

About the license , please take a look in my answer about tha in the issue #1048

**Comment by rbuffat** [comment]
First, sorry for the long response time, and already thanks for the time and effort for making this PR!

> Thanks for your answer René, the validation script fails but the files with parenthesis no longer exist. We forked the repo long time ago, I updated it from upstream (this repo) and then I made the changes so it would be ok from 'our' side.

The github workflow takes all changed (also deleted) files into account and only the  strict_check.py script checks the existence of the file. A fix for passing filenames with parenthesis was only merged a few days ago. But locally all checks seems to be good. 

> About the license , please take a look in my answer about tha in the issue #1048

I'm not really familiar with the situation in Argentina, so I probably need some guidance here. As far as I interpret the links from https://datos.gob.ar/acerca/seccion/Marco%20legal it states that the government needs to release public data but not under what license:
> That to guarantee the foregoing, public data must be published in a proactive, complete and timely manner, in and through the channels, media, formats and under licenses that best facilitate its location, access, processing, use, reuse and redistribution.
http://servicios.infoleg.gob.ar/infolegInternet/anexos/255000-259999/257755/norma.htm


**Educational-Map_wms.geojson:**

I guess http://mapa.educacion.gob.ar/terminos-y-condiciones is applicable for the "http://mapa.educacion.gob.ar/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities" server. On this page the following is stated:

> The National Government licenses all its contents under the Creative Commons Attribution 4.0 International license , whose legal text can be found at https://creativecommons.org/licenses/by/4.0/legalcode.es .

CC-BY typically requires a waiver regarding the attribution: https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/

**ign.gob.ar servers**

For the *ign.gob.ar servers https://www.ign.gob.ar/NuestrasActividades/InformacionGeoespacial/ServiciosOGC at the bottom left links the following terms and conditions: https://www.ign.gob.ar/descargas/tyc3.html

> Terms and Conditions of use of the information downloaded from the website of the National Geographic Institute
> 
> I. Introduction
> These Terms and Conditions are applicable to any natural or legal person who downloads, uses, reuses and / or redistributes information downloaded from the website of the National Geographic Institute of the Argentine Republic.
> 
> II. Responsibility. Guarantee. Security
> The use of the information downloaded from the website of the National Geographic Institute will be carried out by the Users at their own risk and account, corresponding exclusively to them to respond to third parties for damages that may arise from it. The National Geographic Institute will not be responsible for the use that Users make of their information, nor for the damages suffered or economic losses that, directly or indirectly, this may cause.
> The User denies the National Geographic Institute of responsibility for the information they make use of, consequently not being able to claim for errors or omissions in this information and materials. Due to the fact that no transmission over the Internet can guarantee its complete security, the National Geographic Institute cannot guarantee that the information transmitted using its service is completely secure, with which the User assumes this risk that he declares to know and accept.
> The National Geographic Institute is not obliged to guarantee uninterrupted continuity in making the information available, neither in content nor in form, nor does it assume responsibility for any error or omission contained therein.
> 
> III. Information about errors or problems
> Any concern, query, problem or suggestion that Users have in relation to the information downloaded may be reported to the email address contacto@ign.gob.ar
> 
> 
> Data licensing policy
> 
> I. Permitted uses of the information downloaded from the website
> These terms and conditions allow the use of the information downloaded from the website of the National Geographic Institute according to the following conditions:
> 
>  1. The source of the documents object of the reuse: "SOURCE: National Geographic Institute of the Argentine Republic".
>  2. The downloaded data must not be altered.
>  3. It may not be indicated, insinuated or suggested that the National Geographic Institute participates, sponsors or supports its use or reuse.
>  4. The metadata on the update date and the applicable reuse conditions included, where appropriate, in the document made available for use or reuse must be kept, and therefore not altered or deleted.
>  5. In the event that derivative products are generated, the date of the original IGN data must also be mentioned.
>  6. The downloaded data must be shared freely and for free.
>  7. Its commercial use is allowed only in the case of derivative works in which the information is used as an input to generate a new product.
> 
> The authorized reuse may include the copying, dissemination, modification, adaptation, extraction, rearrangement and combination of the information contained in the site, provided that its use does not distort the meaning of the information.
> 
> II. Judicial controversies. Applicable jurisdiction
>  1. Any controversy that arises in relation to the breach of the Terms and Conditions of Use of information downloaded from the website of the National Geographic Institute, and with the Data Licensing Policy set forth above, will be competent to understand the Federal Courts with seat in the Autonomous City of Buenos Aires.
>  2. For such purposes, the National Geographic Institute is domiciled at Avenida Cabildo 381, Autonomous City of Buenos Aires
https://www.ign.gob.ar/descargas/tyc3.html


The following points seem relevant:

> 1. The source of the documents object of the reuse: "SOURCE: National Geographic Institute of the Argentine Republic".

Attribution for datasets in OSM is typically made using the Contributors page: https://wiki.openstreetmap.org/wiki/Contributors#Argentina There seems to be already an entry for IGN.

>  5. In the event that derivative products are generated, the date of the original IGN data must also be mentioned.

The date of the IGN data is specified in the geojson metadata, but this is maybe a bit of a stretch. 

>  7. Its commercial use is allowed only in the case of derivative works in which the information is used as an input to generate a new product.

This is probably ok. OSM is commercial use, but the data is used to generate a new product.

**Comment by rbuffat** [comment]
On a technical note regarding wms_endpoints. It is perfectly fine to include sources using wms_endpoints, but there are a few points to consider: 
* Some OSM editors do not support `wms_endpoint` types, but only the `wms` type where each layer is a separate source.
* Ideally, only sources are included in an index where the license situation is clear. There are multiple examples where the same WMS server includes layers that can be used for OSM and layers that are not.  Thus, wms_endpoints are preferably only used for WMS servers where it is known that now and in the future all available layers can be used for OSM.

**Comment by Zalitoar** [comment]
Hi René, thanks for your time.

A licence is a contract which by a person or entity receives a right or permission to use, distribute, study or modify / process part or whole of its assets under specific conditions.

Due that all legal agreements, contracts and even executive orders (at all levels) are based on the law, can't be in opposition to it. In other words, a licence or even a simple waiver can't rule over that what says a law and Argentina has one about data produced by government.

The National Congress of Argentina sanctioned in late 2016 the law 27275 which determines that all data produced by the government and its associates is public by default, it can be understood as an equivalent to open data. This includes the IGN, education system map, and so on. So the law applies trasnversally to all the government.

Law in english: https://translate.google.com/translate?hl=&sl=es&tl=en&u=http%3A%2F%2Fservicios.infoleg.gob.ar%2FinfolegInternet%2Fanexos%2F265000-269999%2F265949%2Fnorma.htm

Original text in Spanish: http://servicios.infoleg.gob.ar/infolegInternet/anexos/265000-269999/265949/norma.htm 

Since open doesn't implies that something is free, the 2nd article of the law 27275 stablish the conditions that applies to the public data. Transcripted and translated here:

> Right of access to public information. The right of access to public information includes the possibility of searching, accessing, requesting, receiving, copying, analyzing, reprocessing, reusing and freely redistributing the information in the custody of the obligated subjects listed in article 7 of this law, with the only limitations and exceptions established by this rule.
>
> All information generated, obtained, transformed, controlled or guarded by the obligated subjects covered by this law is presumed public. 

As you say the terms and conditions of IGN and other dependencies may lead to a confussion because they affirm things that sounds contrictory to what is said in the cited law. 

I can't explain why in http://mapa.educacion.gob.ar/terminos-y-condiciones is said something like 'all gov data is licensed under CC-BY', maybe it was published before the law was approved and wasn't updated since then. But I can affirm with total confidence that's what happened with IGN's terms and conditions. I work there and checked at the date of those files in the web server, they were published previously to the approval of the law.

I assume that the legal department of the IGN didn't noticed about the implications of the cited law at that time, maybe many other dependencies couldn't noticed it by today. But as I said at the beggining of this response, the law rules over this terms and conditions or any other text published by any government dependency.

The law also says that there are few exceptions as defense, personal, intelligence and other data that is not public but clearly those aren't inclued whitin the sources that we are proposing.

I'm available to answer all the quiestions regarding this matter same as data and services provided by the National Geographic Institute.

Thanks in advance.

**Comment by Zalitoar** [comment]
> On a technical note regarding wms_endpoints. It is perfectly fine to include sources using wms_endpoints, but there are a few points to consider:
> 
>     * Some OSM editors do not support `wms_endpoint` types, but only the `wms` type where each layer is a separate source.
> 
>     * Ideally, only sources are included in an index where the license situation is clear. There are multiple examples where the same WMS server includes layers that can be used for OSM and layers that are not.  Thus, wms_endpoints are preferably only used for WMS servers where it is known that now and in the future all available layers can be used for OSM.

Yeap, I noticed that for iD specially not supporting WMS endpoints. I think that this repo also produces sources definitions in XML for JOSM, that's why added some wms_endpoint. If it's not the case, we can remove them.

**Comment by rbuffat** [comment]
@Zalitoar So you think it would not be possible to apply CC-BY to data under the law 27275? Maybe it would be good to split the PR by the different data providers (IGN, Secretaría de Energía, ...)

@grischard Could you also have a look at this PR?

**Comment by ignaciolep** [comment]
Hi @rbuffat , as you know, Argentina sources are broken. Would it be possible to merge this PR that fixes them? What would be the specific problem that prevents accepting the fixes? Thanks!

**Comment by rbuffat** [comment]
@ignaciolep 
The PR seems to contain sources from different data owners under different licenses.

- The [IGN terms](https://www.ign.gob.ar/descargas/Terminos-y-condiciones-de-uso-IGN.pdf) include some strange terms. E.g. `En ningún caso debe alterarse la información descargada`, but then again `Se permite su uso comercial únicamente en el caso de obras derivadas en que la información sea utilizada como insumo para generar un nuevo producto.`.  The terms also include the requirement to give attribution (`1. Debe citarse la fuente de los documentos objeto de la reutilización: “FUENTE:
Instituto Geográfico Nacional de la República Argentina”.`).  
Given that there is an entry for IGN in https://wiki.openstreetmap.org/wiki/Contributors#Argentina and assuming this was done with the consent of IGN I would say these sources are ok. 

- The Educational Map source seems to be under [CC-BY 4.0](http://mapa.educacion.gob.ar/terminos-y-condiciones), which requires explicit permission: https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/.

As suggested in https://github.com/osmlab/editor-layer-index/pull/1058#issuecomment-792273358 I would propose to split this PR by the different data origins/licenses so that the ones where the license situation is ok can be merged.

**Comment by Zalitoar** [comment]
@rbuffat as I explained above in [#issuecomment-787128954](https://github.com/osmlab/editor-layer-index/pull/1058#issuecomment-787128954) the law 27275 specifies the terms and conditions for all the government data, that includes the IGN, National Educational Map, etc. 

Those texts your're referencing are old, previous to the mentioned law and are surpassed by the it. Maybe some of them were based on Creative Commons while the 'public information..' law was in treatment by the Congress.  

As far as I understand any texts as terms & conditions or licenses published by government entities must comply what the law say, in some cases they would extend or give specific context for usage of the data or its nature. 
This of course is valid for IGN, Educational Map and other government sources because the data provided by them are included by the law 27275 (public information access right law).

Therefore, since all the sources included in this PR (except the Imagico ones) belongs to Argentina's government entities and the 27275 law rule all the data they're publishing we understand that any other text were replaced by it. Maybe in some cases, specific liceses would extend the main definition of usage present in the 2nd aritcle of the public information access right law but never be in opposition to it.
Also, we comprehend that the spirit of the cited law is compatible with the ODbL license because as I cited before here the law says:

> The right of access to public information includes the possibility of searching, accessing, requesting, receiving, copying, analyzing, reprocessing, reusing and freely redistributing the information in the custody of the obligated subjects listed in article 7 of this law, with the only limitations and exceptions established by this rule.

In this sense, any license provided by government entities can't establish restrictions not provided by the law, and if they're previous by common sens we can agree that those license are expired or replaced by the law which is applying today.

**Comment by kathleenlu09** [comment]
Hi, LWG was asked to weigh in here.

Unfortunately, none of us are Spanish speakers or familiar with Argentine law, so it is difficult for us to be authoritative.

Based on this translation at https://github.com/osmlab/editor-layer-index/pull/1058#issuecomment-787128954, it does appear that data from the relevant government entities is, essentially, public domain. We are, however, not in a position to confirm this translation, or to understand whether and of the "limitations and exceptions" references are relevant. (If anyone has an Argentinian lawyer friend, I'd love to chat with them 😂 )

But assuming the translation is correct and no limitations or exceptions apply, one might take the view that the data that have specific licenses are "dual-licensed" under both the license specifically listed and under the terms of this law. Thus, OSM could choose to take them under the terms of the law, which, based on the translation of the portion excerpted, appear compatible.

We would still of course recommend attribution on https://wiki.openstreetmap.org/wiki/Contributors#Argentina, even if only as a courtesy.

Sorry we cannot be of more help. 

-Kathleen (on behalf of LWG)

**Comment by rbuffat** [comment]
@kathleenlu09 Thanks for looking at this, this is much appreciated! @Zalitoar thank you for your persistence!

**Pull request merged**
