### PR TITLE
[Lyon] Fix some metadata in layers

### PR DESCRIPTION
**Pull request by cnotin**
Some metadata, and more importantly, WMS, URLs don't work anymore so I've fixed them with new URLs that were provided by Métropole de Lyon.
I've also added the new 2022 layer, also provided by Métropole de Lyon. I also discovered that JOSM has this layer, and the fix for the others, described on https://josm.openstreetmap.de/wiki/Maps/France#LyonOrthophoto2022

### CODE REVIEW

**Comment by cicku** [comment]
Can you drop the 2012 layer?

**Comment by cnotin** [comment]
Oops indeed there was a mistake in the URL. It's fixed with the latest commit. Is that what you meant?

**Comment by andrewharvey** [comment]
@cnotin Sorry I missed this one and just merged #2061 which incorporated some of your changes. Normally I would work with the earlier contribution first, but I missed it.

Could you check if any further changes are needed and either resolve the conflicts or close? Thanks.

**Comment by cnotin** [comment]
Oh damn! I've fixed the conflicts by keeping only the relevant changes

**Pull request merged**
