### PR TITLE
Create Kanton_Solothurn_SOGIS_DSM_2018.geojson

### PR DESCRIPTION
**Pull request by voongit**
I saw, that the 2019 relief only provides the southern half of the canton. The 2018 relief is the north, including most of Basel Land as well. This would also require modifications to the polygon .. but I do not know how to do that.

### CODE REVIEW

**Comment by grischard** [comment]
You can load the files on geojson.io and use the pencil tool to edit the polygon, just by dragging the nodes. You can add the layer as a background layer, and just trace along to that.

**Comment by voongit** [comment]
Hello Guillaume

Oh ok, I'll have a look at that .. I hope it can load WMS as background :)

Thanks!

Philippe






Am Sonntag, 8. März 2020, 17:22:02 MEZ hat Guillaume Rischard <notifications@github.com> Folgendes geschrieben: 





You can load the files on geojson.io and use the pencil tool to edit the polygon, just by dragging the nodes. You can add the layer as a background layer, and just trace along to that.

**Comment by voongit** [comment]
Hello again :)

There we go ... I tried editing the files in git with the new polygon, which seems to have wroked. I hope I did the right thing? GIT is a bit of a mystery to me atm.

Kind regards,

Philippe

**Comment by voongit** [comment]
Hi Guillaume

Do I have to do something else with my updated polygon? Or was it wrong to chose "edit file" for an update? It seems the process is stuck? If it's only because noone had time, then no worries that's fine, only asking in case I need to do soemthing additional.

Kind regards,

Philippe

**Comment by grischard** [comment]
Sorry for the delay, it's been merged. Thank you for your kind email too - glad you managed github and git and all that jazz :)

**Comment by Klumbumbus** [comment]
These elevation type sources should probably not marked "best":
Kanton Solothurn, DSM Relief 2018
Kanton Solothurn, DSM Relief 2019
Kanton Solothurn, DTM Relief 2019

**Comment by Klumbumbus** [comment]
Fixed shape of the 2019 sources, see https://josm.openstreetmap.de/wiki/Maps/Switzerland?action=diff&version=175

**Comment by grischard** [comment]
Thank you @Klumbumbus

**Pull request merged**
