### PR TITLE
Added Balatonőszöd.

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @Klumbumbus 
Here is a new area for Balatonőszöd, Hungary.

### CODE REVIEW

**Comment by grischard** [comment]
@Klumbumbus you know about this? :)

What is this @urbalazs ? It expands the polygon?

**Comment by urbalazs** [comment]
Hello @grischard 
A new town has been added to the existing ortophoto set, that's why I added the new polygon.

**Comment by grischard** [comment]
Nagyon köszönöm!

**Comment by Klumbumbus** [comment]
The new shape is not closed. The last point must be the same like the first point. (See red line in screenshot.)

There is another new image west of the new one on high zooms too. Can you add the shape for this too?

grafik

**Comment by urbalazs** [comment]
The new part in the west side is also new for me, it was added just today. I fixed the previous shape, and added the new one in https://github.com/osmlab/editor-layer-index/pull/549

**Comment by Klumbumbus** [comment]
Thanks.

**Pull request merged**
