### PR TITLE
Add a category attribute like JOSM, thanks @simonpoole

### PR DESCRIPTION
**Pull request by simonpoole**
As discussed. 

I'll start adding the field to some of the sources in a 2nd commit.

### CODE REVIEW

**Comment by andrewharvey** [comment]
:+1: Is there any guidance on when a imagery becomes historical? Is historical imagery intended for the ELI?

It would be nice to have a description of each somewhere in the documentation, if possible.

**Comment by simonpoole** [comment]
https://josm.openstreetmap.de/wiki/Maps so it isn't actually "historic" the way JOSM uses it, just outdated.

**Comment by simonpoole** [comment]
> 
> 
> https://josm.openstreetmap.de/wiki/Maps so it isn't actually "historic" the way JOSM uses it, just outdated.

Any opinions on if we should follow JOSM on this specific point or not @grischard & @Marc-marc-marc  ?

**Comment by grischard** [comment]
We should follow JOSM on this point. Editors might of course want to show a better explanation - "newer layer available" for example.

**Comment by grischard** [comment]
I'm all in favour of making the attribute mandatory, and doing a great big retro-tagging of all existing sources.

We should also adapt the conversion scripts.

**Comment by Marc-marc-marc** [comment]
> > https://josm.openstreetmap.de/wiki/Maps so it isn't actually "historic" the way JOSM uses it, just outdated.
> 
> Any opinions on if we should follow JOSM on this specific point or not @grischard & @Marc-marc-marc ?

as said in the issue,
I find a very bad idea to have 2 meaning for historic (osm <> josm).
I find also a bad idea to have 2 characteristics in one (type+latest)
but if it's too complicated to use a more meaningful tag (latest, outdated,...) and split those in 2 and some people think that a common tag to both projects is better than a quality tag, then I prefer not to oppose.

**Comment by simonpoole** [comment]
I went through the Swiss sources and tried to categorize those with category photo that made sense, and it clearly showed the problem with historicphoto: is a 10 year old layer historic if there is no successor or is it considered current?

The remaining question is if we should copy the attribute values from JOSM mechanically, or simply wait till people to it of their own accord?

**Comment by Marc-marc-marc** [comment]
> I went through the Swiss sources and tried to categorize those with category photo that made sense, and it clearly showed the problem with historicphoto: is a 10 year old layer historic if there is no successor or is it considered current?

if it's the lasted, it'sn't historic for josm.

> The remaining question is if we should copy the attribute values from JOSM mechanically, or simply wait till people to it of their own accord?

an automatic bidirectional synchronization would obviously be the best, so that the contribution of the 2 projects would benefit everyone.
But if not, someone would have to do it on their own account.

**Review by don-vip — APPROVED** [review]

**Comment by grischard** [comment]
See #136 - JOSM recently added 'elevation' as a type.

**Comment by Klumbumbus** [comment]
I updated the JOSM database with the new category types: 19 qa and 30 elevation

**Comment by don-vip** [comment]
20 qa now. I added French BANO as qa too.

**Comment by simonpoole** [comment]
> 
> 
> See #136 - JOSM recently added 'elevation' as a type.

I've added it too now, even though it seems to be a slightly weird choice.

**Comment by andrewharvey** [comment]
>> See #136 - JOSM recently added 'elevation' as a type.

> I've added it too now, even though it seems to be a slightly weird choice.

Seems appropriate to me. Though I noticed JOSM actually describes what these values are to be used for and I think we need to do that here too eg.

`elevation` - A map of digital terrain model or digital surface model.

**Comment by Klumbumbus** [comment]
> `elevation` - A map of digital terrain model or digital surface model.

That was updated: https://josm.openstreetmap.de/changeset/15685/josm

**Comment by grischard** [comment]
Looks ready to merge for me; we can update the various scripts in another step.

**Comment by simonpoole** [comment]
@grischard https://github.com/osmlab/editor-layer-index/pull/760

PS: @andrewharvey I would have used "terrain"

**Comment by andrewharvey** [comment]
> PS: @andrewharvey I would have used "terrain"

I think either is fine, so long as we include the description within the schema documentation.

**Pull request merged**
