### PR TITLE
Maaamet layer addition (Estonia)

### PR DESCRIPTION
**Pull request by kallejre**
Added ~~3~~ ~~5~~ ~~7~~ 15 new Estonian ~~Maa-amet~~ map layers. 

This PR adds 3 new layers from Estonian land board, using existing corine land layer as template. Added layers are DSM (Digital Surface Model, essentially lidar scan), Hybrid and alternative Cadastre map (compared to existing one this has true colours, addresses data layer and hopefully better aerial image quality).

Later replaced broken hillshading layer with working wgs84-compatible layer and added modern Etak basemap (kaart24). More layers: fixed privacy policy and zoom levels for all layers, added nautical chart and Tallinn city planning department's map (EPSG:3301, but later has number of building levels). 

Also included 5 historic ortophotos from 1993 to 2019. Actually each of these layers include 3-4 sublayers from different years to get full coverage. Added 2 historic maps from 1899 & 1935 and one set of 6 sublayers from 1974-1989 with covering whole country at different zoom levels.

### CODE REVIEW

**Comment by kallejre** [comment]
What else do i have to do, to merge this into main branch? This is my first pull request ever.

**Comment by kallejre** [comment]
Is there a way to tell editor, that "this layer/server supports bounding box with any size and shape (non-square) and you should download map as a whole, not separated into tiles"?

**Comment by grischard** [comment]
@kallejre sorry I haven't gotten around to this yet.

CC @Klumbumbus if he'd like to add this to the JOSM index too.

**Comment by kallejre** [comment]
@grischard I think this latest build failure is issue with Travis tests. There's a layer that didn't need projection (`{proj}`) but well-known ID (`{wkid}`) instead, which is essentially same thing except without `EPSG:`-part. [iD editor's layer testing site](https://ideditor.github.io/imagery-index/) (with different layer) and JOSM (with same layers as in question) did work with `{wkid}` in url.

PS. Have you found time to merge yet, I'm running out of layers to add.

**Comment by kallejre** [comment]
Sorry for these lots of commits. I don't know how to use git.

**Comment by andrewharvey** [comment]
hi @kallejre sorry you've had problems with git, in order to get this mergable you'll need to rebase against master and force push that. To be honest it might even be easier to reapply your changes to a freshly cloned repo and git push --force again here

**Comment by kallejre** [comment]
Closing this PR in favour of #858

**Pull request closed without merging**
