### PR TITLE
Add OS OpenMap Local

### LINKED ISSUE #1057: OS OpenMap Local
When **requesting the addition of an imagery layer**, please provide the following information. Otherwise, delete the text and type your issue.

## URL of the imagery
tms[17]:https://{switch:a,b,c}.os.openstreetmap.org/layer/gb_os_om_local_2020_04/{zoom}/{x}/{y}.png

But it looks like there's a new URL for every release. Maybe we could add each release in?
They can all be found here: https://os.openstreetmap.org/

## Two letter country code
GB

## Desired layer name
OS OpenMap Local - April 2020

## License
OGL v3 as detailed on the [wiki](https://wiki.openstreetmap.org/wiki/Ordnance_Survey_OpenData#OS_VectorMap_District)  and on the [website](https://www.ordnancesurvey.co.uk/business-government/products/open-map-local)

## Is the license compatible with OSM?
Yes

## Attribution (text, URL, required?)
OS OpenMap Local

## Privacy policy (URL)
https://www.ordnancesurvey.co.uk/governance/policies/privacy

## Icon
https://wiki.openstreetmap.org/wiki/File:OS-SV.png

## Bounding polygon
Should be the same as OS OpenData StreetView as this is the updated version of it

### PR DESCRIPTION
**Pull request by TurnrDev**
Fixes #1057

### CODE REVIEW

**Comment by rbuffat** [comment]
@TurnrDev Thanks for this PR. Are there license and privacy policy URLs available for these sources?

**Comment by TurnrDev** [comment]
I don't know, it's documented on the wiki though 😊

https://wiki.openstreetmap.org/wiki/Ordnance_Survey_OpenData

**Comment by rbuffat** [comment]
@TurnrDev Then I would suggest adding:
```
        "privacy_policy_url": "https://wiki.osmfoundation.org/wiki/Privacy_Policy",
        "license_url":  "https://wiki.openstreetmap.org/wiki/Ordnance_Survey_OpenData"
```

**Comment by TurnrDev** [comment]
Pulled your commit :)

**Comment by rbuffat** [comment]
Thanks @TurnrDev !

**Comment by TurnrDev** [comment]
No no, thank you! How long until JOSM and iD take these changes in?

**Comment by boothym** [comment]
For iD there needs to be a new version released with updated layers. Unfortunately there's no active developer on there at the moment to update things, the last update was 3rd March.

**Pull request merged**
