### PR TITLE
Updated Brazil-Rio imagery

### PR DESCRIPTION
**Pull request by matheusgomesms**
Removed Rio 2013 imagery (not working, which also fixes issue #1202), added 2019 imagery, and updated 2015 imagery.

### CODE REVIEW

**Comment by rbuffat** [comment]
Do you know more about the license situate of this data?

**Comment by matheusgomesms** [comment]
The [Brazilian community is using their data for so long](https://wiki.openstreetmap.org/wiki/Pt:Rio_de_Janeiro#Projetos). On Wiki there are some pages saying that all data from Instituto Pereira Passos (IPP/Data.Rio) is on ODbL (more links below). Also, if you go to this [Ortophoto page](https://www.arcgis.com/home/webmap/viewer.html?featurecollection=https%3A%2F%2Fpgeo3.rio.rj.gov.br%2Farcgis%2Frest%2Fservices%2FImagens%2FMosaico_2019%2FImageServer%3Ff%3Djson%26option%3Dfootprints&supportsProjection=true&supportsJSONP=true), click on Content - Show Table, there is the License Information:

_Uso público, citadas as fontes e mantidas as informações originais._ (Public use, citing sources and maintaining original information.)

[[1](https://wiki.openstreetmap.org/wiki/Pt:Rio_de_Janeiro/Import_data.rio#Licen.C3.A7a)] _Data from the data.rio portal are available under an ODbL license, therefore subject to authorization in the OSM without the need for extra authorization._
[[2](https://wiki.openstreetmap.org/wiki/Rio_de_Janeiro/Import_IPP_Buildings)] _This data license is stated as follows: All information obtained through this application can be freely used, citing the source: Prefeitura da Cidade do Rio de Janeiro - Instituto Pereira Passos._

**Comment by matheusgomesms** [comment]
Just to add, one user from Brazilian community talked to IPP and received explicit permission to use their data on OSM:

https://wiki.openstreetmap.org/wiki/File:Autoriza%C3%A7%C3%A3o_Data_Rio_-_Rio_de_Janeiro.png

cc @rbuffat

**Comment by matheusgomesms** [comment]
Hey guys,

Is there still any problem with the license regarding this imagery?

Best,
Matheus

**Review by willemarcel — APPROVED** [review]

**Pull request merged**
