### PR TITLE
Add City of Cape Town 2013 imagery

### PR DESCRIPTION
**Pull request by Firefishy**

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks Grant!

**Comment by Klumbumbus** [comment]
Is `"start_date": "2013" "end_date": "2016"` correct? Sounds unlikely since there is an own entry for 2015.

**Comment by Firefishy** [comment]
Well spotted. `end_date` should be `2014`.

**Comment by Klumbumbus** [comment]
Were images actually taken in 2014 or is `end_date: "2014"` only due to the date definition at https://github.com/osmlab/editor-layer-index/blob/gh-pages/CONTRIBUTING.md ?

**Comment by Firefishy** [comment]
Yes, potentially. The majority of the image was collected in Summer 2013 (note Southern Hemisphere) and was process in 2014. If there were gaps, they may have been captured in early 2014.

**Comment by Klumbumbus** [comment]
OK, thanks. I'll fix it.

**Pull request merged**
