### PR TITLE
2016 AGIS imagery

### PR DESCRIPTION
**Pull request by simonpoole**
A bit late for reasons beyond our control, but here it is.

### CODE REVIEW

**Comment by tyrasd** [comment]
Thanks Simon!

**Comment by Klumbumbus** [comment]
You changed max zoom from 19 to 20. However it seems z20 are only enlarged z19 tiles. I think it would make sense to change it back to z19 to avoid unecessary traffic!?

**Comment by simonpoole** [comment]
The original geo-tifs were tiled for zoom level 20 the other zoom levels were generated from them, so: no zoom 20 is not simply an overlooked version of zoom 19.

On 19. April 2017 18:33:30 GMT+01:00, Klumbumbus <notifications@github.com> wrote:
>You changed max zoom from 19 to 20. However it seems z20 are only
>enlarged z19 tiles. I think it would make sense to change it back to
>z19 to avoid unecessary traffic!?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmlab/editor-layer-index/pull/308#issuecomment-295358305

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit Kaiten Mail gesendet.

**Comment by simonpoole** [comment]
Back from the UK: just to clarify the tiling at level 20 is for hysterical reasons :-). From a resolution pov at the latitude the Canton Aargau is 19 is sufficient. When I get around to it I'll likely re-tile both the 2014 and 2016 imagery at level 19. Currently I'm running that for 2016 NIR channel first.

**Comment by Klumbumbus** [comment]
(see https://github.com/osmlab/editor-layer-index/commit/08e962ff1cac480d0e78a34c58d08b0eca4f574f for zoom change)

**Pull request merged**
