### PR TITLE
Add start/end date to AGIS imagery, reduce max zoom and add polygon for 2011

### PR DESCRIPTION
**Pull request by simonpoole**

### CODE REVIEW

**Comment by tyrasd** [comment]
would you like to add the start_date/end_date information to the *AGIS2016* as well?

**Comment by simonpoole** [comment]
@tyrasd well the 2016 has the best flag set so it doesn't really make a difference at this point in time.

**Comment by tyrasd** [comment]
I don't see what the best flag should have to do with the date metadata field, but ok. :man_shrugging:

**Comment by simonpoole** [comment]
Sorting. Assuming younger is better and best is best for an area, adding the dates doesn't make a difference in sorting. I was intending to add them in the future when we remove the best flag, but I can do it it now if you want :-).

**Comment by tyrasd** [comment]
Ah, I see. I've added the dates now in 8a843367d2736baa4bc0a943f8575a252af7fac4, so no one can forget about it later. ;)

**Pull request merged**
