### PR TITLE
USA: CO: Mesa: Add aerial/satellite imagery

### PR DESCRIPTION
**Pull request by ghost**
* 2015 imagery included due to much higher resolution than 2017
images
	* 2017 imagery included since it has a more coverage than the
most recent images (2018).

I got permission via email on 2014-11-25 to use Mesa County data within OpenStreetMap.
I used the implicit permission instead of explicit due to dates. Their policy has probably not changed, in part due to their mention of openstreetmap on their official twitter account in 2016.

### CODE REVIEW

**Comment by ghost** [comment]
For the record:

1. [https://emap.mesacounty.us/Blog/downloading-mesa-county-ortho-photography](https://emap.mesacounty.us/Blog/downloading-mesa-county-ortho-photography)
2. [https://gis.mesacounty.us/gis-history/pages/make-data-available/](https://gis.mesacounty.us/gis-history/pages/make-data-available/)
3. [https://emap.mesacounty.us/Blog/frequently-asked-questions/](https://emap.mesacounty.us/Blog/frequently-asked-questions/)
4. [https://assessor.mesacounty.us/](https://assessor.mesacounty.us/)
5. [http://blog.mesacounty.us/2014/02/go-code-colorado.html](http://blog.mesacounty.us/2014/02/go-code-colorado.html)
6. [https://www.mesacounty.us/contact-us/copyrightdisclaimerprivacy/](https://www.mesacounty.us/contact-us/copyrightdisclaimerprivacy/)

and when downloading data, the following disclaimer appears:

> The Geographic Information System (GIS) and its components are designed as a source of reference for answering inquiries, for planning and for modeling. GIS is not intended or does not replace legal description information in the chain of title and other information contained in official government records such as the County Clerk and Recorders office or the courts. In addition, the representations of locations in this GIS cannot be substituted for actual legal surveys.
> 
> The information contained herein is believed accurate and suitable for the use for the limited uses, and subject to the limitations, set forth above. Mesa County makes no warranty as to the accuracy or suitability of any information contained herein. Users assume all risk and responsibility for any and all damages, including consequential damages, which may flow from the user's use of this information.

This coexists with (6) where it says:
> Mesa County websites are an information service for the citizens of Mesa County. This service is provided to make public information more accessible using current technology. Mesa County does not condone or prohibit the use of public information obtained from Mesa County Home Pages, Websites and Databases on the World Wide Web as a marketable product. Furthermore, Mesa County is not beholding to any single business, person or entity that would assemble public information for profit or personal gain. 
> 
> The information on the Mesa County websites is for reference only and subject to change without notice. While every reasonable effort is taken to assure the accuracy and timeliness of the content of these websites, no guarantee or warranty as to said accuracy and timeliness is warranted. If you believe material contained on a Mesa County website is inaccurate, please contact the webmaster. For the most current and accurate information, please contact the relevant county office or agency. 
> 
> The Geographic Information System (GIS) and its components are designed as a source of reference for answering inquiries, for planning and for modeling. GIS is not intended or does not replace legal description information in the chain of title and other information contained in official government records such as the County Clerk and Recorders office or the courts. In addition, the representations of location in this GIS cannot be substitute for actual legal surveys. The information contained herein is believed accurate and suitable for the limited uses, and subject to the limitations, set forth above. Mesa County makes no warranty as to the accuracy or suitability of any information contained herein. Users ssume all risk and responsibility for any and all damages, including consequential damages, which may flow from the user's use of this information.

**Comment by grischard** [comment]
Thank you!

Can we get a bit more than "a Senior GIS Administrator from Mesa County said that Mesa County data can be used for OpenStreetMap on 11/25/2014"? For example like the email that was included in #532.

**Comment by ghost** [comment]
[Mesa_County_Data.pdf](https://github.com/osmlab/editor-layer-index/files/2274792/Mesa_County_Data.pdf)

[Mesa_County_Data.mbox.zip](https://github.com/osmlab/editor-layer-index/files/2274798/Mesa_County_Data.mbox.zip)

Is that what you were looking for?
I attached the mbox file in case the email printout wasn't enough (i.e., to verify the headers).

For the link referenced in the email ([http://gis.mesacounty.us/datamap.aspx](https://web.archive.org/web/20150905204918/http://gis.mesacounty.us/datamap.aspx)), it is no longer available. It is available at the web archive (which is where I have set the link to go in this post).

When that link is compared with (6) in my previous [post](https://github.com/osmlab/editor-layer-index/pull/520#issuecomment-411217424), their license is now more permissive.

**Comment by grischard** [comment]
That's perfect! Could you please add it to the `sources/north-america/us/co/` directory and link to it in the `license_url` property like we did on [ACTmapi-Imagery.PDF](https://osmlab.github.io/editor-layer-index/sources/australia/au/act/ACTmapi-Imagery.PDF) in [australia/au/act/ACTmapi-Imagery2018.geojson](https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/australia/au/act/ACTmapi-Imagery2018.geojson)?

**Comment by grischard** [comment]
Ta-da! Thanks!

**Comment by ghost** [comment]
No problem. Sorry that it took me awhile to do that.

**Comment by Klumbumbus** [comment]
The link to the license pdf file is not valid: https://osmlab.github.io/sources/north-america/us/co/Mesa_County_Data.pdf

**Comment by grischard** [comment]
Indeed! Fixed in f089f4f, thanks.

**Comment by Klumbumbus** [comment]
two are still wrong :)

**Comment by grischard** [comment]
Dagnabbit. 47045f0

**Pull request merged**
