### PR TITLE
OpenAerialMap Mosaic by Kontur.io

### PR DESCRIPTION
**Pull request by Zkir**
OpenAerialMap Mosaic by Kontur.io has been added.
This is newly developed mosaic layer, which contains all the avalible OAM imagery in one layer. 
New images are displayed over older ones, min/max zooms are tracked.

### CODE REVIEW

**Comment by cicku** [comment]
We have no plan to add this, this is tracked at https://github.com/openstreetmap/iD/issues/8562

**Comment by Zkir** [comment]
> We have no plan to add this, this is tracked at [openstreetmap/iD#8562](https://github.com/openstreetmap/iD/issues/8562)

@cicku, I am a bit confused. 
_This_ is newly developed **mosaic** , which contains all the avalible OAM imagery in **one** layer, so ID does not have to load thousands of images.  New images are displayed over older ones, min/max zooms are tracked, and some other logic is present to make it usable.  
We spend some efforts implementing this. Do you have plans to implement it yourself? ;)

сс: @Komzpa

**Comment by cicku** [comment]
I'm a bit confused as well. What is the logic selecting imageries of the same area, if there are multiple different contributions overlapping with each other?

**Comment by Zkir** [comment]
>What is the logic selecting imageries of the same area, if there are multiple different contributions overlapping with each other?

1. The newer images over older ones.
2. Images which cover huge areas dissapper on certain zooms, depending on actual image resolutuion, to unhide images of smaller areas.

You can explore it via provided tms link or here:
https://disaster.ninja/active/?map=3.416/137.067/39.493&app=58851b50-9574-4aec-a3a6-425fa18dcb54&event=d06ac064-19f3-4e19-9798-d630a1075b6e&feed=kontur-public&layers=KLA__openaerialmap%2CKLA__openaerialmap_cluster

On Disaster.Ninja there are also markes/clusters, to find avalible OAM imagery quicker.

**Comment by cicku** [comment]
Well I really appreciate your input on this, I'm not able to review it anymore. @rbuffat @grischard Please decide.

**Comment by Zkir** [comment]
@rbuffat @grischard any decision?

**Comment by grischard** [comment]
I think this is an elegant solution to adding OAM imagery to the various editors.

Can you please fix this, and I'll merge it?

```json
"privacy_policy_url": false,
```

**Comment by Zkir** [comment]
@grischard, thank you!

 >Can you please fix this, and I'll merge it?

According to the schema, **false** is acceptable value [if there is no existing privacy policy for the imagery](https://github.com/osmlab/editor-layer-index/blob/6a7e27a728bcc33061869f87029e53cec0ea154f/schema.json#L87), and for OAM there is no explicit privacy policy currently.
 
 Or am I missing something obvious?

**Comment by simonpoole** [comment]
Shouldn't this simply be kontour.io's privacy policy, I assume you have one?

**Comment by Zkir** [comment]
@grischard @simonpoole fixed.

**Comment by grischard** [comment]
Perfect!

**Pull request merged**
