### PR TITLE
Add aerial imagery and vector for Wallonia (south of Belgium)

### PR DESCRIPTION
**Pull request by jbelien**
Here is the agreement from SPW (Service Public de Wallonie) for the use of those services : https://wiki.openstreetmap.org/wiki/WikiProject_Belgium/Mapping_resources/PICC

### CODE REVIEW

**Comment by grischard** [comment]
Thank you! Can you please add the license information?

**Comment by jbelien** [comment]
Ouuups ... Sorry I missed it ! Fixing it ASAP :)

**Comment by jbelien** [comment]
Done ! Hope I didn't forget anything this time !

**Comment by grischard** [comment]
That surreal license discussion is so typically Belgian. I love it.

**Comment by jbelien** [comment]
Thanks for the merge 🎉

**Pull request merged**
