### PR TITLE
update sources to include New York State Orthos Online

### PR DESCRIPTION
**Pull request by kennykb**
An attempt at including New York State Orthos Online - issue [345](https://github.com/osmlab/editor-layer-index/issues/345)

Let me know if there's anything I need to do here! 

Reminder: the clearance can be found under 'Disclaimers' at [https://data.ny.gov/Public-Safety/Statewide-Digital-Orthoimagery/amsv-rmfz](https://data.ny.gov/Public-Safety/Statewide-Digital-Orthoimagery/amsv-rmfz): 

Limitations No limitations on use of publicly available imagery.

### CODE REVIEW

**Comment by kennykb** [comment]
Oh, also, is there some sort of automation by which this change propagates over to [https://josm.openstreetmap.de/wiki/Maps](https://josm.openstreetmap.de/wiki/Maps) or does that have to be done separately to have the layer available to JOSM?

**Comment by tyrasd** [comment]
> Oh, also, is there some sort of automation by which this change propagates over to https://josm.openstreetmap.de/wiki/Maps or does that have to be done separately to have the layer available to JOSM?

It needs to be done manually, but one can also set-up JOSM to use this imagery source: https://github.com/osmlab/editor-layer-index#using-this-index

**Comment by kennykb** [comment]
Sorry, I hadn't seen available_projections in the first five or six GeoJSON files that I'd looked at. It seems that many others have made the same mistake, leading me to presume that the server's announcement of its own capabilities would govern.

I left "CRS:84" out of the list since I didn't see anything else using that namespace, and it's redundant with "EPSG:4326".

**Comment by tyrasd** [comment]
You've probably looked only at tms sources, for which it's not necessary to specify the field. Or are there still wms layers in the index without `available_projections`?

The idea behind this field is the following: Let's say there's some software (e.g. an osm editor) using this index, which only supports a handful of projections (say, EPSG:3857 and its pseudonyms). Using the `available_projections`, the software can decide which layers it should show on a list of compatible layers, without having to check all `GetCapabilities` of all possible WMS layers all of the time (or alternatively, when showing an unfiltered list: without having to give the user an error message after they selected a layer which will turn out to be incompatible with the supported projections of the software). Hope this clarifies this a bit.

**Pull request merged**
