### PR TITLE
Add "dl-zero-de/2.0"  to list of compatible licenses

### PR DESCRIPTION
**Pull request by pathmapper**
There are already many sources with this license included in the `editor-layer-index`.

### CODE REVIEW

**Comment by cicku** [comment]
I wouldn't say it is very appropriate to mention it here, because the license is not in English. Can you confirm if this is what you mean?

https://spdx.org/licenses/DL-DE-BY-2.0.html

**Comment by pathmapper** [comment]
> I wouldn't say it is very appropriate to mention it here, because the license is not in English.

It is, the English version is at the bottom of the page :-)

>  Can you confirm if this is what you mean?
> 
> https://spdx.org/licenses/DL-DE-BY-2.0.html

No, the one you linked is with attribution and not the right one, seems like it is currently not listed on https://spdx.org/licenses/.

Here is the right one which is also linked in the PR:
https://www.govdata.de/dl-de/zero-2-0



grafik

**Comment by pathmapper** [comment]
@cicku thanks for making me aware, that `dl-zero-de/2.0` isn't listed on https://spdx.org/licenses/.

I've submitted a request to add it -> https://github.com/spdx/license-list-XML/issues/2072

**Comment by pathmapper** [comment]
Thanks @cicku

**Pull request merged**
