### PR TITLE
new aerial photo Dakota County, MN 2020

### PR DESCRIPTION
**Pull request by DcJoeS**
new aerial photo Dakota County, MN 2020

### CODE REVIEW

**Comment by rbuffat** [comment]
@DcJoeS would it be possible to merge upstream/gh-pages into your branch?

**Comment by andrewharvey** [comment]
Hoping that a rebase against the latest gh-pages branch would resolve the issue here.

**Comment by DcJoeS** [comment]
Sorry for the delay.  Not a big github user, took a bit to sort out getting things updated.

**Comment by rbuffat** [comment]
@DcJoeS No problem and thanks for making the effort! We should probably document this better. 

The attirubtion url seems to be not existent. As license url I would propose to use https://resources.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_co_dakota/base_aerialphotography_2020_sprg/metadata/metadata.html as this url links to the dataset. 

The use constraints are as follows:

> Use Constraints | Dakota County GIS Database Disclaimer NOTICE: Dakota County Geographic Information System (GIS) Data are made available pursuant to the Minnesota Government Data Practices Act (Minnesota Statutes Chapter 13) THE GIS DATA ARE PROVIDED TO YOU AS IS AND WITHOUT ANY WARRANTY AS TO THEIR PERFORMANCE, MERCHANTABILITY, OR FITNESS FOR ANY PARTICULAR PURPOSE. The GIS Data were developed by Dakota County ("County") for their own internal business purposes. The County does not represent or warrant that the GIS Data or the data documentation are error-free, complete, current, or accurate. You are responsible for any consequences resulting from your use of the GIS Data or your reliance on the GIS Data. You should consult the data documentation for this particular GIS Data to determine the limitations of the GIS Data and the precision with which the GIS Data may depict distance, direction, location, or other geographic features. If you transmit or provide the GIS Data (or any portion of it) to another user, you must provide a copy of this disclaimer and the accompanying metadata for this dataset to the user.This imagery is copyrighted and licensed by Nearmap US Inc, which retains ownership of the imagery. It is being provided by Dakota County under the terms of that license. It may be used for any purpose, excluding commercial purpose. Any third party must use this imagery in the ordinary course of their business and may not resell such imagery for the purpose of direct commercial benefit or gain. By accessing this imagery, the user acknowledges these terms and affirms compliance.


>This imagery is copyrighted and licensed by Nearmap US Inc, which retains ownership of the imagery. It is being provided by  Dakota County under the terms of that license.

Not sure to what license terms this refers to.

**Comment by andrewharvey** [comment]
> excluding commercial purpose

show stopper right there, the license as it stands is not compatible for use in OpenStreetMap. Have I missed anything?

**Comment by rbuffat** [comment]
@andrewharvey 

https://www.co.dakota.mn.us/HomeProperty/MappingServices/GISData/Pages/default.aspx seems to have slightly different terms:

> Dakota County provides public GIS data in specific formats and geographic subsets without fees or use restrictions.  By downloading and using this data, you represent that you agree to the Dakota County GIS Database Disclaimer below. 

> Dakota County encourages public use of this GIS data.  The County Board of Commissioners adopted a policy of free and open GIS data, in collaboration with the other six metropolitan counties in the Twin Cities.  More information on this initiative is available from MetroGIS. 

> Dakota County GIS Database Disclaimer
> NOTICE: Dakota County Geographic Information System (GIS) Data are made available pursuant to the Minnesota Government Data Practices Act (Minnesota Statutes Chapter 13) THE GIS DATA ARE PROVIDED TO YOU AS IS AND WITHOUT ANY WARRANTY AS TO THEIR PERFORMANCE, MERCHANTABILITY, OR FITNESS FOR ANY PARTICULAR PURPOSE. The GIS Data were developed by Dakota County (“County”) for their own internal business purposes. The County does not represent or warrant that the GIS Data or the data documentation are error-free, complete, current, or accurate. You are responsible for any consequences resulting from your use of the GIS Data or your reliance on the GIS Data. You should consult the data documentation for this particular GIS Data to determine the limitations of the GIS Data and the precision with which the GIS Data may depict distance, direction, location, or other geographic features. If you transmit or provide the GIS Data (or any portion of it) to another user, you must provide a copy of this disclaimer and the accompanying metadata for this dataset to the user.

No mentioning of "excluding commercial" or Nearmap US copyright / license terms.

**Comment by andrewharvey** [comment]
> https://www.co.dakota.mn.us/HomeProperty/MappingServices/GISData/Pages/default.aspx seems to have slightly different terms:

That page doesn't load for me, but based on the URL structure it's likely for their other GIS data and not this 2020 imagery layer which was purchased from a private company Nearmap under license, so it's not owned by Dakota County, so Dakota County can only license it so much as their license from Nearmap allows, which excludes commercial use.

**Comment by rbuffat** [comment]
The same applies for https://resources.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_co_dakota/base_aerialphotography_2019_fall/metadata/metadata.html
which is already included in ELI: https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/north-america/us/mn/DakotaCountyImagery2019SpringLeafOff.geojson

**Comment by rbuffat** [comment]
> > https://www.co.dakota.mn.us/HomeProperty/MappingServices/GISData/Pages/default.aspx seems to have slightly different terms:
> 
> That page doesn't load for me, but based on the URL structure it's likely for their other GIS data and not this 2020 imagery layer which was purchased from a private company Nearmap under license, so it's not owned by Dakota County, so Dakota County can only license it so much as their license from Nearmap allows, which excludes commercial use.

The link works intermittently for me. The page links to the following data catalog: https://gisdata.mn.gov/organization/us-mn-co-dakota

**Comment by andrewharvey** [comment]
> The same applies for https://resources.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_co_dakota/base_aerialphotography_2019_fall/metadata/metadata.html
which is already included in ELI: https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/north-america/us/mn/DakotaCountyImagery2019SpringLeafOff.geojson

I must have missed that in #753 or maybe it wasn't mentioned then.

I've reviewed Nearmap's standard license terms in Australia before and I came to the conclusion that I still wasn't sure if it lets you trace and own that derived data, but to er on the side of caution we probably shouldn't use it. In fact we have got very narrow waivers to trace from Nearmap for some disaster mappathons, but outside of that we shouldn't use it unless this has been clarified.

> The page links to the following data catalog: https://gisdata.mn.gov/organization/us-mn-co-dakota

Yep that works and also lists the same Nearmap conditions.

So my conclusion is still that this source can't be used, and we should remove the 2019 Fall one too (Spring 2019 seems okay because it doesn't use Nearmap - https://resources.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_co_dakota/base_aerialphotography_2019_sprg/metadata/metadata.html). So unless there's anything I've missed where this has been looked at from the licensing side before.

**Comment by rbuffat** [comment]
> I must have missed that in #753 or maybe it wasn't mentioned then.

Sorry, I missed that there are fall and spring imagery, I only looked at the year. The source included is for spring: https://resources.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_co_dakota/base_aerialphotography_2019_sprg/metadata/metadata.html

https://github.com/osmlab/editor-layer-index/blob/gh-pages/sources/north-america/us/mn/DakotaCountyImagery2019SpringLeafOff.geojson

Which is not from Nearmap. But we should update the license url to link to the metadata page.

**Comment by DcJoeS** [comment]
I'll check with our US based Nearmap representatives and our contract this week to get a clear answer.

**Comment by DcJoeS** [comment]
Sorry, this got put on the back burner for a bit, but it was picked back up a couple of weeks ago.  Long story short, we have an agreement that differs from the standard agreement that you may be familiar with.  We are allowed to share the imagery, but no one can sell the imagery.  OSM can collect data on the imagery.  And we able to get a letter from them.  It is now referenced in the image service itself too.  Does this cover it?
 https://gisimg.co.dakota.mn.us/mrsid/base_aerialphotography_2020_sprg/Nearmap_DakotaCounty_SIGNED.pdf

**Comment by DcJoeS** [comment]
> Sorry, this got put on the back burner for a bit, but it was picked back up a couple of weeks ago. Long story short, we have an agreement that differs from the standard agreement that you may be familiar with. We are allowed to share the imagery, but no one can sell the imagery. OSM can collect data on the imagery. And we able to get a letter from them. It is now referenced in the image service itself too. Does this cover it?
> https://gisimg.co.dakota.mn.us/mrsid/base_aerialphotography_2020_sprg/Nearmap_DakotaCounty_SIGNED.pdf

@rbuffat and @andrewharvey just checking in, is this sufficient?

**Comment by rbuffat** [comment]
@DcJoeS Sorry for the long delay. I suppose point a) is problematic, as I don't think there is a functionality to ensure that users agree to imagery specific license terms before they can use it.

@grischard  What is your opinion here?

**Comment by cicku** [comment]
Nearmap cannot be used.

If they decide to give you a waiver (likely won't happen), please reopen later.

**Pull request closed without merging**
