### PR TITLE
Rio de Janeiro WMS imagery 2013 and 2015

### PR DESCRIPTION
**Pull request by Skippern**
WMS Images available from Prefecture de Rio de Janeiro, 2013 and 2015 with proper bounding boxes.

### CODE REVIEW

**Comment by simon04** [comment]
Fixed indentation and merged manually. Thanks.

**Comment by Skippern** [comment]
Thanks @simon04, much appreciated

**Comment by Klumbumbus** [comment]
@Skippern can you please give a link to the license or permission to use these in osm?

**Comment by Skippern** [comment]
@Klumbumbus I have forwarded the question to the users in Rio de Janeiro, who have direct knowledge, hope to have an answer for you shortly.

**Comment by Skippern** [comment]
@Klumbumbus According to [data.rio](http://data.rio), the shared data is ODbL compatible, link shared by @nighto

**Comment by Klumbumbus** [comment]
The 2015 imagery has its max resolution at zoom 13, right?

**Comment by Skippern** [comment]
Didn't check that one in detail, 2013 was very high resolution, but possible that 2015 had lover resolution.

**Comment by rbuffat** [comment]
@Skippern @nighto I can't find any license information for the wms server on data.rio. Probably the site has changed. Do you know if the same license still applies to the sources?

**Pull request closed without merging**
