### PR TITLE
[Help needed] Add imagery for DE/Ludwigshafen

### PR DESCRIPTION
**Pull request by coolultra1**
More information on the permission:

https://ludwigshafen.de/buergerservice/dienstleistungen/geodatendienste-wms

I've got their kind-of stretchy wording there confirmed to fit to OSM via an Email conversation with the city administration, so everything should be all right here.

### CODE REVIEW

**Comment by coolultra1** [comment]
Anybody know how I would fix the GeoJSON? I'm actually clueless.

**Comment by arch0345** [comment]
> Anybody know how I would fix the GeoJSON? I'm actually clueless.

https://github.com/coolultra1/editor-layer-index-1/pull/1 should fix the geometry

**Comment by coolultra1** [comment]
@arch0345 Thank you very much; What was the trick? How'd you do it so easily?

**Comment by arch0345** [comment]
I just copy pasted the suggested geometry from the CI error message and reformatted it in VSCode

**Pull request merged**
