### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks but I'm moving this project to node.js asap.  see #168

**Comment by iandees** [comment]
Well hurry up, @bhousel ! 😛

**Comment by bhousel** [comment]
> Well hurry up, @bhousel ! 😛

Third time I've been told that _today_

**Comment by simon04** [comment]
Thanks for clearly communicating the project direction here and in #201.  :disappointed:

**Comment by iandees** [comment]
@simon04 we appreciate your contribution, it's just a busy/long day over here in the USA...

I'm happy to review this later today.

**Comment by simon04** [comment]
Ah, right – there has been _something_ going on :wink:

**Pull request merged**
